import type { ModuleData, ModuleDataMap, ModuleType } from '../../../types/spatial'
import { commandsFor, fieldsFor } from '../../../widgets/fields'
import { formatVitalValue } from '../../../utils/widgetDisplayValue'
import { WidgetPanel } from '../WidgetPanel'

type ExpansionType = Extract<ModuleType,
  'clock_pulse'|'comparator'|'aggregator'|'range_mapper'|'latch'|'random_picker'|'sequencer'|'template'|'recorder'|'notifier'|
  'subscriptions'|'debt_payoff'|'expense_split'|'invoices'|'meal_planner'|'recipe'|'home_maintenance'|'chore_rotation'|'renewals_vault'|'medications'|'workout_plan'|'job_applications'|'okr'|'decision_journal'|'weekly_review'|'snippet_library'|'keep_in_touch'|'gifts_occasions'|'trip_itinerary'|'guest_list'
>
type D<K extends ModuleType> = ModuleDataMap[K]
type Props = { type: ExpansionType; data: ModuleData; onChange: (data: ModuleData) => void }
const inputClass='gp-input min-w-0 px-2 py-1.5 outline-none'
const buttonClass='rounded-lg border border-transparent bg-white/[0.04] px-2.5 py-1.5 text-[10px] font-semibold text-neutral-300 hover:bg-white/[0.08] active:scale-95'

function NumberBox({value,onChange,label}:{value:number;onChange:(value:number)=>void;label:string}){return <label data-island-size="width" data-island-min-w="72" className="gp-island flex min-w-0 flex-1 flex-col gap-1 p-2"><span className="gp-label">{label}</span><input aria-label={label} type="number" value={Number.isFinite(value)?value:0} onChange={e=>onChange(Number(e.target.value)||0)} className={inputClass}/></label>}
function TextBox({value,onChange,label,type='text'}:{value:string;onChange:(value:string)=>void;label:string;type?:string}){return <label data-island-size="width" data-island-min-w="120" className="gp-island flex min-w-0 flex-1 flex-col gap-1 p-2"><span className="gp-label">{label}</span><input aria-label={label} type={type} value={value} onChange={e=>onChange(e.target.value)} className={inputClass}/></label>}
function SelectBox({value,onChange,label,options}:{value:string;onChange:(value:string)=>void;label:string;options:readonly string[]}){return <label data-island-size="width" data-island-min-w="104" className="gp-island flex min-w-0 flex-1 flex-col gap-1 p-2"><span className="gp-label">{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className={inputClass}>{options.map(option=><option key={option} value={option}>{option.replaceAll('_',' ')}</option>)}</select></label>}
function Check({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}){return <label className="flex items-center gap-2 text-[11px] text-neutral-400"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="accent-emerald-400"/>{label}</label>}
function runCommand(type:ModuleType,key:string,data:ModuleData,onChange:(data:ModuleData)=>void){const command=commandsFor(type).find(item=>item.key===key);if(command)onChange(command.run(data))}

function Vitals({type,data}:{type:ModuleType;data:ModuleData}){const values=fieldsFor(type).filter(field=>!field.set&&field.valueType!=='series').slice(0,3);return <div className="gp-vitals-grid grid grid-cols-3 gap-2">{values.map(field=>{const raw=field.get(data);const value=formatVitalValue(raw);return <div key={field.key} className="gp-well min-w-0 overflow-hidden px-2 py-2"><div className="gp-label">{field.label}</div><div className="gp-value gp-vital-value" title={String(raw ?? '')}>{value}</div></div>})}</div>}

export function ExpansionWidget({type,data,onChange}:Props){
  if(type==='clock_pulse'){const q=data as D<'clock_pulse'>;return <div className="space-y-3"><div className={`rounded-xl border px-3 py-2 text-center text-xs font-semibold ${fieldsFor(type)[0]!.get(data)?'border-emerald-400/50 bg-emerald-400/10 text-emerald-300':'gp-hairline text-neutral-500'}`}>{fieldsFor(type)[0]!.get(data)?'Pulse active':'Waiting for schedule'}</div><div className="flex gap-2"><SelectBox label="Mode" value={q.mode} options={['daily','weekly','interval','window']} onChange={v=>onChange({...q,mode:v as D<'clock_pulse'>['mode']})}/>{q.mode==='interval'?<NumberBox label="Minutes" value={q.intervalMinutes} onChange={v=>onChange({...q,intervalMinutes:Math.max(1,v)})}/>:<TextBox label="Time" type="time" value={q.time} onChange={v=>onChange({...q,time:v})}/>}</div><Vitals type={type} data={data}/></div>}
  if(type==='comparator'){const q=data as D<'comparator'>;return <div className="space-y-3"><div className="gp-comparator-row flex gap-2"><SelectBox label="Rule" value={q.op} options={['gt','gte','lt','lte','eq','between']} onChange={v=>onChange({...q,op:v as D<'comparator'>['op']})}/><NumberBox label="A" value={q.a} onChange={v=>onChange({...q,a:v})}/><NumberBox label="B" value={q.b} onChange={v=>onChange({...q,b:v})}/></div><Vitals type={type} data={data}/></div>}
  if(type==='aggregator'){const q=data as D<'aggregator'>;return <div className="space-y-3"><SelectBox label="Combine as" value={q.mode} options={['avg','min','max','count_nonzero','count_true']} onChange={v=>onChange({...q,mode:v as D<'aggregator'>['mode']})}/><div className="grid grid-cols-3 gap-1.5">{q.slots.map((value,index)=><NumberBox key={index} label={`${index+1}`} value={value} onChange={v=>{const slots=[...q.slots];slots[index]=v;onChange({...q,slots})}}/>)}</div><Vitals type={type} data={data}/></div>}
  if(type==='range_mapper'){const q=data as D<'range_mapper'>;return <div className="space-y-3"><NumberBox label="Input" value={q.input} onChange={v=>onChange({...q,input:v})}/><div className="space-y-1">{q.bands.map((band,index)=><div key={band.id} className="flex gap-1"><input value={band.emoji??''} aria-label={`Band ${index+1} emoji`} onChange={e=>onChange({...q,bands:q.bands.map(row=>row.id===band.id?{...row,emoji:e.target.value}:row)})} className={`${inputClass} w-10`}/><input value={band.label} aria-label={`Band ${index+1} label`} onChange={e=>onChange({...q,bands:q.bands.map(row=>row.id===band.id?{...row,label:e.target.value}:row)})} className={`${inputClass} flex-1`}/><input type="number" value={Number.isFinite(band.upTo)?band.upTo:''} placeholder="∞" aria-label={`Band ${index+1} upper bound`} onChange={e=>onChange({...q,bands:q.bands.map(row=>row.id===band.id?{...row,upTo:e.target.value===''?Infinity:Number(e.target.value)}:row)})} className={`${inputClass} w-20`}/></div>)}</div><Vitals type={type} data={data}/></div>}
  if(type==='latch'){const q=data as D<'latch'>;return <div className="space-y-3"><NumberBox label="Current" value={q.current} onChange={v=>onChange({...q,current:v})}/><button className={`${buttonClass} w-full`} onClick={()=>runCommand(type,'capture',data,onChange)}>Capture baseline</button><Vitals type={type} data={data}/></div>}
  if(type==='random_picker'){const q=data as D<'random_picker'>;return <div className="flex h-full flex-col gap-1.5"><WidgetPanel grip={false} island="options" sizing="free" className="min-h-0 flex-1 space-y-2 p-3">{q.options.map(option=><div key={option.id} className="flex gap-2"><input value={option.text} aria-label="Option" onChange={e=>onChange({...q,options:q.options.map(row=>row.id===option.id?{...row,text:e.target.value}:row)})} className={`${inputClass} flex-1`}/><input type="number" min="0" value={option.weight} aria-label="Weight" onChange={e=>onChange({...q,options:q.options.map(row=>row.id===option.id?{...row,weight:Number(e.target.value)}:row)})} className={`${inputClass} w-16`}/></div>)}</WidgetPanel><WidgetPanel grip={false} island="result" sizing="width" className="shrink-0 space-y-2 p-3"><div className="rounded-xl bg-rose-400/10 px-3 py-2 text-center text-sm font-semibold text-rose-200">{q.pick||'Ready to decide'}</div><button className={`${buttonClass} w-full`} onClick={()=>runCommand(type,'roll',data,onChange)}>Roll</button></WidgetPanel></div>}
  if(type==='sequencer'){const q=data as D<'sequencer'>;return <div className="space-y-3">{q.steps.map((step,index)=><div key={step.id} className={`flex items-center gap-2 rounded-lg px-2 py-1 ${index===q.activeIndex?'bg-indigo-400/12 text-indigo-200':'text-neutral-500'}`}><span className="w-5 text-[10px]">{index+1}</span><input value={step.text} aria-label={`Step ${index+1}`} onChange={e=>onChange({...q,steps:q.steps.map(row=>row.id===step.id?{...row,text:e.target.value}:row)})} className="min-w-0 flex-1 bg-transparent text-xs outline-none"/></div>)}<div className="flex gap-2"><button className={`${buttonClass} flex-1`} onClick={()=>runCommand(type,'advance',data,onChange)}>Advance</button><button className={buttonClass} onClick={()=>runCommand(type,'reset',data,onChange)}>Reset</button></div><Check label="Loop" checked={q.loop} onChange={v=>onChange({...q,loop:v})}/><Vitals type={type} data={data}/></div>}
  if(type==='template'){const q=data as D<'template'>;return <div className="space-y-3"><textarea aria-label="Template" value={q.template} onChange={e=>onChange({...q,template:e.target.value})} className={`${inputClass} min-h-16 w-full resize-none`}/><div className="grid grid-cols-2 gap-2">{(['A','B','C','D'] as const).map(key=><TextBox key={key} label={key} value={q[`slot${key}`]} onChange={v=>onChange({...q,[`slot${key}`]:v})}/>)}</div><div className="rounded-lg bg-emerald-400/8 p-2 text-xs text-emerald-200">{String(fieldsFor(type).find(f=>f.key==='text')?.get(data)??'')}</div></div>}
  if(type==='recorder'){const q=data as D<'recorder'>;const max=Math.max(1,...q.samples.map(point=>Math.abs(point.v)));return <div className="space-y-3"><div className="flex gap-2"><NumberBox label="Input" value={q.input} onChange={v=>onChange({...q,input:v,...(q.mode==='on_change'?{samples:[...q.samples,{t:Date.now(),v}].slice(-400),lastRecordedAt:Date.now()}: {})})}/><SelectBox label="Mode" value={q.mode} options={['on_change','daily','on_command']} onChange={v=>onChange({...q,mode:v as D<'recorder'>['mode']})}/></div><svg viewBox="0 0 240 54" className="h-14 w-full overflow-visible rounded-lg bg-white/[0.025]">{q.samples.length>1&&<polyline fill="none" stroke="#4ade80" strokeWidth="2" points={q.samples.map((point,index)=>`${index/(q.samples.length-1)*240},${27-point.v/max*22}`).join(' ')}/>}</svg><button className={`${buttonClass} w-full`} onClick={()=>runCommand(type,'record',data,onChange)}>Record now</button><Vitals type={type} data={data}/></div>}
  if(type==='notifier'){const q=data as D<'notifier'>;return <div className="space-y-3"><TextBox label="Message" value={q.message} onChange={v=>onChange({...q,message:v})}/><div className="gp-notifier-controls flex gap-2"><SelectBox label="Channel" value={q.channel} options={['toast','browser']} onChange={v=>onChange({...q,channel:v as D<'notifier'>['channel']})}/><NumberBox label="Cooldown min" value={q.cooldownMinutes} onChange={v=>onChange({...q,cooldownMinutes:Math.max(0,v)})}/></div><Check label="Armed" checked={q.armed} onChange={v=>onChange({...q,armed:v,...(!q.armed&&v?{pendingFireAt:Date.now()}: {})})}/><button className={`${buttonClass} w-full`} onClick={()=>runCommand(type,'notify',data,onChange)}>Send test notification</button><Vitals type={type} data={data}/></div>}
  return <LifeWidget type={type} data={data} onChange={onChange}/>
}

type GenericRow={id:string}&Record<string,unknown>
type Column={key:string;label:string;kind?:'text'|'number'|'date'|'checkbox'|'select';options?:readonly string[]}
const rowColumns:Partial<Record<ExpansionType,Column[]>>={
  subscriptions:[{key:'name',label:'Name'},{key:'cost',label:'Cost',kind:'number'},{key:'cycle',label:'Cycle',kind:'select',options:['monthly','yearly','weekly']},{key:'renewsOn',label:'Renews',kind:'date'},{key:'active',label:'Active',kind:'checkbox'}],
  debt_payoff:[{key:'name',label:'Debt'},{key:'balance',label:'Balance',kind:'number'},{key:'apr',label:'APR %',kind:'number'},{key:'minPayment',label:'Minimum',kind:'number'}],
  expense_split:[{key:'desc',label:'Expense'},{key:'amount',label:'Amount',kind:'number'},{key:'paidBy',label:'Paid by'}],
  invoices:[{key:'client',label:'Client'},{key:'amount',label:'Amount',kind:'number'},{key:'due',label:'Due',kind:'date'},{key:'status',label:'Status',kind:'select',options:['draft','sent','paid']}],
  home_maintenance:[{key:'task',label:'Task'},{key:'everyMonths',label:'Every months',kind:'number'},{key:'lastDone',label:'Last done',kind:'date'}],
  renewals_vault:[{key:'item',label:'Item'},{key:'expires',label:'Expires',kind:'date'},{key:'renewLeadDays',label:'Lead days',kind:'number'}],
  job_applications:[{key:'company',label:'Company'},{key:'role',label:'Role'},{key:'stage',label:'Stage',kind:'select',options:['wishlist','applied','screen','interview','offer','closed']},{key:'followUpBy',label:'Follow up',kind:'date'}],
  decision_journal:[{key:'decision',label:'Decision'},{key:'confidence',label:'Confidence',kind:'number'},{key:'reviewOn',label:'Review',kind:'date'},{key:'verdict',label:'Verdict',kind:'select',options:['','hit','miss','mixed']}],
  keep_in_touch:[{key:'name',label:'Person'},{key:'cadenceDays',label:'Every days',kind:'number'},{key:'lastContact',label:'Last contact',kind:'date'}],
  gifts_occasions:[{key:'person',label:'Person'},{key:'date',label:'Date',kind:'date'},{key:'budget',label:'Budget',kind:'number'},{key:'bought',label:'Bought',kind:'checkbox'}],
  guest_list:[{key:'name',label:'Guest'},{key:'status',label:'RSVP',kind:'select',options:['invited','yes','no','maybe']},{key:'plusOnes',label:'+1s',kind:'number'},{key:'dietary',label:'Dietary'}],
}

function RowTable({rows,columns,onRows}:{rows:GenericRow[];columns:Column[];onRows:(rows:GenericRow[])=>void}){return <div className="space-y-2">{rows.map((row,rowIndex)=><div key={row.id} className="gp-subdivision rounded-xl border gp-hairline bg-white/[0.02] p-2"><div className="grid grid-cols-2 gap-1.5">{columns.map(column=>{const value=row[column.key];if(column.kind==='checkbox')return <Check key={column.key} label={column.label} checked={Boolean(value)} onChange={v=>onRows(rows.map(item=>item.id===row.id?{...item,[column.key]:v}:item))}/>;if(column.kind==='select')return <SelectBox key={column.key} label={column.label} value={String(value??'')} options={column.options??[]} onChange={v=>onRows(rows.map(item=>item.id===row.id?{...item,[column.key]:v}:item))}/>;if(column.kind==='number')return <NumberBox key={column.key} label={column.label} value={Number(value)||0} onChange={v=>onRows(rows.map(item=>item.id===row.id?{...item,[column.key]:v}:item))}/>;return <TextBox key={column.key} label={column.label} type={column.kind==='date'?'date':'text'} value={String(value??'')} onChange={v=>onRows(rows.map(item=>item.id===row.id?{...item,[column.key]:v}:item))}/>})}</div><button aria-label={`Remove row ${rowIndex+1}`} className="mt-1 text-[9px] text-neutral-600 hover:text-red-400" onClick={()=>onRows(rows.filter(item=>item.id!==row.id))}>Remove</button></div>)}<button className={`${buttonClass} w-full`} onClick={()=>onRows([...rows,{id:crypto.randomUUID(),...Object.fromEntries(columns.map(column=>[column.key,column.kind==='number'?0:column.kind==='checkbox'?false:column.options?.[0]??'']))}])}>Add row</button></div>}

function LifeWidget({type,data,onChange}:Props){
  if(type==='meal_planner'){const q=data as D<'meal_planner'>;const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];const ensureSlot=(day:number,meal:'breakfast'|'lunch'|'dinner')=>q.week.find(item=>item.day===day&&item.meal===meal)??{id:`${day}-${meal}`,day,meal,dish:''};return <div className="space-y-3"><div className="grid grid-cols-7 gap-1">{days.map((day,dayIndex)=><div key={day} className="min-w-0"><div className="mb-1 text-center text-[8px] font-semibold uppercase text-neutral-600">{day}</div>{(['breakfast','lunch','dinner'] as const).map(meal=>{const slot=ensureSlot(dayIndex,meal);return <input key={meal} aria-label={`${day} ${meal}`} value={slot.dish} placeholder={meal[0]?.toUpperCase()} onChange={e=>{const exists=q.week.some(item=>item.id===slot.id);onChange({...q,week:exists?q.week.map(item=>item.id===slot.id?{...item,dish:e.target.value}:item):[...q.week,{...slot,dish:e.target.value}]})}} className="mb-1 w-full rounded border gp-hairline bg-black/15 px-1 py-1 text-[9px] text-neutral-200 outline-none"/>})}</div>)}</div><textarea aria-label="Shopping list" value={q.shoppingList} placeholder="Shopping list…" onChange={e=>onChange({...q,shoppingList:e.target.value})} className={`${inputClass} min-h-14 w-full resize-none`}/><Vitals type={type} data={data}/></div>}
  if(type==='workout_plan'){const q=data as D<'workout_plan'>;const day=q.days[q.activeDay]??q.days[0];if(!day)return <Vitals type={type} data={data}/>;return <div className="space-y-3"><TextBox label="Session" value={day.label} onChange={v=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,label:v}:item)})}/>{day.exercises.map(exercise=><div key={exercise.id} className="grid grid-cols-[1fr_48px_48px_54px] gap-1.5"><input aria-label="Exercise" value={exercise.name} onChange={e=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,exercises:item.exercises.map(row=>row.id===exercise.id?{...row,name:e.target.value}:row)}:item)})} className={inputClass}/><NumberBox label="Sets" value={exercise.sets} onChange={v=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,exercises:item.exercises.map(row=>row.id===exercise.id?{...row,sets:v}:row)}:item)})}/><NumberBox label="Reps" value={exercise.reps} onChange={v=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,exercises:item.exercises.map(row=>row.id===exercise.id?{...row,reps:v}:row)}:item)})}/><NumberBox label="Kg" value={exercise.weight} onChange={v=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,exercises:item.exercises.map(row=>row.id===exercise.id?{...row,weight:v}:row)}:item)})}/><Check label="Done" checked={exercise.done} onChange={v=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,exercises:item.exercises.map(row=>row.id===exercise.id?{...row,done:v}:row)}:item)})}/></div>)}<Vitals type={type} data={data}/></div>}
  if(type==='snippet_library'){const q=data as D<'snippet_library'>;return <div className="space-y-2">{[...q.entries].sort((a,b)=>b.useCount-a.useCount).map(entry=><div key={entry.id} className="rounded-xl border gp-hairline p-2"><TextBox label="Snippet" value={entry.title} onChange={v=>onChange({...q,entries:q.entries.map(item=>item.id===entry.id?{...item,title:v}:item)})}/><textarea aria-label={`${entry.title} body`} value={entry.body} onChange={e=>onChange({...q,entries:q.entries.map(item=>item.id===entry.id?{...item,body:e.target.value}:item)})} className={`${inputClass} mt-1 min-h-12 w-full resize-none`}/><button className={`${buttonClass} mt-1`} onClick={()=>{void navigator.clipboard?.writeText(entry.body);onChange({...q,entries:q.entries.map(item=>item.id===entry.id?{...item,useCount:item.useCount+1}:item)})}}>Copy · {entry.useCount}</button></div>)}<Vitals type={type} data={data}/></div>}
  if(type==='trip_itinerary'){
    const q=data as D<'trip_itinerary'>
    return <div className="space-y-3">
      <TextBox label="Start" type="date" value={q.startDate} onChange={v=>onChange({...q,startDate:v})}/>
      {q.days.map(day=><div key={day.id} className="gp-island p-2">
        <TextBox label="Day" type="date" value={day.date} onChange={v=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,date:v}:item)})}/>
        {day.legs.map(leg=><div key={leg.id} className="mt-2 grid grid-cols-[96px_minmax(0,1fr)_minmax(0,1fr)] gap-2">
          <input type="time" aria-label="Leg time" value={leg.time} onChange={e=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,legs:item.legs.map(row=>row.id===leg.id?{...row,time:e.target.value}:row)}:item)})} className={`${inputClass} gp-input--compact`}/>
          <input aria-label="Leg activity" value={leg.what} onChange={e=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,legs:item.legs.map(row=>row.id===leg.id?{...row,what:e.target.value}:row)}:item)})} className={inputClass}/>
          <input aria-label="Leg place" value={leg.where} onChange={e=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,legs:item.legs.map(row=>row.id===leg.id?{...row,where:e.target.value}:row)}:item)})} className={inputClass}/>
          <div className="col-span-3 px-1"><Check label="Booked" checked={leg.booked} onChange={v=>onChange({...q,days:q.days.map(item=>item.id===day.id?{...item,legs:item.legs.map(row=>row.id===leg.id?{...row,booked:v}:row)}:item)})}/></div>
        </div>)}
      </div>)}
      <Vitals type={type} data={data}/>
    </div>
  }
  if(type==='expense_split'){const q=data as D<'expense_split'>;return <div className="space-y-3"><TextBox label="People (comma separated)" value={q.people.join(', ')} onChange={v=>onChange({...q,people:v.split(',').map(person=>person.trim()).filter(Boolean)})}/><TextBox label="You" value={q.you} onChange={v=>onChange({...q,you:v})}/><Vitals type={type} data={data}/><RowTable rows={q.expenses as unknown as GenericRow[]} columns={rowColumns.expense_split??[]} onRows={rows=>onChange({...q,expenses:rows.map(row=>({...row,splitAmong:q.people})) as unknown as D<'expense_split'>['expenses']})}/></div>}
  const columns=rowColumns[type]
  if(columns&&'rows' in (data as object)){const rows=(data as unknown as {rows:GenericRow[]}).rows;return <div className="space-y-3"><Vitals type={type} data={data}/><RowTable rows={rows} columns={columns} onRows={next=>onChange({...data as object,rows:next} as unknown as ModuleData)}/>{type==='debt_payoff'&&<NumberBox label="Extra monthly payment" value={(data as D<'debt_payoff'>).extraPayment} onChange={v=>onChange({...data as D<'debt_payoff'>,extraPayment:v})}/>}</div>}
  if(type==='recipe'){const q=data as D<'recipe'>;return <div className="space-y-3"><NumberBox label="Servings" value={q.servings} onChange={v=>onChange({...q,servings:Math.max(1,v)})}/><RowTable rows={q.ingredients as unknown as GenericRow[]} columns={[{key:'qty',label:'Qty',kind:'number'},{key:'unit',label:'Unit'},{key:'item',label:'Ingredient'}]} onRows={rows=>onChange({...q,ingredients:rows as unknown as D<'recipe'>['ingredients']})}/><Vitals type={type} data={data}/></div>}
  if(type==='chore_rotation'){const q=data as D<'chore_rotation'>;return <div className="space-y-3"><TextBox label="People (comma separated)" value={q.people.join(', ')} onChange={v=>onChange({...q,people:v.split(',').map(x=>x.trim()).filter(Boolean)})}/><TextBox label="Chores (comma separated)" value={q.chores.join(', ')} onChange={v=>onChange({...q,chores:v.split(',').map(x=>x.trim()).filter(Boolean)})}/><button className={`${buttonClass} w-full`} onClick={()=>runCommand(type,'rotate',data,onChange)}>Rotate now</button><Vitals type={type} data={data}/></div>}
  if(type==='medications'){const q=data as D<'medications'>;return <div className="space-y-3">{q.rows.map(row=><div key={row.id} className="rounded-xl border gp-hairline p-2"><TextBox label="Medication" value={row.name} onChange={v=>onChange({...q,rows:q.rows.map(item=>item.id===row.id?{...item,name:v}:item)})}/><div className="mt-2 flex gap-1">{row.takenToday.map((taken,index)=><button key={index} className={`${buttonClass} flex-1 ${taken?'bg-emerald-400/15 text-emerald-300':''}`} onClick={()=>onChange({...q,rows:q.rows.map(item=>item.id===row.id?{...item,takenToday:item.takenToday.map((value,i)=>i===index?!value:value)}:item)})}>Dose {index+1}</button>)}</div></div>)}<Vitals type={type} data={data}/></div>}
  if(type==='okr'){const q=data as D<'okr'>;return <div className="space-y-3"><TextBox label="Objective" value={q.objective} onChange={v=>onChange({...q,objective:v})}/>{q.keyResults.map(kr=><div key={kr.id} className="flex gap-2"><TextBox label="Key result" value={kr.label} onChange={v=>onChange({...q,keyResults:q.keyResults.map(item=>item.id===kr.id?{...item,label:v}:item)})}/><NumberBox label="Current" value={kr.current} onChange={v=>onChange({...q,keyResults:q.keyResults.map(item=>item.id===kr.id?{...item,current:v}:item)})}/><NumberBox label="Target" value={kr.target} onChange={v=>onChange({...q,keyResults:q.keyResults.map(item=>item.id===kr.id?{...item,target:v}:item)})}/></div>)}<Vitals type={type} data={data}/></div>}
  if(type==='weekly_review'){const q=data as D<'weekly_review'>;return <div className="space-y-3">{q.prompts.map(prompt=><label key={prompt.id} className="block text-[10px] text-neutral-400">{prompt.q}<textarea aria-label={prompt.q} value={prompt.answer} onChange={e=>onChange({...q,prompts:q.prompts.map(item=>item.id===prompt.id?{...item,answer:e.target.value}:item)})} className={`${inputClass} mt-1 min-h-12 w-full resize-none`}/></label>)}<Check label="Review complete" checked={q.completedThisWeek} onChange={v=>onChange({...q,completedThisWeek:v})}/><Vitals type={type} data={data}/></div>}
  return <div className="space-y-3"><Vitals type={type} data={data}/><p className="text-[11px] leading-relaxed text-neutral-500">This system is ready for field wiring. Use the connection mode to automate its live outputs.</p></div>
}
