import type { ModuleData, ModuleDataMap, ModuleType } from '../../types/spatial'
import type { SemanticUnit } from '../../types/fieldConnections'
import type { CommandDescriptor, FieldDescriptor, FieldValue } from '../contracts/fields'
import {
  DAY_MS, appendSample, daysUntilDate, localDayKey, monthsSince, projectDebtPayoff,
  seriesAverage, seriesDelta7d, settleExpenses,
} from '../expansionMath'

type D<K extends ModuleType> = ModuleDataMap[K]
const d = <K extends ModuleType>(data: ModuleData) => data as D<K>
const n = (value: FieldValue) => Array.isArray(value) ? value.at(-1)?.v ?? 0 : typeof value === 'number' ? value : typeof value === 'boolean' ? Number(value) : Number.parseFloat(value) || 0
const s = (value: FieldValue) => Array.isArray(value) ? value.map((point) => point.v).join(', ') : String(value)
const b = (value: FieldValue) => Array.isArray(value) ? value.length > 0 : typeof value === 'boolean' ? value : typeof value === 'number' ? value >= 1 : ['true','1','yes','on'].includes(value.toLowerCase())
const minOrZero = (values: number[]) => values.length ? Math.min(...values) : 0
const txt = (key: string, label: string, get: (data: ModuleData) => string, set?: (data: ModuleData, value: string) => ModuleData, unit?: SemanticUnit): FieldDescriptor => ({ key,label,valueType:'text',get,...(set?{set:(data,value)=>set(data,s(value))}:{}),...(unit?{unit}:{}) })
const num = (key: string, label: string, get: (data: ModuleData) => number, set?: (data: ModuleData, value: number) => ModuleData, timeSensitive=false, unit?: SemanticUnit): FieldDescriptor => ({ key,label,valueType:'number',get,...(set?{set:(data,value)=>set(data,n(value))}:{}),...(timeSensitive?{timeSensitive:true}:{}),...(unit?{unit}:{}) })
const bool = (key: string, label: string, get: (data: ModuleData) => boolean, set?: (data: ModuleData, value: boolean) => ModuleData, timeSensitive=false): FieldDescriptor => ({ key,label,valueType:'boolean',get,...(set?{set:(data,value)=>set(data,b(value))}:{}),...(timeSensitive?{timeSensitive:true}:{}) })

function comparatorResult(data: D<'comparator'>): boolean {
  if (data.op==='gt') return data.a>data.b; if(data.op==='gte') return data.a>=data.b
  if(data.op==='lt') return data.a<data.b; if(data.op==='lte') return data.a<=data.b
  if(data.op==='eq') return Math.abs(data.a-data.b)<1e-9
  return data.a>=data.low&&data.a<=data.high
}
function aggregate(data:D<'aggregator'>):number { const values=data.slots.map(Number); if(data.mode==='min')return Math.min(...values);if(data.mode==='max')return Math.max(...values);if(data.mode==='count_nonzero')return values.filter(Boolean).length;if(data.mode==='count_true')return values.filter(v=>v>=1).length;return values.reduce((a,v)=>a+v,0)/values.length }
function mapped(data:D<'range_mapper'>){ const sorted=[...data.bands].sort((a,b)=>a.upTo-b.upTo);const index=Math.max(0,sorted.findIndex(band=>data.input<=band.upTo));return{band:sorted[index]??sorted.at(-1),index} }
function composed(data:D<'template'>):string { return data.template.replace(/\{([abcd])\}/gi,(_,key:string)=>data[`slot${key.toUpperCase()}` as 'slotA'|'slotB'|'slotC'|'slotD']) }
function pulseState(data:D<'clock_pulse'>,now=new Date()){ const hhmm=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`; if(data.mode==='daily')return hhmm===data.time;if(data.mode==='weekly')return data.days.includes(now.getDay())&&hhmm===data.time;if(data.mode==='interval')return Math.floor(now.getTime()/60_000)%Math.max(1,data.intervalMinutes)===0;return hhmm>=data.windowStart&&hhmm<=data.windowEnd }
function subscriptionMonthly(row:D<'subscriptions'>['rows'][number]){return row.cycle==='yearly'?row.cost/12:row.cycle==='weekly'?row.cost*52/12:row.cost}
function assignments(data:D<'chore_rotation'>){return data.chores.map((chore,index)=>`${data.people[(index+data.offset)%Math.max(1,data.people.length)]??'—'}: ${chore}`).join('; ')}
function okrProgress(data:D<'okr'>){const total=data.keyResults.reduce((sum,kr)=>sum+Math.max(0,kr.weight),0)||1;return data.keyResults.reduce((sum,kr)=>sum+Math.min(1,Math.max(0,kr.current/Math.max(kr.target,1)))*Math.max(0,kr.weight),0)/total*100}

export const EXPANSION_FIELDS: Partial<Record<ModuleType, FieldDescriptor[]>> = {
  clock_pulse:[bool('active','Active',x=>pulseState(d<'clock_pulse'>(x)),undefined,true),bool('pulse','Pulse',x=>pulseState(d<'clock_pulse'>(x)),undefined,true),txt('today','Today',()=>new Date().toLocaleDateString(undefined,{weekday:'long'}))],
  comparator:[num('a','A',x=>d<'comparator'>(x).a,(x,v)=>({...d<'comparator'>(x),a:v})),num('b','B',x=>d<'comparator'>(x).b,(x,v)=>({...d<'comparator'>(x),b:v})),num('low','Low',x=>d<'comparator'>(x).low,(x,v)=>({...d<'comparator'>(x),low:v})),num('high','High',x=>d<'comparator'>(x).high,(x,v)=>({...d<'comparator'>(x),high:v})),bool('result','Result',x=>comparatorResult(d<'comparator'>(x))),num('gap','Gap',x=>d<'comparator'>(x).a-d<'comparator'>(x).b)],
  aggregator:[...Array.from({length:6},(_,i)=>num(`in${i+1}`,`Input ${i+1}`,x=>d<'aggregator'>(x).slots[i]??0,(x,v)=>{const data=d<'aggregator'>(x);const slots=[...data.slots];slots[i]=v;return{...data,slots}})),num('value','Value',x=>aggregate(d<'aggregator'>(x)))],
  range_mapper:[num('input','Input',x=>d<'range_mapper'>(x).input,(x,v)=>({...d<'range_mapper'>(x),input:v})),txt('label','Band label',x=>{const m=mapped(d<'range_mapper'>(x));return`${m.band?.emoji??''} ${m.band?.label??''}`.trim()}),num('bandIndex','Band index',x=>mapped(d<'range_mapper'>(x)).index),bool('topBand','Top band',x=>mapped(d<'range_mapper'>(x)).index===d<'range_mapper'>(x).bands.length-1)],
  latch:[num('current','Current',x=>d<'latch'>(x).current,(x,v)=>({...d<'latch'>(x),current:v})),num('held','Held',x=>d<'latch'>(x).held),num('delta','Delta',x=>d<'latch'>(x).current-d<'latch'>(x).held),txt('heldAt','Held at',x=>d<'latch'>(x).heldAt?new Date(d<'latch'>(x).heldAt!).toLocaleString():'Never')],
  random_picker:[txt('pick','Pick',x=>d<'random_picker'>(x).pick),bool('rolledToday','Rolled today',x=>d<'random_picker'>(x).lastRolledAt?localDayKey(d<'random_picker'>(x).lastRolledAt!)===localDayKey():false,undefined,true)],
  sequencer:[txt('current','Current step',x=>d<'sequencer'>(x).steps[d<'sequencer'>(x).activeIndex]?.text??''),num('index','Index',x=>d<'sequencer'>(x).activeIndex),num('progress','Progress',x=>{const q=d<'sequencer'>(x);return q.steps.length?(q.activeIndex/Math.max(1,q.steps.length-1))*100:0}),bool('done','Done',x=>{const q=d<'sequencer'>(x);return !q.loop&&q.activeIndex>=q.steps.length-1})],
  template:[txt('a','Slot A',x=>d<'template'>(x).slotA,(x,v)=>({...d<'template'>(x),slotA:v})),txt('b','Slot B',x=>d<'template'>(x).slotB,(x,v)=>({...d<'template'>(x),slotB:v})),txt('c','Slot C',x=>d<'template'>(x).slotC,(x,v)=>({...d<'template'>(x),slotC:v})),txt('d','Slot D',x=>d<'template'>(x).slotD,(x,v)=>({...d<'template'>(x),slotD:v})),txt('text','Composed text',x=>composed(d<'template'>(x)))],
  recorder:[num('input','Input',x=>d<'recorder'>(x).input,(x,v)=>{const data=d<'recorder'>(x);return{...data,input:v,...(data.mode==='on_change'?{samples:appendSample(data.samples,v),lastRecordedAt:Date.now()}:{})}}),num('last','Last',x=>d<'recorder'>(x).samples.at(-1)?.v??0),num('count','Sample count',x=>d<'recorder'>(x).samples.length),num('average','Average',x=>seriesAverage(d<'recorder'>(x).samples)),num('delta7d','7-day change',x=>seriesDelta7d(d<'recorder'>(x).samples),undefined,true),{key:'series',label:'Series',valueType:'series',get:x=>d<'recorder'>(x).samples}],
  notifier:[bool('armed','Armed',x=>d<'notifier'>(x).armed,(x,v)=>{const data=d<'notifier'>(x);const rising=!data.armed&&v;return{...data,armed:v,...(rising?{pendingFireAt:Date.now()}: {})}}),txt('message','Message',x=>d<'notifier'>(x).message,(x,v)=>({...d<'notifier'>(x),message:v})),txt('lastFiredAt','Last fired',x=>d<'notifier'>(x).lastFiredAt?new Date(d<'notifier'>(x).lastFiredAt!).toLocaleString():'Never'),num('fireCount','Fire count',x=>d<'notifier'>(x).fireCount)],

  subscriptions:[num('monthlyTotal','Monthly total',x=>d<'subscriptions'>(x).rows.filter(r=>r.active).reduce((sum,row)=>sum+subscriptionMonthly(row),0),undefined,false,'currency'),num('annualTotal','Annual total',x=>d<'subscriptions'>(x).rows.filter(r=>r.active).reduce((sum,row)=>sum+subscriptionMonthly(row)*12,0),undefined,false,'currency'),num('nextRenewalDays','Next renewal',x=>minOrZero(d<'subscriptions'>(x).rows.filter(r=>r.active).map(r=>daysUntilDate(r.renewsOn))),undefined,true,'count'),num('dueSoonCount','Due soon',x=>d<'subscriptions'>(x).rows.filter(r=>r.active&&daysUntilDate(r.renewsOn)>=0&&daysUntilDate(r.renewsOn)<=7).length,undefined,true,'count')],
  debt_payoff:[num('extraPayment','Extra payment',x=>d<'debt_payoff'>(x).extraPayment,(x,v)=>({...d<'debt_payoff'>(x),extraPayment:v}),false,'currency'),num('totalBalance','Total balance',x=>d<'debt_payoff'>(x).debts.reduce((sum,row)=>sum+row.balance,0),undefined,false,'currency'),num('monthsToFree','Months to free',x=>projectDebtPayoff(d<'debt_payoff'>(x)).months,undefined,false,'count'),num('totalInterest','Total interest',x=>projectDebtPayoff(d<'debt_payoff'>(x)).interest,undefined,false,'currency'),txt('debtFreeDate','Debt-free date',x=>projectDebtPayoff(d<'debt_payoff'>(x)).debtFreeDate)],
  expense_split:[num('total','Total',x=>d<'expense_split'>(x).expenses.reduce((sum,row)=>sum+row.amount,0),undefined,false,'currency'),num('youAreOwed','You are owed',x=>settleExpenses(d<'expense_split'>(x)).filter(t=>t.to===d<'expense_split'>(x).you).reduce((sum,t)=>sum+t.amount,0),undefined,false,'currency'),num('youOwe','You owe',x=>settleExpenses(d<'expense_split'>(x)).filter(t=>t.from===d<'expense_split'>(x).you).reduce((sum,t)=>sum+t.amount,0),undefined,false,'currency'),txt('settlement','Settlement',x=>settleExpenses(d<'expense_split'>(x)).map(t=>`${t.from} → ${t.to} $${t.amount.toFixed(2)}`).join('; ')||'Settled')],
  invoices:[num('outstanding','Outstanding',x=>d<'invoices'>(x).rows.filter(r=>r.status!=='paid').reduce((sum,r)=>sum+r.amount,0),undefined,false,'currency'),num('overdueCount','Overdue',x=>d<'invoices'>(x).rows.filter(r=>r.status==='sent'&&daysUntilDate(r.due)<0).length,undefined,true,'count'),num('paidThisMonth','Paid this month',x=>d<'invoices'>(x).rows.filter(r=>r.status==='paid'&&r.due.slice(0,7)===localDayKey().slice(0,7)).reduce((sum,r)=>sum+r.amount,0),undefined,false,'currency')],
  meal_planner:[num('plannedCount','Planned meals',x=>d<'meal_planner'>(x).week.filter(slot=>slot.dish.trim()).length),num('gapsCount','Meal gaps',x=>21-d<'meal_planner'>(x).week.filter(slot=>slot.dish.trim()).length),txt('todaysMeals','Today’s meals',x=>d<'meal_planner'>(x).week.filter(slot=>slot.day===new Date().getDay()).map(slot=>`${slot.meal}: ${slot.dish}`).join('; '),undefined),txt('shoppingList','Shopping list',x=>d<'meal_planner'>(x).shoppingList,(x,v)=>({...d<'meal_planner'>(x),shoppingList:v}))],
  recipe:[num('servings','Servings',x=>d<'recipe'>(x).servings,(x,v)=>({...d<'recipe'>(x),servings:Math.max(1,v)})),txt('ingredientList','Ingredients',x=>{const q=d<'recipe'>(x);const scale=q.servings/Math.max(1,q.baseServings);return q.ingredients.map(i=>`${Math.round(i.qty*scale*100)/100}${i.unit} ${i.item}`).join(', ')}),num('cookMinutes','Cook minutes',x=>d<'recipe'>(x).cookMinutes)],
  home_maintenance:[num('dueCount','Due',x=>d<'home_maintenance'>(x).rows.filter(r=>monthsSince(r.lastDone)>=r.everyMonths).length,undefined,true),num('overdueCount','Overdue',x=>d<'home_maintenance'>(x).rows.filter(r=>monthsSince(r.lastDone)>r.everyMonths).length,undefined,true),txt('nextDue','Next due',x=>[...d<'home_maintenance'>(x).rows].sort((a,b)=>(a.everyMonths-monthsSince(a.lastDone))-(b.everyMonths-monthsSince(b.lastDone)))[0]?.task??'Nothing due')],
  chore_rotation:[txt('assignments','Assignments',x=>assignments(d<'chore_rotation'>(x))),txt('myChores','My chores',x=>assignments(d<'chore_rotation'>(x)).split('; ')[0]??'')],
  renewals_vault:[num('soonestExpiryDays','Soonest expiry',x=>minOrZero(d<'renewals_vault'>(x).rows.map(r=>daysUntilDate(r.expires))),undefined,true),num('dueSoonCount','Due soon',x=>d<'renewals_vault'>(x).rows.filter(r=>daysUntilDate(r.expires)<=r.renewLeadDays).length,undefined,true),txt('nextUp','Next up',x=>[...d<'renewals_vault'>(x).rows].sort((a,b)=>daysUntilDate(a.expires)-daysUntilDate(b.expires))[0]?.item??'')],
  medications:[num('takenToday','Taken today',x=>d<'medications'>(x).rows.reduce((sum,r)=>sum+r.takenToday.filter(Boolean).length,0)),num('remainingToday','Remaining today',x=>d<'medications'>(x).rows.reduce((sum,r)=>sum+Math.max(0,r.timesPerDay-r.takenToday.filter(Boolean).length),0)),bool('allTaken','All taken',x=>d<'medications'>(x).rows.every(r=>r.takenToday.length>=r.timesPerDay&&r.takenToday.slice(0,r.timesPerDay).every(Boolean))),num('refillDays','Refill days',x=>minOrZero(d<'medications'>(x).rows.map(r=>Math.floor(r.pillsLeft/Math.max(1,r.dailyUse)))))],
  workout_plan:[num('sessionVolume','Session volume',x=>{const q=d<'workout_plan'>(x);return(q.days[q.activeDay]?.exercises??[]).filter(e=>e.done).reduce((sum,e)=>sum+e.sets*e.reps*e.weight,0)}),bool('completedToday','Completed today',x=>{const q=d<'workout_plan'>(x);const rows=q.days[q.activeDay]?.exercises??[];return rows.length>0&&rows.every(e=>e.done)}),txt('lastSession','Last session',x=>d<'workout_plan'>(x).lastSession)],
  job_applications:[num('activeCount','Active',x=>d<'job_applications'>(x).rows.filter(r=>!['wishlist','closed'].includes(r.stage)).length),num('needsFollowUpCount','Needs followup',x=>d<'job_applications'>(x).rows.filter(r=>r.stage!=='closed'&&daysUntilDate(r.followUpBy)<=0).length,undefined,true),num('interviewCount','Interviews',x=>d<'job_applications'>(x).rows.filter(r=>r.stage==='interview').length),num('offerCount','Offers',x=>d<'job_applications'>(x).rows.filter(r=>r.stage==='offer').length)],
  okr:[...Array.from({length:4},(_,i)=>num(`kr${i+1}Current`,`KR ${i+1}`,x=>d<'okr'>(x).keyResults[i]?.current??0,(x,v)=>{const q=d<'okr'>(x);const keyResults=[...q.keyResults];if(keyResults[i])keyResults[i]={...keyResults[i]!,current:v};return{...q,keyResults}})),num('progress','Progress',x=>okrProgress(d<'okr'>(x)))],
  decision_journal:[num('dueForReview','Due for review',x=>d<'decision_journal'>(x).entries.filter(e=>!e.verdict&&daysUntilDate(e.reviewOn)<=0).length,undefined,true),num('entryCount','Entries',x=>d<'decision_journal'>(x).entries.length),num('hitRate','Hit rate',x=>{const scored=d<'decision_journal'>(x).entries.filter(e=>e.verdict);return scored.length?scored.filter(e=>e.verdict==='hit').length/scored.length*100:0})],
  weekly_review:[bool('completedThisWeek','Completed',x=>d<'weekly_review'>(x).completedThisWeek,(x,v)=>({...d<'weekly_review'>(x),completedThisWeek:v})),num('streak','Streak',x=>d<'weekly_review'>(x).streak)],
  snippet_library:[num('count','Count',x=>d<'snippet_library'>(x).entries.length),txt('mostUsed','Most used',x=>[...d<'snippet_library'>(x).entries].sort((a,b)=>b.useCount-a.useCount)[0]?.body??'')],
  keep_in_touch:[num('overdueCount','Overdue',x=>d<'keep_in_touch'>(x).rows.filter(r=>Date.now()-new Date(`${r.lastContact}T00:00:00`).getTime()>r.cadenceDays*DAY_MS).length,undefined,true),txt('nextUp','Next up',x=>[...d<'keep_in_touch'>(x).rows].sort((a,b)=>(new Date(a.lastContact).getTime()+a.cadenceDays*DAY_MS)-(new Date(b.lastContact).getTime()+b.cadenceDays*DAY_MS))[0]?.name??'')],
  gifts_occasions:[num('nextOccasionDays','Next occasion',x=>minOrZero(d<'gifts_occasions'>(x).rows.map(r=>daysUntilDate(r.date))),undefined,true,'count'),txt('nextOccasion','Next occasion name',x=>[...d<'gifts_occasions'>(x).rows].sort((a,b)=>daysUntilDate(a.date)-daysUntilDate(b.date))[0]?.person??''),num('unboughtSoonCount','Unbought soon',x=>d<'gifts_occasions'>(x).rows.filter(r=>!r.bought&&daysUntilDate(r.date)<=14).length,undefined,true,'count'),num('plannedSpend','Planned spend',x=>d<'gifts_occasions'>(x).rows.filter(r=>!r.bought).reduce((sum,r)=>sum+r.budget,0),undefined,false,'currency')],
  trip_itinerary:[num('daysUntil','Days until',x=>daysUntilDate(d<'trip_itinerary'>(x).startDate),undefined,true),num('unbookedCount','Unbooked',x=>d<'trip_itinerary'>(x).days.flatMap(day=>day.legs).filter(leg=>!leg.booked).length),txt('todaysPlan','Today’s plan',x=>d<'trip_itinerary'>(x).days.find(day=>day.date===localDayKey())?.legs.map(leg=>`${leg.time} ${leg.what} @ ${leg.where}`).join('; ')??'',undefined)],
  guest_list:[num('confirmedCount','Confirmed',x=>d<'guest_list'>(x).rows.filter(r=>r.status==='yes').reduce((sum,r)=>sum+1+r.plusOnes,0)),num('pendingCount','Pending',x=>d<'guest_list'>(x).rows.filter(r=>['invited','maybe'].includes(r.status)).length),txt('dietaryNotes','Dietary notes',x=>d<'guest_list'>(x).rows.filter(r=>r.status==='yes'&&r.dietary).map(r=>`${r.name}: ${r.dietary}`).join('; '))],
}

function roll(data:D<'random_picker'>):D<'random_picker'>{const blocked=new Set(data.history.slice(-Math.max(0,data.noRepeatWindow)));const choices=data.options.filter(o=>!blocked.has(o.text));const pool=choices.length?choices:data.options;const total=pool.reduce((sum,o)=>sum+Math.max(0,o.weight),0)||pool.length;let cursor=Math.random()*total;const selected=pool.find(o=>(cursor-=Math.max(0,o.weight)||1)<=0)??pool[0];if(!selected)return data;return{...data,pick:selected.text,lastRolledAt:Date.now(),history:[...data.history,selected.text].slice(-20)}}

export const EXPANSION_COMMANDS: Partial<Record<ModuleType, CommandDescriptor[]>> = {
  latch:[{key:'capture',label:'Capture snapshot',run:x=>{const q=d<'latch'>(x);return{...q,held:q.current,heldAt:Date.now()}}}],
  random_picker:[{key:'roll',label:'Roll a choice',run:x=>roll(d<'random_picker'>(x))}],
  sequencer:[{key:'advance',label:'Advance step',run:x=>{const q=d<'sequencer'>(x);const next=q.activeIndex+1;return{...q,activeIndex:next>=q.steps.length?(q.loop?0:Math.max(0,q.steps.length-1)):next}}},{key:'reset',label:'Restart sequence',run:x=>({...d<'sequencer'>(x),activeIndex:0})}],
  recorder:[{key:'record',label:'Record sample',run:x=>{const q=d<'recorder'>(x);return{...q,samples:appendSample(q.samples,q.input),lastRecordedAt:Date.now()}}},{key:'reset',label:'Clear history',run:x=>({...d<'recorder'>(x),samples:[],lastRecordedAt:null})}],
  notifier:[{key:'notify',label:'Send notification',run:x=>({...d<'notifier'>(x),pendingFireAt:Date.now()})}],
  chore_rotation:[{key:'rotate',label:'Rotate chores',run:x=>{const q=d<'chore_rotation'>(x);return{...q,offset:(q.offset+1)%Math.max(1,q.people.length)}}}],
  medications:[{key:'uncheck_all',label:'Reset today’s doses',run:x=>{const q=d<'medications'>(x);return{...q,rows:q.rows.map(row=>({...row,takenToday:Array(row.timesPerDay).fill(false)}))}}}],
  weekly_review:[{key:'new_period',label:'Start new review period',run:x=>{const q=d<'weekly_review'>(x);return{...q,prompts:q.prompts.map(p=>({...p,answer:''})),weekOf:localDayKey(),historyCount:q.historyCount+(q.completedThisWeek?1:0),streak:q.completedThisWeek?q.streak+1:0,completedThisWeek:false}}}],
}
