import {
  BarChart3,
  Binary,
  Calculator,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Percent,
  ReceiptText,
  Sigma,
  Variable,
  ChartNoAxesColumn,
  CircleDollarSign,
  Coffee,
  Contact,
  Flame,
  Gauge,
  Hash,
  Hourglass,
  Link2,
  ListChecks,
  ListOrdered,
  Palette,
  Radio,
  Rows3,
  Smile,
  SlidersHorizontal,
  Star,
  Table2,
  Timer,
  TrafficCone,
  Vote,
  ChartLine,
  ChartPie,
  Dumbbell,
  Globe2,
  ListRestart,
  Repeat2,
  Swords,
  TimerReset,
  WalletCards,
  ShieldCheck,
  ArrowRightLeft,
  PiggyBank,
  Users,
  BriefcaseBusiness,
  MousePointerClick,
  Target,
  ChevronsUpDown,
  ListPlus,
  CalendarSync,
  UserRound,
  Briefcase,
  Siren,
  Store,
  HeartHandshake,
  House,
  Stethoscope,
} from 'lucide-react'
import type { WidgetDefinition } from '../contracts/registry'
import { localDayKey } from '../../utils/localDate'
import { C, uid } from './definitionHelpers'

/** Data and tracking widgets (calendar … color_palette). Extracted verbatim from registry.ts; key order preserved. */
export const DATA_TRACKING_WIDGET_DEFINITIONS = {
  calendar: {
    type: 'calendar',
    label: 'Calendar',
    description: 'A month view — click days to mark them',
    icon: CalendarDays,
    category: 'planning',
    accent: '#7dd3fc',
    defaultSize: { width: 280, height: C * 6 },
    defaultData: () => {
      const now = new Date()
      return { year: now.getFullYear(), month: now.getMonth(), markedDates: [], skin: 'month' }
    },
    rendererOwnedSkinDetails: ['shift_rota', 'birthday_and_anniversary'],
  },
  countdown: {
    type: 'countdown',
    label: 'Countdown',
    description: 'Days remaining until a target date',
    icon: CalendarClock,
    category: 'planning',
    accent: '#fdba74',
    defaultSize: { width: 280, height: C * 3 },
    defaultData: () => {
      const target = new Date()
      target.setDate(target.getDate() + 14)
      return { label: 'Deadline', targetDate: localDayKey(target.getTime()) }
    },
  },
  progress: {
    type: 'progress',
    label: 'Progress',
    description: 'A labeled 0–100% progress bar',
    icon: Gauge,
    category: 'planning',
    accent: '#a3e635',
    defaultSize: { width: 280, height: C * 3 },
    defaultData: () => ({ label: 'Progress', percent: 40 }),
  },
  poll: {
    type: 'poll',
    label: 'Poll',
    description: 'Gather a preference as bars, a share dial, an approval or ranked ballot, duels, a live room, or an anonymous vote',
    icon: Vote,
    category: 'planning',
    accent: '#f0abfc',
    restingFace: true,
    // Ranked choice pairs a draft ballot with its runoff, and Pairwise stacks a
    // duel above its win matrix; both need more room than a plain bar list.
    defaultSize: { width: 340, height: C * 6 },
    defaultData: () => ({
      skin: 'bars',
      question: 'Which direction?',
      options: [
        { id: uid(), label: 'Option A', votes: 0 },
        { id: uid(), label: 'Option B', votes: 0 },
      ],
    }),
    skinField: 'skin',
    rendererOwnedSkinDetails: ['ranked_choice', 'pairwise', 'live_room', 'anonymous'],
    // Metadata mirrors the generated catalogue exactly; only the icon is ours.
    skins: [
      {
        value: 'bars',
        label: 'Bars',
        description: 'The current comparison of option vote totals.',
        implementation: 'renderer-ready',
        presentation: 'matrix',
        icon: ChartNoAxesColumn,
        accent: '#72e472',
      },
      {
        value: 'donut',
        label: 'Donut',
        description: 'A share-of-votes view for compact dashboards.',
        implementation: 'renderer-ready',
        presentation: 'board',
        icon: ChartPie,
        accent: '#72e4c9',
      },
      {
        value: 'approval',
        label: 'Approval',
        description: 'Allows each voter to approve any number of options.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: ListChecks,
        accent: '#e4c772',
      },
      {
        value: 'ranked_choice',
        label: 'Ranked Choice',
        description: 'Collects ordered preferences and calculates rounds.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: ListOrdered,
        accent: '#729ce4',
      },
      {
        value: 'pairwise',
        label: 'Pairwise',
        description: 'Runs option-versus-option comparisons.',
        implementation: 'schema-extension',
        presentation: 'matrix',
        icon: Swords,
        accent: '#e4b872',
      },
      {
        value: 'live_room',
        label: 'Live Room',
        description: 'Shows participant count, voting state, and result reveal control.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: Radio,
        accent: '#72e4d5',
      },
      {
        value: 'anonymous',
        label: 'Anonymous',
        description: 'Stores aggregate votes without retaining voter identity.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: ShieldCheck,
        accent: '#e472cf',
      },
    ],
  },
  rating: {
    type: 'rating',
    label: 'Rating',
    description: 'Stars, sentiment, score, rubric, and confidence in one rating',
    icon: Star,
    category: 'data',
    accent: '#fbbf24',
    // NPS needs eleven honest targets across; the auto-height charter lets the
    // richer Rubric grow without leaving the quieter skins in an empty card.
    defaultSize: { width: C * 8, height: C * 4 },
    sizing: { minWidth: C * 8, minHeight: C * 4, autoHeight: true, fixed: true },
    defaultData: () => ({ label: 'Rate it', value: 0, skin: 'stars' }),
    rendererOwnedSkinDetails: ['rubric', 'confidence'],
    skinField: 'skin',
    skins: [
      {
        value: 'stars',
        label: 'Stars',
        description: 'The familiar five-star control.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Star,
        accent: '#e4cd72',
      },
      {
        value: 'slider',
        label: 'Slider',
        description: 'A continuous scale with a precise reading.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: SlidersHorizontal,
        accent: '#729ce4',
      },
      {
        value: 'emoji',
        label: 'Emoji',
        description: 'A quick emotional or satisfaction scale.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Smile,
        accent: '#e472a5',
      },
      {
        value: 'traffic_light',
        label: 'Traffic Light',
        description: 'A clear red, amber, or green assessment.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: TrafficCone,
        accent: '#e4c072',
      },
      {
        value: 'nps',
        label: 'NPS',
        description: 'A zero-to-ten recommendation scale.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Gauge,
        accent: '#729de4',
      },
      {
        value: 'rubric',
        label: 'Rubric',
        description: 'Combine several named criteria into one published rating.',
        implementation: 'schema-extension',
        presentation: 'matrix',
        icon: Rows3,
        accent: '#e4cd72',
      },
      {
        value: 'confidence',
        label: 'Confidence',
        description: 'Pair the rating with certainty and a short evidence note.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: Percent,
        accent: '#e4cd72',
      },
    ],
  },
  calculator: {
    type: 'calculator',
    label: 'Calculator',
    description: 'Pocket, scientific, tape, finance, and programmer calculators in one card',
    icon: Calculator,
    category: 'data',
    accent: '#a7f3d0',
    // Scientific carries a function strip above the number block and
    // Programmer four base readouts above its keypad. Every key keeps the
    // catalog's 28px target floor, so the card has to be tall enough to hold
    // them all rather than the keys shrinking to fit the old 240×280 box.
    defaultSize: { width: 280, height: C * 9 },
    sizing: { minWidth: C * 6, minHeight: C * 7 },
    defaultData: () => ({ expression: '', result: '' }),
    rendererOwnedSkinDetails: ['date_math', 'named_variables'],
    // Declared by hand so each skin wears its own icon: every one of these is
    // the `standard` presentation, so the catalogue merge would have given all
    // seven the same sparkle. `skinField` must stay 'skin' — `CalculatorData`
    // has no `mode`, and `result` is the circuit's canonical output.
    skinField: 'skin',
    skins: [
      {
        value: 'basic',
        label: 'Basic',
        description: 'The current four-operation keypad.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Calculator,
        accent: '#a7e472',
      },
      {
        value: 'scientific',
        label: 'Scientific',
        description: 'Functions, constants, parentheses, and memory.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Sigma,
        accent: '#e48c72',
      },
      {
        value: 'tape',
        label: 'Tape',
        description: 'A visible running calculation history like an adding machine.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: ReceiptText,
        accent: '#72e4ab',
      },
      {
        value: 'finance',
        label: 'Finance',
        description: 'Percent change, margin, markup, tax, and compound-growth shortcuts.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Percent,
        accent: '#72e4a1',
      },
      {
        value: 'programmer',
        label: 'Programmer',
        description: 'Binary, octal, hexadecimal, and bitwise operations.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Binary,
        accent: '#bce472',
      },
      {
        value: 'date_math',
        label: 'Date Math',
        description: 'Calculates differences, offsets, and working days between dates.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: CalendarRange,
        accent: '#8772e4',
      },
      {
        value: 'named_variables',
        label: 'Named Variables',
        description: 'Lets circuit inputs populate named values inside an expression.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: Variable,
        accent: '#a572e4',
      },
    ],
  },
  bar_chart: {
    type: 'bar_chart',
    label: 'Chart',
    description: 'Bar, line, donut, and pie views over one shared series',
    icon: BarChart3,
    category: 'data',
    accent: '#7dd3fc',
    restingFace: true,
    defaultSize: { width: 400, height: C * 7 },
    defaultData: () => ({
      title: 'Chart',
      mode: 'bar',
      unit: '',
      bars: [
        { id: uid(), label: 'A', value: 3, color: '#38bdf8' },
        { id: uid(), label: 'B', value: 5, color: '#a3e635' },
      ],
    }),
    skins: [
      { value: 'bar', label: 'Bar', icon: BarChart3, accent: '#7dd3fc' },
      { value: 'line', label: 'Line', icon: ChartLine, accent: '#4ade80' },
      { value: 'donut', label: 'Donut', icon: ChartPie, accent: '#fbbf24' },
      { value: 'pie', label: 'Pie', icon: ChartPie, accent: '#fb923c' },
    ],
    rendererOwnedSkinDetails: ['heatmap', 'scatter', 'stacked'],
  },
  table: {
    type: 'table',
    label: 'Table',
    description: 'Editable grid with a header row',
    icon: Table2,
    category: 'data',
    accent: '#94a3b8',
    restingFace: true,
    defaultSize: { width: 440, height: C * 5 },
    sizing: { minWidth: 340, minHeight: C * 5, maxWidth: 840 },
    defaultData: () => ({
      rows: [
        ['Item', 'Owner', 'Status'],
        ['', '', ''],
        ['', '', ''],
      ],
    }),
    rendererOwnedSkinDetails: ['database', 'kanban', 'gallery', 'form_view', 'pivot'],
  },
  budget: {
    type: 'budget',
    label: 'Budget',
    description: 'Eight elegant planning views over one shared set of budget lines',
    icon: CircleDollarSign,
    category: 'data',
    accent: '#fde047',
    defaultSize: { width: 400, height: C * 8 },
    sizing: { minWidth: 320, minHeight: C * 7, maxWidth: 720 },
    defaultData: () => ({
      currency: '$',
      skin: 'category_plan',
      items: [
        { id: uid(), label: 'Hosting', amount: 12 },
        { id: uid(), label: 'Domain', amount: 15 },
      ],
    }),
    skinField: 'skin',
    skins: [
      { value: 'category_plan', label: 'Category Plan', description: 'The current planned-versus-actual category view.', implementation: 'renderer-ready', presentation: 'standard', icon: ReceiptText, accent: '#9272e4' },
      { value: 'envelope', label: 'Envelope', description: 'Shows remaining spendable money as category envelopes.', implementation: 'renderer-ready', presentation: 'standard', icon: WalletCards, accent: '#72e4a1' },
      { value: 'zero_based', label: 'Zero-based', description: 'Requires every unit of income to receive an assignment.', implementation: 'renderer-ready', presentation: 'standard', icon: CircleDollarSign, accent: '#72e4a1' },
      { value: '50_30_20', label: '50 / 30 / 20', description: 'Groups spending into needs, wants, and savings targets.', implementation: 'renderer-ready', presentation: 'standard', icon: ShieldCheck, accent: '#72e4a1' },
      { value: 'cashflow', label: 'Cashflow', description: 'Adds dated income and expense timing across a month.', implementation: 'schema-extension', presentation: 'standard', icon: ArrowRightLeft, accent: '#72e4a1' },
      { value: 'sinking_funds', label: 'Sinking Funds', description: 'Tracks several future expenses and contribution schedules.', implementation: 'schema-extension', presentation: 'timeline', icon: PiggyBank, accent: '#e4a772' },
      { value: 'shared_budget', label: 'Shared Budget', description: 'Adds contributor, payer, and household ownership.', implementation: 'schema-extension', presentation: 'standard', icon: Users, accent: '#72e4a1' },
      { value: 'project_budget', label: 'Project Budget', description: 'Separates committed, invoiced, paid, and forecast cost.', implementation: 'schema-extension', presentation: 'standard', icon: BriefcaseBusiness, accent: '#72e4a1' },
    ],
    rendererOwnedSkinDetails: ['cashflow', 'sinking_funds', 'shared_budget', 'project_budget'],
  },
  metrics: {
    type: 'metrics',
    label: 'Metrics',
    description: 'KPI tiles with value, unit, and trend',
    icon: ChartNoAxesColumn,
    category: 'data',
    accent: '#67e8f9',
    restingFace: true,
    defaultSize: { width: 400, height: C * 7 },
    sizing: { minWidth: 320, minHeight: C * 6, maxWidth: 720 },
    defaultData: () => ({
      tiles: [
        { id: uid(), label: 'Users', value: '128', unit: '', trend: 'up' },
        { id: uid(), label: 'Revenue', value: '3.2', unit: 'k', trend: 'flat' },
      ],
    }),
    rendererOwnedSkinDetails: ['delta', 'target', 'executive_strip'],
  },
  timer: {
    type: 'timer',
    label: 'Timer',
    description: 'A countdown timer with start, pause, and reset',
    icon: Timer,
    category: 'tracking',
    accent: '#86efac',
    defaultSize: { width: 240, height: C * 4 },
    defaultData: () => ({ label: 'Timer', durationSeconds: 300, remainingSeconds: 300, endAt: null }),
  },
  timekeeper: {
    type: 'timekeeper',
    label: 'Time',
    description: 'Timers, focus cycles, deadlines, clocks, and lap tracking in one card',
    icon: Timer,
    category: 'tracking',
    accent: '#86efac',
    // A dial is square: the clock ring rides the card's own outline, so the
    // card stays between 4×4 and 7×7 cells and never stretches into a bar
    // that would make the ring read as a border instead of a bezel.
    restingFace: true,
    defaultSize: { width: C * 6, height: C * 6 },
    sizing: { minWidth: C * 5, minHeight: C * 5, maxWidth: C * 8, maxHeight: C * 8 },
    defaultData: () => ({
      mode: 'countdown',
      countdown: { label: 'Timer', durationSeconds: 300, remainingSeconds: 300, endAt: null },
      pomodoro: { label: 'Focus', workMinutes: 25, breakMinutes: 5, phase: 'work', endAt: null, remainingSeconds: 25 * 60, completed: 0 },
      stopwatch: { elapsedMs: 0, startedAt: null, laps: [] },
      deadline: {
        label: 'Launch day',
        targetDate: localDayKey(Date.now() + 14 * 86_400_000),
      },
      worldClock: { zones: ['America/New_York', 'Europe/London', 'Asia/Tokyo'] },
    }),
    skins: [
      { value: 'countdown', label: 'Timer', icon: Timer, accent: '#86efac' },
      { value: 'pomodoro', label: 'Pomodoro', icon: Coffee, accent: '#fb7185' },
      { value: 'stopwatch', label: 'Stopwatch', icon: Hourglass, accent: '#7dd3fc' },
      { value: 'deadline', label: 'Deadline', icon: CalendarClock, accent: '#fb923c' },
      { value: 'world_clock', label: 'World Clock', icon: Globe2, accent: '#67e8f9' },
      { value: 'hourglass', label: 'Hourglass', description: 'A calm visual countdown with minimal controls.', implementation: 'renderer-ready', presentation: 'time', icon: Hourglass, accent: '#89e472' },
      { value: 'intervals', label: 'Intervals', description: 'Alternates configurable work and recovery segments.', implementation: 'schema-extension', presentation: 'terminal', icon: Repeat2, accent: '#83e472' },
      { value: 'tabata', label: 'Tabata', description: 'Runs repeated high-intensity and rest rounds.', implementation: 'schema-extension', presentation: 'standard', icon: Dumbbell, accent: '#72e0e4' },
      { value: 'chess_clock', label: 'Chess Clock', description: 'Maintains two mutually exclusive running clocks.', implementation: 'schema-extension', presentation: 'time', icon: Swords, accent: '#e4a772' },
      { value: 'lap_timer', label: 'Lap Timer', description: 'Records named laps and split differences.', implementation: 'schema-extension', presentation: 'time', icon: TimerReset, accent: '#e4a772' },
      { value: 'multi_stage_timer', label: 'Multi-stage Timer', description: 'Runs several named timed phases in sequence.', implementation: 'schema-extension', presentation: 'time', icon: ListRestart, accent: '#e4a772' },
    ],
    rendererOwnedSkinDetails: ['intervals', 'tabata', 'chess_clock', 'multi_stage_timer'],
  },
  mood_tracker: {
    type: 'mood_tracker',
    label: 'Mood Tracker',
    description: 'A weekly mood log — tap a day to cycle through',
    icon: Smile,
    category: 'tracking',
    accent: '#fde047',
    defaultSize: { width: 300, height: C * 4 },
    sizing: { minWidth: 260, minHeight: C * 4, maxWidth: 560, maxHeight: C * 4, autoHeight: true },
    defaultData: () => ({ days: [null, null, null, null, null, null, null] }),
  },
  counter: {
    type: 'counter',
    label: 'Counter',
    description: 'A tally counter — one number, step-adjustable',
    icon: Hash,
    category: 'tracking',
    accent: '#93c5fd',
    // Multi-counter stacks named rows and Resetting Period carries a history
    // strip, so the card starts taller than a single number would need.
    defaultSize: { width: 280, height: C * 5 },
    defaultData: () => ({ label: 'Tally', count: 0, step: 1, skin: 'tally' }),
    skinField: 'skin',
    rendererOwnedSkinDetails: ['multi_counter', 'timed_rate', 'resetting_period'],
    // Metadata mirrors the generated catalogue exactly; only the icon is ours.
    skins: [
      { value: 'tally', label: 'Tally', description: 'The current increment/decrement counter.', implementation: 'renderer-ready', presentation: 'standard', icon: Hash, accent: '#bce472' },
      { value: 'clicker', label: 'Clicker', description: 'One enormous tap target for events and attendance.', implementation: 'renderer-ready', presentation: 'standard', icon: MousePointerClick, accent: '#72e490' },
      { value: 'goal_counter', label: 'Goal Counter', description: 'Shows current, target, remaining, and percent.', implementation: 'renderer-ready', presentation: 'standard', icon: Target, accent: '#e4cd72' },
      { value: 'up_down', label: 'Up / Down', description: 'Prominent plus and minus controls for changing quantities.', implementation: 'renderer-ready', presentation: 'standard', icon: ChevronsUpDown, accent: '#89e472' },
      { value: 'multi_counter', label: 'Multi-counter', description: 'Maintains several named tallies in one card.', implementation: 'schema-extension', presentation: 'cards', icon: ListPlus, accent: '#b2e472' },
      { value: 'timed_rate', label: 'Timed Rate', description: 'Calculates events per minute or hour.', implementation: 'schema-extension', presentation: 'standard', icon: Gauge, accent: '#e4a772' },
      { value: 'resetting_period', label: 'Resetting Period', description: 'Keeps daily, weekly, or monthly totals and history.', implementation: 'schema-extension', presentation: 'time', icon: CalendarSync, accent: '#e47272' },
    ],
  },
  links: {
    type: 'links',
    label: 'Link List',
    description: 'Labelled external links, click to open',
    icon: Link2,
    category: 'tracking',
    accent: '#93c5fd',
    defaultSize: { width: 300, height: C * 4 },
    defaultData: () => ({
      items: [{ id: uid(), label: 'grovepad', url: 'https://example.com' }],
    }),
  },
  habit: {
    type: 'habit',
    label: 'Habit Tracker',
    description: 'One habit, seven beautifully focused ways to keep it moving',
    icon: Flame,
    category: 'tracking',
    accent: '#fdba74',
    defaultSize: { width: 320, height: C * 5 },
    sizing: { minWidth: 280, minHeight: C * 4, maxWidth: 600, autoHeight: true },
    defaultData: () => ({
      label: 'Daily habit',
      days: [false, false, false, false, false, false, false],
      streak: 0,
      skin: 'week_grid',
    }),
    skinField: 'skin',
    skins: [
      { value: 'week_grid', label: 'Week Grid', description: 'The current seven-day completion row.', implementation: 'renderer-ready', presentation: 'grid', accent: '#72d1e4', icon: CalendarDays },
      { value: 'month_heatmap', label: 'Month Heatmap', description: 'A contribution-style month history.', implementation: 'renderer-ready', presentation: 'map', accent: '#a372e4', icon: CalendarRange },
      { value: 'chain', label: 'Chain', description: 'Emphasizes the uninterrupted sequence of qualifying days.', implementation: 'renderer-ready', presentation: 'steps', accent: '#72e49d', icon: Link2 },
      { value: 'scorecard', label: 'Scorecard', description: 'Shows compliance rate and recent misses.', implementation: 'renderer-ready', presentation: 'cards', accent: '#e4cd72', icon: Gauge },
      { value: 'routine_stack', label: 'Routine Stack', description: 'Orders several habits around an anchor behavior.', implementation: 'schema-extension', presentation: 'standard', accent: '#7281e4', icon: ListRestart },
      { value: 'minimum_target', label: 'Minimum / Target', description: 'Records a minimum acceptable and ideal daily amount.', implementation: 'schema-extension', presentation: 'time', accent: '#72d1e4', icon: TimerReset },
      { value: 'flexible_frequency', label: 'Flexible Frequency', description: 'Supports times-per-week goals instead of specific weekdays.', implementation: 'schema-extension', presentation: 'standard', accent: '#e4a772', icon: Repeat2 },
    ],
    rendererOwnedSkinDetails: ['routine_stack', 'minimum_target', 'flexible_frequency'],
  },
  contact: {
    type: 'contact',
    label: 'Contact Card',
    description: 'One person, seven ways to hold onto them',
    icon: Contact,
    category: 'tracking',
    accent: '#d8b4fe',
    // The Personal form is four labelled rows under an identity block, and
    // Household stacks a roster — the card starts tall enough for those
    // rather than opening on a scrollbar.
    defaultSize: { width: 320, height: C * 7 },
    sizing: { minWidth: 220, minHeight: C * 4, maxWidth: 560 },
    defaultData: () => ({ name: '', role: '', email: '', phone: '', skin: 'personal' }),
    skinField: 'skin',
    rendererOwnedSkinDetails: ['relationship', 'household', 'care_contact'],
    // Metadata mirrors the generated catalogue exactly; only the icon is ours.
    skins: [
      { value: 'personal', label: 'Personal', description: 'Informal identity, birthday, notes, and preferred channels.', implementation: 'renderer-ready', presentation: 'form', icon: UserRound, accent: '#729ce4' },
      { value: 'business', label: 'Business', description: 'Company, role, work details, and professional links.', implementation: 'renderer-ready', presentation: 'standard', icon: Briefcase, accent: '#9872e4' },
      { value: 'emergency', label: 'Emergency', description: 'Critical details and one-tap call emphasis.', implementation: 'renderer-ready', presentation: 'standard', icon: Siren, accent: '#b172e4' },
      { value: 'vendor', label: 'Vendor', description: 'Service category, terms, identifiers, and support routes.', implementation: 'renderer-ready', presentation: 'map', icon: Store, accent: '#9272e4' },
      { value: 'relationship', label: 'Relationship', description: 'Adds last contact, desired cadence, and personal context.', implementation: 'schema-extension', presentation: 'standard', icon: HeartHandshake, accent: '#e472b2' },
      { value: 'household', label: 'Household', description: 'Represents several related people under one address.', implementation: 'schema-extension', presentation: 'standard', icon: House, accent: '#e472c9' },
      { value: 'care_contact', label: 'Care Contact', description: 'Adds role, availability, care notes, and escalation order.', implementation: 'schema-extension', presentation: 'standard', icon: Stethoscope, accent: '#729ce4' },
    ],
  },
  color_palette: {
    type: 'color_palette',
    label: 'Color Palette',
    description: 'A swatch board — click a hue to copy its hex',
    icon: Palette,
    category: 'media',
    accent: '#f0abfc',
    defaultSize: { width: 260, height: C * 4 },
    defaultData: () => ({ colors: ['#a3e635', '#38bdf8', '#f472b6', '#fbbf24'] }),
  },
} satisfies Record<string, WidgetDefinition>
