import {
  BarChart3,
  Calculator,
  CalendarClock,
  CalendarDays,
  ChartNoAxesColumn,
  CircleDollarSign,
  Coffee,
  Contact,
  Flame,
  Gauge,
  Hash,
  Hourglass,
  Link2,
  Palette,
  Smile,
  Star,
  Table2,
  Timer,
  Vote,
  ChartLine,
  ChartPie,
} from 'lucide-react'
import type { WidgetDefinition } from '../contracts/registry'
import { localDayKey } from '../../utils/localDate'
import { C, uid } from './definitionHelpers'

/** Data and tracking widgets (calendar … color_palette). Extracted verbatim from registry.ts; key order preserved. */
export const DATA_TRACKING_WIDGET_DEFINITIONS = {
  calendar: {
    type: 'calendar',
    label: 'Calendar',
    description: 'A month view — click days to mark them',
    icon: CalendarDays,
    category: 'planning',
    accent: '#7dd3fc',
    defaultSize: { width: 280, height: C * 6 },
    defaultData: () => {
      const now = new Date()
      return { year: now.getFullYear(), month: now.getMonth(), markedDates: [] }
    },
  },
  countdown: {
    type: 'countdown',
    label: 'Countdown',
    description: 'Days remaining until a target date',
    icon: CalendarClock,
    category: 'planning',
    accent: '#fdba74',
    defaultSize: { width: 280, height: C * 3 },
    defaultData: () => {
      const target = new Date()
      target.setDate(target.getDate() + 14)
      return { label: 'Deadline', targetDate: localDayKey(target.getTime()) }
    },
  },
  progress: {
    type: 'progress',
    label: 'Progress',
    description: 'A labeled 0–100% progress bar',
    icon: Gauge,
    category: 'planning',
    accent: '#a3e635',
    defaultSize: { width: 280, height: C * 3 },
    defaultData: () => ({ label: 'Progress', percent: 40 }),
  },
  poll: {
    type: 'poll',
    label: 'Poll',
    description: 'Options with tap-to-vote counts',
    icon: Vote,
    category: 'planning',
    accent: '#f0abfc',
    defaultSize: { width: 300, height: C * 5 },
    defaultData: () => ({
      question: 'Which direction?',
      options: [
        { id: uid(), label: 'Option A', votes: 0 },
        { id: uid(), label: 'Option B', votes: 0 },
      ],
    }),
  },
  rating: {
    type: 'rating',
    label: 'Rating',
    description: 'A labeled 5-star rating',
    icon: Star,
    category: 'data',
    accent: '#fbbf24',
    defaultSize: { width: 260, height: C * 3 },
    defaultData: () => ({ label: 'Rate it', value: 0 }),
  },
  calculator: {
    type: 'calculator',
    label: 'Calculator',
    description: 'A pocket calculator — type or tap',
    icon: Calculator,
    category: 'data',
    accent: '#a7f3d0',
    defaultSize: { width: 240, height: C * 7 },
    defaultData: () => ({ expression: '', result: '' }),
  },
  bar_chart: {
    type: 'bar_chart',
    label: 'Chart',
    description: 'Bar, line, donut, and pie views over one shared series',
    icon: BarChart3,
    category: 'data',
    accent: '#7dd3fc',
    defaultSize: { width: 400, height: C * 7 },
    defaultData: () => ({
      title: 'Chart',
      mode: 'bar',
      unit: '',
      bars: [
        { id: uid(), label: 'A', value: 3, color: '#38bdf8' },
        { id: uid(), label: 'B', value: 5, color: '#a3e635' },
      ],
    }),
    modes: [
      { value: 'bar', label: 'Bar', icon: BarChart3 },
      { value: 'line', label: 'Line', icon: ChartLine },
      { value: 'donut', label: 'Donut', icon: ChartPie },
      { value: 'pie', label: 'Pie', icon: ChartPie },
    ],
  },
  table: {
    type: 'table',
    label: 'Table',
    description: 'Editable grid with a header row',
    icon: Table2,
    category: 'data',
    accent: '#94a3b8',
    defaultSize: { width: 360, height: C * 4 },
    sizing: { minWidth: 320, maxWidth: 720 },
    defaultData: () => ({
      rows: [
        ['Item', 'Owner', 'Status'],
        ['', '', ''],
        ['', '', ''],
      ],
    }),
  },
  budget: {
    type: 'budget',
    label: 'Budget',
    description: 'Line items with a running total',
    icon: CircleDollarSign,
    category: 'data',
    accent: '#fde047',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      currency: '$',
      items: [
        { id: uid(), label: 'Hosting', amount: 12 },
        { id: uid(), label: 'Domain', amount: 15 },
      ],
    }),
  },
  metrics: {
    type: 'metrics',
    label: 'Metrics',
    description: 'KPI tiles with value, unit, and trend',
    icon: ChartNoAxesColumn,
    category: 'data',
    accent: '#67e8f9',
    defaultSize: { width: 320, height: C * 4 },
    defaultData: () => ({
      tiles: [
        { id: uid(), label: 'Users', value: '128', unit: '', trend: 'up' },
        { id: uid(), label: 'Revenue', value: '3.2', unit: 'k', trend: 'flat' },
      ],
    }),
  },
  timer: {
    type: 'timer',
    label: 'Timer',
    description: 'A countdown timer with start, pause, and reset',
    icon: Timer,
    category: 'tracking',
    accent: '#86efac',
    defaultSize: { width: 240, height: C * 4 },
    defaultData: () => ({ label: 'Timer', durationSeconds: 300, remainingSeconds: 300, endAt: null }),
    availability: 'existing-only',
    unavailableReason: 'Countdown now lives inside the Timer widget.',
  },
  timekeeper: {
    type: 'timekeeper',
    label: 'Timer',
    description: 'Countdown, Pomodoro, and Stopwatch in one mode-switching timer',
    icon: Timer,
    category: 'tracking',
    accent: '#86efac',
    defaultSize: { width: 280, height: C * 6 },
    defaultData: () => ({
      mode: 'countdown',
      countdown: { label: 'Timer', durationSeconds: 300, remainingSeconds: 300, endAt: null },
      pomodoro: { label: 'Focus', workMinutes: 25, breakMinutes: 5, phase: 'work', endAt: null, remainingSeconds: 25 * 60, completed: 0 },
      stopwatch: { elapsedMs: 0, startedAt: null, laps: [] },
    }),
    modes: [
      { value: 'countdown', label: 'Countdown', icon: Timer },
      { value: 'pomodoro', label: 'Pomodoro', icon: Coffee },
      { value: 'stopwatch', label: 'Stopwatch', icon: Hourglass },
    ],
  },
  mood_tracker: {
    type: 'mood_tracker',
    label: 'Mood Tracker',
    description: 'A weekly mood log — tap a day to cycle through',
    icon: Smile,
    category: 'tracking',
    accent: '#fde047',
    defaultSize: { width: 300, height: C * 4 },
    sizing: { minWidth: 260, minHeight: C * 4, maxWidth: 560, maxHeight: C * 4, autoHeight: true },
    defaultData: () => ({ days: [null, null, null, null, null, null, null] }),
  },
  counter: {
    type: 'counter',
    label: 'Counter',
    description: 'A tally counter — one number, step-adjustable',
    icon: Hash,
    category: 'tracking',
    accent: '#93c5fd',
    defaultSize: { width: 260, height: C * 4 },
    defaultData: () => ({ label: 'Tally', count: 0, step: 1 }),
  },
  links: {
    type: 'links',
    label: 'Link List',
    description: 'Labelled external links, click to open',
    icon: Link2,
    category: 'tracking',
    accent: '#93c5fd',
    defaultSize: { width: 300, height: C * 4 },
    defaultData: () => ({
      items: [{ id: uid(), label: 'grovepad', url: 'https://example.com' }],
    }),
  },
  habit: {
    type: 'habit',
    label: 'Habit Tracker',
    description: 'A weekly streak grid for one habit',
    icon: Flame,
    category: 'tracking',
    accent: '#fdba74',
    defaultSize: { width: 300, height: C * 3 },
    defaultData: () => ({ label: 'Daily habit', days: [false, false, false, false, false, false, false], streak: 0 }),
  },
  contact: {
    type: 'contact',
    label: 'Contact Card',
    description: 'Name, role, and how to reach them',
    icon: Contact,
    category: 'tracking',
    accent: '#d8b4fe',
    defaultSize: { width: 300, height: C * 4 },
    defaultData: () => ({ name: '', role: '', email: '', phone: '' }),
  },
  color_palette: {
    type: 'color_palette',
    label: 'Color Palette',
    description: 'A swatch board — click a hue to copy its hex',
    icon: Palette,
    category: 'media',
    accent: '#f0abfc',
    defaultSize: { width: 260, height: C * 4 },
    defaultData: () => ({ colors: ['#a3e635', '#38bdf8', '#f472b6', '#fbbf24'] }),
  },
} satisfies Record<string, WidgetDefinition>
