import {
  Activity, Bell, CalendarSync, ChartSpline, ChefHat, CircleGauge, ContactRound,
  CreditCard, Dices, Dumbbell, Equal, FileClock, Gift, HeartHandshake,
  ListRestart, MapPinned, Pill, ReceiptText, Repeat2, Scale, ScanLine, Sigma,
  Split, Subtitles, Target, Utensils, WalletCards, Wrench,
} from 'lucide-react'
import type { ModuleType } from '../../types/spatial'
import { GRID_SIZE } from '../../types/spatial'
import type { WidgetDefinition } from '../contracts/registry'

const C = GRID_SIZE
const uid = () => crypto.randomUUID()
const today = () => new Date().toISOString().slice(0, 10)
const inDays = (days: number) => { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10) }

type ExpansionType = Extract<ModuleType,
  'clock_pulse'|'comparator'|'aggregator'|'range_mapper'|'latch'|'random_picker'|'sequencer'|'template'|'recorder'|'notifier'|
  'subscriptions'|'debt_payoff'|'expense_split'|'invoices'|'meal_planner'|'recipe'|'home_maintenance'|'chore_rotation'|'renewals_vault'|'medications'|'workout_plan'|'job_applications'|'okr'|'decision_journal'|'weekly_review'|'snippet_library'|'keep_in_touch'|'gifts_occasions'|'trip_itinerary'|'guest_list'
>

export const EXPANSION_WIDGET_DEFINITIONS: Record<ExpansionType, WidgetDefinition> = {
  clock_pulse: { type:'clock_pulse', label:'Schedule Pulse', description:'Fire automations on a schedule', icon:FileClock, category:'automation', accent:'#38bdf8', defaultSize:{width:300,height:C*6}, defaultData:()=>({label:'Daily pulse',mode:'daily',time:'08:00',days:[1,2,3,4,5],intervalMinutes:60,windowStart:'09:00',windowEnd:'17:00',lastFiredAt:null}) },
  comparator: { type:'comparator', label:'Comparator', description:'Compare numbers into a decision', icon:Equal, category:'automation', accent:'#a78bfa', defaultSize:{width:320,height:C*4}, defaultData:()=>({label:'Compare',op:'gte',a:0,b:10,low:0,high:100}) },
  aggregator: { type:'aggregator', label:'Aggregator', description:'Average min max or count inputs', icon:Sigma, category:'automation', accent:'#c084fc', defaultSize:{width:300,height:C*5}, defaultData:()=>({label:'Combine',mode:'avg',slots:[0,0,0,0,0,0]}) },
  range_mapper: { type:'range_mapper', label:'Range Mapper', description:'Turn numbers into human status bands', icon:CircleGauge, category:'automation', accent:'#fbbf24', defaultSize:{width:300,height:C*5}, defaultData:()=>({label:'Status bands',input:0,bands:[{id:uid(),upTo:25,label:'Low',emoji:'🟢'},{id:uid(),upTo:75,label:'Medium',emoji:'🟡'},{id:uid(),upTo:Number.MAX_SAFE_INTEGER,label:'High',emoji:'🔴'}]}) },
  latch: { type:'latch', label:'Snapshot Latch', description:'Capture and hold a baseline', icon:ScanLine, category:'automation', accent:'#22d3ee', defaultSize:{width:280,height:C*4}, defaultData:()=>({label:'Baseline',current:0,held:0,heldAt:null}) },
  random_picker: { type:'random_picker', label:'Random Picker', description:'Choose fairly with weighted options', icon:Dices, category:'automation', accent:'#fb7185', defaultSize:{width:300,height:C*5}, defaultData:()=>({label:'Decide for me',options:[{id:uid(),text:'Option A',weight:1},{id:uid(),text:'Option B',weight:1}],pick:'',history:[],lastRolledAt:null,noRepeatWindow:1}) },
  sequencer: { type:'sequencer', label:'Sequencer', description:'Advance through ordered stages', icon:ListRestart, category:'automation', accent:'#818cf8', defaultSize:{width:320,height:C*6}, defaultData:()=>({label:'Sequence',steps:[{id:uid(),text:'First step'},{id:uid(),text:'Second step'}],activeIndex:0,loop:false}) },
  template: { type:'template', label:'Text Composer', description:'Compose live values into sentences', icon:Subtitles, category:'automation', accent:'#34d399', defaultSize:{width:320,height:C*5}, defaultData:()=>({template:'You have {a} tasks and {b} left',slotA:'3',slotB:'$42',slotC:'',slotD:''}) },
  recorder: { type:'recorder', label:'Recorder', description:'Turn any number into history', icon:ChartSpline, category:'automation', accent:'#4ade80', defaultSize:{width:320,height:C*5}, defaultData:()=>({label:'History',input:0,samples:[],mode:'on_change',lastRecordedAt:null}) },
  notifier: { type:'notifier', label:'Notifier', description:'Send a toast or browser reminder', icon:Bell, category:'automation', accent:'#f97316', defaultSize:{width:320,height:C*5}, defaultData:()=>({label:'Reminder',message:'Something needs your attention',channel:'toast',cooldownMinutes:60,armed:false,lastFiredAt:null,fireCount:0,pendingFireAt:null}) },

  subscriptions: { type:'subscriptions', label:'Subscriptions', description:'Recurring charges and renewal pressure', icon:CreditCard, category:'life', accent:'#f472b6', defaultSize:{width:360,height:C*6}, defaultData:()=>({rows:[{id:uid(),name:'Streaming',cost:12,cycle:'monthly',renewsOn:inDays(5),active:true}] }), pack:'life' },
  debt_payoff: { type:'debt_payoff', label:'Debt Payoff', description:'Balances payoff date and interest', icon:WalletCards, category:'life', accent:'#fb7185', defaultSize:{width:380,height:C*7}, defaultData:()=>({debts:[{id:uid(),name:'Card',balance:2500,apr:19.9,minPayment:75}],extraPayment:100,strategy:'avalanche'}), pack:'life' },
  expense_split: { type:'expense_split', label:'Expense Split', description:'Calculate the smallest fair settlement', icon:Split, category:'life', accent:'#2dd4bf', defaultSize:{width:380,height:C*7}, defaultData:()=>({people:['You','Sam'],you:'You',expenses:[{id:uid(),desc:'Accommodation',amount:200,paidBy:'You',splitAmong:['You','Sam']}]}), pack:'life' },
  invoices: { type:'invoices', label:'Invoices', description:'Track receivables and overdue followups', icon:ReceiptText, category:'life', accent:'#60a5fa', defaultSize:{width:360,height:C*6}, defaultData:()=>({rows:[{id:uid(),client:'Client',amount:500,issued:today(),due:inDays(14),status:'sent'}]}), pack:'life' },
  meal_planner: { type:'meal_planner', label:'Meal Planner', description:'Plan seven days and three meals', icon:Utensils, category:'life', accent:'#f59e0b', defaultSize:{width:440,height:C*9}, defaultData:()=>({week:Array.from({length:7},(_,day)=>(['breakfast','lunch','dinner'] as const).map(meal=>({id:uid(),day,meal,dish:''}))).flat(),shoppingList:''}), pack:'life' },
  recipe: { type:'recipe', label:'Recipe', description:'Ingredients scale with servings', icon:ChefHat, category:'life', accent:'#fb923c', defaultSize:{width:360,height:C*7}, defaultData:()=>({title:'Dinner',servings:2,baseServings:2,ingredients:[{id:uid(),qty:200,unit:'g',item:'Ingredient'}],steps:[{id:uid(),text:'Prepare ingredients',done:false}],cookMinutes:30}), pack:'life' },
  home_maintenance: { type:'home_maintenance', label:'Home Maintenance', description:'Recurring jobs with their own clocks', icon:Wrench, category:'life', accent:'#a3e635', defaultSize:{width:360,height:C*7}, defaultData:()=>({rows:[{id:uid(),task:'Replace filter',everyMonths:3,lastDone:today()}]}), pack:'life' },
  chore_rotation: { type:'chore_rotation', label:'Chore Rotation', description:'Rotate household work automatically', icon:Repeat2, category:'life', accent:'#c084fc', defaultSize:{width:340,height:C*8}, defaultData:()=>({people:['You','Housemate'],chores:['Kitchen','Bins'],offset:0,cadenceLabel:'Weekly'}), pack:'life' },
  renewals_vault: { type:'renewals_vault', label:'Renewals Vault', description:'Expiry dates and renewal lead times', icon:CalendarSync, category:'life', accent:'#facc15', defaultSize:{width:360,height:C*7}, defaultData:()=>({rows:[{id:uid(),item:'Passport',expires:inDays(180),noteRef:'',renewLeadDays:90}]}), pack:'life' },
  medications: { type:'medications', label:'Medications', description:'Doses taken today and refill runway', icon:Pill, category:'life', accent:'#38bdf8', defaultSize:{width:360,height:C*6}, defaultData:()=>({rows:[{id:uid(),name:'Medication',timesPerDay:2,takenToday:[false,false],pillsLeft:30,dailyUse:2}]}), pack:'life' },
  workout_plan: { type:'workout_plan', label:'Workout Plan', description:'Training volume and progression', icon:Dumbbell, category:'life', accent:'#4ade80', defaultSize:{width:400,height:C*8}, defaultData:()=>({days:[{id:uid(),label:'Today',exercises:[{id:uid(),name:'Squat',sets:3,reps:8,weight:40,done:false}]}],activeDay:0,lastSession:''}), pack:'life' },
  job_applications: { type:'job_applications', label:'Job Applications', description:'Pipeline with followup pressure', icon:Target, category:'life', accent:'#818cf8', defaultSize:{width:400,height:C*7}, defaultData:()=>({rows:[{id:uid(),company:'Company',role:'Role',stage:'applied',applied:today(),nextAction:'Follow up',followUpBy:inDays(7)}]}), pack:'life' },
  okr: { type:'okr', label:'OKRs', description:'Weighted key results with live inputs', icon:Target, category:'life', accent:'#a3e635', defaultSize:{width:360,height:C*7}, defaultData:()=>({objective:'Meaningful objective',keyResults:[{id:uid(),label:'Key result',current:0,target:100,weight:1}]}), pack:'life' },
  decision_journal: { type:'decision_journal', label:'Decision Journal', description:'Review and score past decisions', icon:Scale, category:'life', accent:'#fbbf24', defaultSize:{width:380,height:C*7}, defaultData:()=>({entries:[{id:uid(),decision:'Decision',context:'',expected:'',confidence:70,decidedOn:today(),reviewOn:inDays(30)}]}), pack:'life' },
  weekly_review: { type:'weekly_review', label:'Weekly Review', description:'A recurring reflection ritual', icon:Activity, category:'life', accent:'#2dd4bf', defaultSize:{width:360,height:C*7}, defaultData:()=>({prompts:[{id:uid(),q:'What went well?',answer:''},{id:uid(),q:'What should change?',answer:''},{id:uid(),q:'What carries forward?',answer:''}],weekOf:today(),historyCount:0,streak:0,completedThisWeek:false}), pack:'life' },
  snippet_library: { type:'snippet_library', label:'Snippet Library', description:'Reusable text sorted by use', icon:Subtitles, category:'life', accent:'#60a5fa', defaultSize:{width:360,height:C*7}, defaultData:()=>({entries:[{id:uid(),title:'Quick reply',body:'Thanks — I will get back to you shortly.',tags:['email'],useCount:0}]}), pack:'life' },
  keep_in_touch: { type:'keep_in_touch', label:'Keep in Touch', description:'Relationship cadence and overdue contacts', icon:ContactRound, category:'life', accent:'#f472b6', defaultSize:{width:360,height:C*6}, defaultData:()=>({rows:[{id:uid(),name:'Nadia',cadenceDays:14,lastContact:today(),note:''}]}), pack:'life' },
  gifts_occasions: { type:'gifts_occasions', label:'Gifts & Occasions', description:'Occasions ideas and planned spend', icon:Gift, category:'life', accent:'#fb7185', defaultSize:{width:360,height:C*6}, defaultData:()=>({rows:[{id:uid(),person:'Someone',date:inDays(30),ideas:'',budget:50,bought:false}]}), pack:'life' },
  trip_itinerary: { type:'trip_itinerary', label:'Trip Itinerary', description:'Daily legs bookings and confirmations', icon:MapPinned, category:'life', accent:'#38bdf8', defaultSize:{width:420,height:C*10}, defaultData:()=>({tripName:'Trip',startDate:inDays(30),days:[{id:uid(),date:inDays(30),legs:[{id:uid(),time:'09:00',what:'Arrival',where:'',confirmation:'',booked:false}]}]}), pack:'life' },
  guest_list: { type:'guest_list', label:'Guest List', description:'RSVP headcount and dietary needs', icon:HeartHandshake, category:'life', accent:'#c084fc', defaultSize:{width:360,height:C*7}, defaultData:()=>({rows:[{id:uid(),name:'Guest',status:'invited',plusOnes:0,dietary:''}]}), pack:'life' },
}
