import {
  CalendarClock,
  FunctionSquare,
  Gauge,
  Binary,
  Hash,
  Image,
  MessagesSquare,
  PenTool,
  Shapes,
  Sparkles,
  TextCursorInput,
  ToggleRight,
} from 'lucide-react'
import type { WidgetDefinition } from '../contracts/registry'
import { localDayKeyInDays } from '../../utils/localDate'
import { C, uid } from './definitionHelpers'

/** Media, input, and logic widgets (media … date_picker). Extracted verbatim from registry.ts; key order preserved. */
export const MEDIA_INPUT_WIDGET_DEFINITIONS = {
  media: {
    type: 'media',
    label: 'Media',
    description: 'An image by URL with a caption',
    icon: Image,
    category: 'media',
    accent: '#f9a8d4',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({ url: '', caption: '' }),
  },
  sketchpad: {
    type: 'sketchpad',
    label: 'Drawing',
    description: 'Quick pressure-sensitive ink and full diagram modes',
    icon: PenTool,
    category: 'media',
    accent: '#fcd34d',
    defaultSize: { width: C * 12, height: C * 9 },
    sizing: { minWidth: C * 7, minHeight: C * 5 },
    defaultData: () => ({
      height: 240,
      strokes: [],
      mode: 'ink',
      diagram: { elements: [], appState: {}, files: [], updatedAt: new Date().toISOString() },
    }),
    modes: [
      { value: 'ink', label: 'Quick Ink', icon: PenTool },
      { value: 'diagram', label: 'Diagram', icon: Shapes },
    ],
  },
  excalidraw: {
    type: 'excalidraw',
    label: 'Excalidraw',
    description: 'Freehand sketches, diagrams, flowcharts, and whiteboards',
    icon: Shapes,
    category: 'media',
    accent: '#93c5fd',
    defaultSize: { width: C * 12, height: C * 9 },
    sizing: { minWidth: C * 7, minHeight: C * 6 },
    defaultData: () => ({ elements: [], appState: {}, files: [], updatedAt: new Date().toISOString() }),
  },
  dialog: {
    type: 'dialog',
    label: 'Dialog',
    description: 'Script lines by character',
    icon: MessagesSquare,
    category: 'media',
    accent: '#a5b4fc',
    defaultSize: { width: 360, height: C * 5 },
    defaultData: () => ({
      lines: [
        {
          id: uid(),
          character: 'NARRATOR',
          cue: 'The canvas stretches on, in every direction.',
        },
      ],
    }),
  },
  ai_generator: {
    type: 'ai_generator',
    label: 'AI Generator',
    description: 'Prompt-driven content generator',
    icon: Sparkles,
    category: 'media',
    accent: '#a3e635',
    defaultSize: { width: 320, height: C * 4 },
    defaultData: () => ({ prompt: '', status: 'idle' }),
  },
  text_input: {
    type: 'text_input',
    label: 'Text Input',
    description: 'A clean text value that can feed any connected branch',
    icon: TextCursorInput,
    category: 'data',
    accent: '#f472b6',
    defaultSize: { width: 280, height: C * 3 },
    defaultData: () => ({
      label: 'Input',
      value: '',
      placeholder: 'Type a value…',
      multiline: false,
    }),
  },
  number_input: {
    type: 'number_input',
    label: 'Number Input',
    description: 'A bounded number, slider, and stepper for live calculations',
    icon: Hash,
    category: 'data',
    accent: '#38bdf8',
    defaultSize: { width: 280, height: C * 4 },
    defaultData: () => ({ label: 'Value', value: 0, min: 0, max: 100, step: 1 }),
  },
  toggle: {
    type: 'toggle',
    label: 'Toggle',
    description: 'A simple on/off condition for gates, triggers, and branches',
    icon: ToggleRight,
    category: 'data',
    accent: '#fbbf24',
    defaultSize: { width: 240, height: C * 3 },
    defaultData: () => ({ label: 'Condition', value: false }),
  },
  branch_gate: {
    type: 'branch_gate',
    label: 'Bool Gate',
    description: 'A true/false condition with both normal and inverse outputs',
    icon: Binary,
    category: 'structure',
    accent: '#a78bfa',
    defaultSize: { width: C * 7, height: C * 3 },
    sizing: { minWidth: C * 4, minHeight: C * 2 },
    defaultData: () => ({
      value: false,
      trueLabel: 'Yes',
      falseLabel: 'No',
      trueNote: '',
      falseNote: '',
    }),
  },
  formula: {
    type: 'formula',
    label: 'Formula',
    description: 'Combine two connected numbers and publish the live result',
    icon: FunctionSquare,
    category: 'data',
    accent: '#818cf8',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({ label: 'Calculation', a: 0, b: 0, operator: 'add' }),
  },
  status: {
    type: 'status',
    label: 'Status',
    description: 'A universal workflow state with progress and completion outputs',
    icon: Gauge,
    category: 'tracking',
    accent: '#34d399',
    defaultSize: { width: 280, height: C * 3 },
    defaultData: () => ({ label: 'Status', value: 'not_started' }),
  },
  date_picker: {
    type: 'date_picker',
    label: 'Date',
    description: 'Edit a target date and switch between date-time and countdown views',
    icon: CalendarClock,
    category: 'planning',
    accent: '#fb923c',
    defaultSize: { width: 280, height: C * 4 },
    defaultData: () => ({ label: 'Target date', date: localDayKeyInDays(1), time: '', includeTime: false, mode: 'date_time' }),
    modes: [
      { value: 'date_time', label: 'Date & Time', icon: CalendarClock },
      { value: 'countdown', label: 'Countdown', icon: CalendarClock },
    ],
  },
} satisfies Record<string, WidgetDefinition>
