import {
  AudioLines,
  CalendarClock,
  CalendarHeart,
  CalendarRange,
  Clapperboard,
  Flag,
  Hourglass,
  FileText,
  FunctionSquare,
  FileImage,
  Frame,
  Gauge,
  Binary,
  CircleDashed,
  CircleDot,
  Columns2,
  Drama,
  Hash,
  Grip,
  Grid2X2,
  Image,
  Images,
  Languages,
  LayoutDashboard,
  AlignLeft,
  AtSign,
  GitBranch,
  Link2,
  MessageCircle,
  MessagesSquare,
  Mic2,
  PanelsTopLeft,
  PenTool,
  Power,
  Percent,
  Repeat,
  Scale,
  Scale3d,
  Search,
  Sunrise,
  Shapes,
  Sigma,
  SlidersHorizontal,
  Sparkles,
  SquareCheckBig,
  Tags,
  TerminalSquare,
  TextCursorInput,
  ToggleRight,
  TrendingUp,
  Variable,
} from 'lucide-react'
import type { WidgetDefinition } from '../contracts/registry'
import { localDayKeyInDays } from '../../utils/localDate'
import { C, uid } from './definitionHelpers'

/** Media, input, and logic widgets (media … date_picker). Extracted verbatim from registry.ts; key order preserved. */
export const MEDIA_INPUT_WIDGET_DEFINITIONS = {
  media: {
    type: 'media',
    label: 'Media',
    description: 'A picture, clip, recording, or document — with a caption',
    icon: Image,
    category: 'media',
    accent: '#f9a8d4',
    defaultSize: { width: 320, height: C * 5 },
    // An image card may be genuinely small — its content scales, unlike
    // control rows. The resting image face relies on this floor.
    sizing: { minWidth: 120, minHeight: 80 },
    defaultData: () => ({ url: '', caption: '' }),
    // Every skin here is renderer-owned, so the generic schema-extension
    // overlay never doubles the gallery's and moodboard's own controls.
    rendererOwnedSkinDetails: ['gallery', 'moodboard'],
    // Declared by hand so each skin wears an icon that says what it is (the
    // catalogue merge falls back to one icon per presentation family). The
    // rest of each entry repeats its catalogue blueprint verbatim.
    // `skinField` must stay 'skin': MediaData has no `mode`, and the merge
    // only assigns the field when a widget declares no skins of its own.
    skinField: 'skin',
    skins: [
      {
        value: 'image',
        label: 'Image',
        description: 'The current single image with caption.',
        implementation: 'renderer-ready',
        presentation: 'media',
        icon: Image,
        accent: '#e4ab72',
      },
      {
        value: 'video',
        label: 'Video',
        description: 'A player-first view with poster and caption.',
        implementation: 'renderer-ready',
        presentation: 'media',
        icon: Clapperboard,
        accent: '#72d9e4',
      },
      {
        value: 'audio',
        label: 'Audio',
        description: 'Waveform or player treatment for a sound asset.',
        implementation: 'renderer-ready',
        presentation: 'form',
        icon: AudioLines,
        accent: '#72e4e4',
      },
      {
        value: 'document_preview',
        label: 'Document Preview',
        description: 'First-page or file-type preview with metadata.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: FileText,
        accent: '#72d1e4',
      },
      {
        value: 'before_after',
        label: 'Before / After',
        description: 'Compares two versions with a draggable reveal.',
        implementation: 'renderer-ready',
        presentation: 'matrix',
        icon: SlidersHorizontal,
        accent: '#72e487',
      },
      {
        value: 'gallery',
        label: 'Gallery',
        description: 'Stores and browses several related media items.',
        implementation: 'schema-extension',
        presentation: 'grid',
        icon: Images,
        accent: '#a372e4',
      },
      {
        value: 'moodboard',
        label: 'Moodboard',
        description: 'Supports free visual arrangement and annotations.',
        implementation: 'schema-extension',
        presentation: 'board',
        icon: LayoutDashboard,
        accent: '#e472b2',
      },
    ],
  },
  sketchpad: {
    type: 'sketchpad',
    label: 'Drawing',
    description: 'Ink, paper, storyboards, annotations, and Excalidraw in one studio',
    icon: PenTool,
    category: 'media',
    accent: '#fcd34d',
    defaultSize: { width: C * 12, height: C * 9 },
    sizing: { minWidth: C * 7, minHeight: C * 5 },
    defaultData: () => ({
      height: 240,
      strokes: [],
      mode: 'ink',
      diagram: { elements: [], appState: {}, files: [], updatedAt: new Date().toISOString() },
      skinStates: {},
    }),
    rendererOwnedSkinDetails: ['storyboard', 'annotation', 'diagram'],
    skins: [
      {
        value: 'ink',
        label: 'Quick Ink',
        description: 'A fast pressure-sensitive canvas for handwriting and loose sketches.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: PenTool,
        accent: '#fcd34d',
      },
      {
        value: 'whiteboard',
        label: 'Whiteboard',
        description: 'An infinite light-background diagram surface.',
        implementation: 'renderer-ready',
        presentation: 'board',
        icon: Sparkles,
        accent: '#ba72e4',
      },
      {
        value: 'graph_paper',
        label: 'Graph Paper',
        description: 'A precise square-grid surface for spatial reasoning.',
        implementation: 'renderer-ready',
        presentation: 'map',
        icon: Grid2X2,
        accent: '#72d1e4',
      },
      {
        value: 'dot_grid',
        label: 'Dot Grid',
        description: 'A quieter alignment aid for notes and diagrams.',
        implementation: 'renderer-ready',
        presentation: 'grid',
        icon: Grip,
        accent: '#72d1e4',
      },
      {
        value: 'storyboard',
        label: 'Storyboard',
        description: 'Adds ordered frames with captions and shot notes.',
        implementation: 'schema-extension',
        presentation: 'board',
        icon: Frame,
        accent: '#729ce4',
      },
      {
        value: 'annotation',
        label: 'Annotation',
        description: 'Uses an imported image or PDF page as the locked background.',
        implementation: 'schema-extension',
        presentation: 'media',
        icon: FileImage,
        accent: '#e472d9',
      },
      {
        value: 'diagram',
        label: 'Excalidraw',
        description: 'A fullscreen infinite canvas for shapes, arrows, text, and freehand diagrams.',
        implementation: 'schema-extension',
        presentation: 'board',
        icon: Shapes,
        accent: '#6965db',
      },
    ],
  },
  excalidraw: {
    type: 'excalidraw',
    label: 'Excalidraw',
    description: 'Freehand sketches, diagrams, flowcharts, and whiteboards',
    icon: Shapes,
    category: 'media',
    accent: '#93c5fd',
    defaultSize: { width: C * 12, height: C * 9 },
    sizing: { minWidth: C * 7, minHeight: C * 6 },
    defaultData: () => ({ elements: [], appState: {}, files: [], updatedAt: new Date().toISOString() }),
  },
  dialog: {
    type: 'dialog',
    label: 'Dialog',
    description: 'Screenplays, conversations, interviews, and localized scripts',
    icon: MessagesSquare,
    category: 'media',
    accent: '#a5b4fc',
    defaultSize: { width: 400, height: C * 7 },
    sizing: { minWidth: C * 7, minHeight: C * 5 },
    skinField: 'skin',
    rendererOwnedSkinDetails: ['roleplay', 'comic', 'localization', 'audio_transcript'],
    skins: [
      {
        value: 'screenplay',
        label: 'Screenplay',
        description: 'Character headings, parentheticals, dialogue, and scene rhythm.',
        implementation: 'renderer-ready',
        presentation: 'ledger',
        icon: Clapperboard,
        accent: '#e47b72',
      },
      {
        value: 'chat',
        label: 'Chat',
        description: 'Message bubbles with alternating speakers.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: MessageCircle,
        accent: '#72e498',
      },
      {
        value: 'interview',
        label: 'Interview',
        description: 'Question-and-answer transcript styling.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Mic2,
        accent: '#c772e4',
      },
      {
        value: 'roleplay',
        label: 'Roleplay',
        description: 'Speaker goals, hidden notes, and performance prompts.',
        implementation: 'schema-extension',
        presentation: 'form',
        icon: Drama,
        accent: '#e4cd72',
      },
      {
        value: 'comic',
        label: 'Comic',
        description: 'Groups lines into panels and speech balloons.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: PanelsTopLeft,
        accent: '#72b8e4',
      },
      {
        value: 'localization',
        label: 'Localization',
        description: 'Shows source and translated lines side by side.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: Languages,
        accent: '#72e4c9',
      },
      {
        value: 'audio_transcript',
        label: 'Audio Transcript',
        description: 'Adds timestamps and speaker identification.',
        implementation: 'schema-extension',
        presentation: 'media',
        icon: AudioLines,
        accent: '#e4a772',
      },
    ],
    defaultData: () => ({
      skin: 'screenplay',
      skinStates: {},
      lines: [
        {
          id: uid(),
          character: 'NARRATOR',
          cue: 'The canvas stretches on, in every direction.',
        },
      ],
    }),
  },
  ai_generator: {
    type: 'ai_generator',
    label: 'AI Generator',
    description: 'Prompt-driven content generator',
    icon: Sparkles,
    category: 'media',
    accent: '#a3e635',
    defaultSize: { width: 320, height: C * 4 },
    defaultData: () => ({ prompt: '', status: 'idle' }),
  },
  text_input: {
    type: 'text_input',
    label: 'Text Input',
    description: 'A clean text value that can feed any connected branch',
    icon: TextCursorInput,
    category: 'data',
    accent: '#f472b6',
    restingFace: true,
    // Tags and Command stack a field over a list, so the card opens with room
    // for both rather than clipping the list the moment either is worn.
    defaultSize: { width: 300, height: C * 5 },
    sizing: { minWidth: C * 4, minHeight: C * 3 },
    defaultData: () => ({
      label: 'Input',
      value: '',
      placeholder: 'Type a value…',
      multiline: false,
      skin: 'single_line',
    }),
    // Command keeps a draft and a run history of its own, so its renderer owns
    // that editor and the generic schema-extension overlay never doubles it.
    rendererOwnedSkinDetails: ['tags', 'command'],
    // Declared by hand so each skin wears an icon that says what it asks for;
    // the catalogue merge would have given five of the seven the same
    // "standard" sparkle. `skinField` must stay 'skin' — `TextInputData` has
    // no `mode`, and `value` is the string a wire reads.
    skinField: 'skin',
    skins: [
      {
        value: 'single_line',
        label: 'Single Line',
        description: 'The current compact text source.',
        implementation: 'renderer-ready',
        presentation: 'compact',
        icon: TextCursorInput,
        accent: '#e472c7',
      },
      {
        value: 'multiline',
        label: 'Multiline',
        description: 'A larger text area for paragraphs and payloads.',
        implementation: 'renderer-ready',
        presentation: 'chart',
        icon: AlignLeft,
        accent: '#7281e4',
      },
      {
        value: 'search',
        label: 'Search',
        description: 'Search-field styling with clear and submit affordances.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Search,
        accent: '#729de4',
      },
      {
        value: 'url',
        label: 'URL',
        description: 'Validates and normalizes a web address.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Link2,
        accent: '#e4b172',
      },
      {
        value: 'email',
        label: 'Email',
        description: 'Validates an email-shaped value without sending it.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: AtSign,
        accent: '#e472dc',
      },
      {
        value: 'tags',
        label: 'Tags',
        description: 'Produces an ordered list of small text tokens.',
        implementation: 'schema-extension',
        presentation: 'ledger',
        icon: Tags,
        accent: '#e47772',
      },
      {
        value: 'command',
        label: 'Command',
        description: 'Keeps history and emits submitted values rather than every keystroke.',
        implementation: 'schema-extension',
        presentation: 'terminal',
        icon: TerminalSquare,
        accent: '#72a5e4',
      },
    ],
  },
  number_input: {
    type: 'number_input',
    label: 'Number Input',
    description: 'A bounded number, slider, and stepper for live calculations',
    icon: Hash,
    category: 'data',
    accent: '#38bdf8',
    restingFace: true,
    defaultSize: { width: 280, height: C * 4 },
    defaultData: () => ({ label: 'Value', value: 0, min: 0, max: 100, step: 1 }),
  },
  toggle: {
    type: 'toggle',
    label: 'Toggle',
    description: 'A simple on/off condition for gates, triggers, and branches',
    icon: ToggleRight,
    category: 'data',
    accent: '#fbbf24',
    restingFace: true,
    // Power and Availability are hero controls, not rows: the old 3-cell card
    // left no room for the button and its two lines of language.
    defaultSize: { width: 240, height: C * 4 },
    sizing: { minWidth: C * 4, minHeight: C * 3 },
    defaultData: () => ({ label: 'Condition', value: false }),
    rendererOwnedSkinDetails: ['tri_state'],
    // Declared by hand so each skin wears its own icon; the catalogue merge
    // would have given all six the same "standard" sparkle. `skinField` must
    // stay 'skin' — `ToggleData.mode` does not exist, and `value` is the
    // circuit's canonical boolean and must never be reused as a skin field.
    skinField: 'skin',
    skins: [
      {
        value: 'switch',
        label: 'Switch',
        description: 'The current sliding on/off control.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: ToggleRight,
        accent: '#9872e4',
      },
      {
        value: 'checkbox',
        label: 'Checkbox',
        description: 'A conventional completion-style boolean.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: SquareCheckBig,
        accent: '#bce472',
      },
      {
        value: 'power',
        label: 'Power',
        description: 'One large armed/disarmed button.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Power,
        accent: '#72e4a7',
      },
      {
        value: 'segment',
        label: 'Segment',
        description: 'Two explicit labeled choices rather than an abstract switch.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Columns2,
        accent: '#72d1e4',
      },
      {
        value: 'availability',
        label: 'Availability',
        description: 'Available/busy language with status color.',
        implementation: 'renderer-ready',
        presentation: 'dashboard',
        icon: CircleDot,
        accent: '#cbe472',
      },
      {
        value: 'tri_state',
        label: 'Tri-state',
        description: 'Adds unknown or automatic between off and on.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: CircleDashed,
        accent: '#b872e4',
      },
    ],
  },
  branch_gate: {
    type: 'branch_gate',
    label: 'Bool Gate',
    description: 'A true/false condition with both normal and inverse outputs',
    icon: Binary,
    category: 'structure',
    accent: '#a78bfa',
    restingFace: true,
    defaultSize: { width: C * 7, height: C * 3 },
    sizing: { minWidth: C * 4, minHeight: C * 2 },
    defaultData: () => ({
      value: false,
      trueLabel: 'Yes',
      falseLabel: 'No',
      trueNote: '',
      falseNote: '',
    }),
  },
  formula: {
    type: 'formula',
    label: 'Formula',
    description: 'Ask one question of two connected numbers and publish the answer',
    icon: FunctionSquare,
    category: 'data',
    accent: '#818cf8',
    restingFace: true,
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({ label: 'Calculation', a: 0, b: 0, operator: 'add' }),
    rendererOwnedSkinDetails: ['expression', 'weighted_score', 'conditional'],
    // Declared by hand so each question wears its own icon; the catalogue merge
    // gives every `standard` skin the same sparkle. Value, label, description,
    // implementation, presentation, and accent repeat the generated blueprint
    // verbatim (skinCatalog.test.ts matches them). `skinField` must stay 'skin':
    // `FormulaData` has no `mode`, and `a`/`b` are the circuit's own inputs.
    skinField: 'skin',
    skins: [
      {
        value: 'two_input',
        label: 'Two-input',
        description: 'The current A/B operation surface.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Sigma,
        accent: '#72cfe4',
      },
      {
        value: 'percent_change',
        label: 'Percent Change',
        description: 'Old value, new value, and percent movement.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Percent,
        accent: '#c7e472',
      },
      {
        value: 'ratio',
        label: 'Ratio',
        description: 'Part-to-whole and simplified ratio output.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Scale,
        accent: '#ab72e4',
      },
      {
        value: 'growth',
        label: 'Growth',
        description: 'Starting value, rate, periods, and projected result.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: TrendingUp,
        accent: '#e4cd72',
      },
      {
        value: 'expression',
        label: 'Expression',
        description: 'Supports a safe expression over named inputs.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: Variable,
        accent: '#e47275',
      },
      {
        value: 'weighted_score',
        label: 'Weighted Score',
        description: 'Combines several value/weight pairs.',
        implementation: 'schema-extension',
        presentation: 'dashboard',
        icon: Scale3d,
        accent: '#e4cd72',
      },
      {
        value: 'conditional',
        label: 'Conditional',
        description: 'Returns one of two values based on a comparison.',
        implementation: 'schema-extension',
        presentation: 'matrix',
        icon: GitBranch,
        accent: '#e47b72',
      },
    ],
  },
  status: {
    type: 'status',
    label: 'Status',
    description: 'A universal workflow state with progress and completion outputs',
    icon: Gauge,
    category: 'tracking',
    accent: '#34d399',
    restingFace: true,
    defaultSize: { width: 280, height: C * 3 },
    defaultData: () => ({ label: 'Status', value: 'not_started' }),
  },
  date_picker: {
    type: 'date_picker',
    label: 'Date',
    description: 'Choose a reusable date and optional time',
    icon: CalendarClock,
    category: 'planning',
    accent: '#fb923c',
    restingFace: true,
    defaultSize: { width: 280, height: C * 4 },
    defaultData: () => ({ label: 'Target date', date: localDayKeyInDays(1), time: '', includeTime: false, mode: 'date_time' }),
    skinField: 'mode',
    /**
     * The three optional-state skins draw their own editors, so the generic
     * skin-details popover never opens over a card that already asks for the
     * end of a range, a repeat rule, or an owner in place.
     */
    rendererOwnedSkinDetails: ['range', 'recurring_date', 'milestone'],
    skins: [
      {
        value: 'date_time',
        label: 'Date & Time',
        description: 'The day itself, with an optional time.',
        implementation: 'renderer-ready',
        presentation: 'time',
        icon: CalendarClock,
        accent: '#fb923c',
      },
      {
        value: 'deadline',
        label: 'Deadline',
        description: 'Emphasizes remaining time and overdue state.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Hourglass,
        accent: '#e47572',
      },
      {
        value: 'anniversary',
        label: 'Anniversary',
        description: 'Repeats the same month and day each year.',
        implementation: 'renderer-ready',
        presentation: 'timeline',
        icon: CalendarHeart,
        accent: '#85e472',
      },
      {
        value: 'relative_date',
        label: 'Relative Date',
        description: 'Displays today, tomorrow, next week, or elapsed time.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Sunrise,
        accent: '#e4a772',
      },
      {
        value: 'range',
        label: 'Range',
        description: 'Stores start and end dates and calculates duration.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: CalendarRange,
        accent: '#e4cd72',
      },
      {
        value: 'recurring_date',
        label: 'Recurring Date',
        description: 'Adds repeat rules and the next occurrence.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: Repeat,
        accent: '#72a1e4',
      },
      {
        value: 'milestone',
        label: 'Milestone',
        description: 'Adds owner, status, and linked deliverable.',
        implementation: 'schema-extension',
        presentation: 'dashboard',
        icon: Flag,
        accent: '#7292e4',
      },
    ],
  },
} satisfies Record<string, WidgetDefinition>
