import {
  ArrowLeftRight,
  AudioLines,
  Binary,
  BookMarked,
  CalendarDays,
  CalendarRange,
  ChefHat,
  ChartLine,
  ChartPie,
  Clapperboard,
  ClipboardCheck,
  ClipboardList,
  CircleDollarSign,
  Columns3,
  FileCheck2,
  FolderTree,
  Gamepad2,
  GitCommitHorizontal,
  GraduationCap,
  Grid2x2,
  FlaskConical,
  Link2,
  ListChecks,
  ListTree,
  MapPinned,
  MessageSquare,
  PanelsTopLeft,
  Package,
  PartyPopper,
  Ruler,
  ScrollText,
  ShieldCheck,
  ShieldAlert,
  Siren,
  Sparkles,
  SquareFunction,
  ThermometerSun,
  Timer,
  Wrench,
  Workflow,
} from 'lucide-react'
import type { WidgetDefinition } from '../contracts/registry'
import { C, uid, todayISO } from './definitionHelpers'

/** Professional, ops, and specialist widgets (outline … audio_player). Extracted verbatim from registry.ts; key order preserved. */
export const PROFESSIONAL_WIDGET_DEFINITIONS = {
  outline: {
    type: 'outline',
    label: 'Outline',
    description: 'Shape ideas as trees, formal documents, stories, sites, courses, plans, and expandable briefs',
    icon: ListTree,
    category: 'notes',
    accent: '#60a5fa',
    restingFace: true,
    defaultSize: { width: 400, height: C * 7 },
    defaultData: () => ({
      skin: 'tree',
      items: [{ id: uid(), text: 'First idea', depth: 0, collapsed: false }],
    }),
    skinField: 'skin',
    rendererOwnedSkinDetails: ['work_breakdown', 'collapsible_brief'],
    skins: [
      {
        value: 'tree',
        label: 'Tree',
        description: 'The current nested outline.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: ListTree,
        accent: '#e47279',
      },
      {
        value: 'roman',
        label: 'Roman',
        description: 'Formal I/A/1 hierarchy for documents and policies.',
        implementation: 'renderer-ready',
        presentation: 'form',
        icon: ScrollText,
        accent: '#729ce4',
      },
      {
        value: 'scenes',
        label: 'Scenes',
        description: 'Story scenes grouped into acts and sequences.',
        implementation: 'renderer-ready',
        presentation: 'steps',
        icon: Clapperboard,
        accent: '#72e496',
      },
      {
        value: 'sitemap',
        label: 'Sitemap',
        description: 'Pages grouped under navigation sections.',
        implementation: 'renderer-ready',
        presentation: 'map',
        icon: FolderTree,
        accent: '#a372e4',
      },
      {
        value: 'course',
        label: 'Course',
        description: 'Modules, lessons, and exercises.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: GraduationCap,
        accent: '#e472d3',
      },
      {
        value: 'work_breakdown',
        label: 'Work Breakdown',
        description: 'Adds owner, estimate, and completion to outline nodes.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: ListChecks,
        accent: '#e472cd',
      },
      {
        value: 'collapsible_brief',
        label: 'Collapsible Brief',
        description: 'Adds notes and attachments under each heading.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: PanelsTopLeft,
        accent: '#729ce4',
      },
    ],
  },
  form: {
    type: 'form',
    label: 'Form',
    description: 'Build and complete a compact form with required-field tracking',
    icon: ClipboardList,
    category: 'data',
    accent: '#2dd4bf',
    restingFace: true,
    defaultSize: { width: 400, height: C * 7 },
    defaultData: () => ({
      skin: 'intake',
      title: 'Quick form',
      fields: [{ id: uid(), label: 'Name', type: 'text', value: '', required: true }],
    }),
    // Declared by hand so each preset wears its own icon; the generated
    // catalogue gave the four "form" ones the same checklist glyph.
    // `skinField` must stay 'skin' — `FormWidgetData` has no `mode`, and the
    // filled/complete outputs a circuit reads must not move when the card only
    // changes shape.
    skinField: 'skin',
    rendererOwnedSkinDetails: ['application', 'conditional_form'],
    skins: [
      {
        value: 'intake',
        label: 'Intake',
        description: 'A practical mixed-field information request.',
        implementation: 'renderer-ready',
        presentation: 'form',
        icon: ClipboardList,
        accent: '#cd72e4',
      },
      {
        value: 'survey',
        label: 'Survey',
        description: 'Question-first layout optimized for completion.',
        implementation: 'renderer-ready',
        presentation: 'form',
        icon: ListChecks,
        accent: '#e472be',
      },
      {
        value: 'feedback',
        label: 'Feedback',
        description: 'Ratings, comments, and improvement prompts.',
        implementation: 'renderer-ready',
        presentation: 'form',
        icon: MessageSquare,
        accent: '#e4cd72',
      },
      {
        value: 'rsvp',
        label: 'RSVP',
        description: 'Attendance, plus-ones, dietary needs, and message.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: PartyPopper,
        accent: '#e48972',
      },
      {
        value: 'inspection',
        label: 'Inspection',
        description: 'Pass/fail checks with comments.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: ClipboardCheck,
        accent: '#b2e472',
      },
      {
        value: 'application',
        label: 'Application',
        description: 'Adds sections, required evidence, and review state.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: FileCheck2,
        accent: '#85e472',
      },
      {
        value: 'conditional_form',
        label: 'Conditional Form',
        description: 'Shows later questions based on earlier responses.',
        implementation: 'schema-extension',
        presentation: 'form',
        icon: Link2,
        accent: '#72c0e4',
      },
    ],
  },
  daily_agenda: {
    type: 'daily_agenda',
    label: 'Daily Agenda',
    description: 'A focused schedule of timed, completable items for one day',
    icon: CalendarRange,
    category: 'planning',
    accent: '#7dd3fc',
    restingFace: true,
    defaultSize: { width: 360, height: C * 7 },
    defaultData: () => ({
      date: todayISO(),
      items: [{ id: uid(), time: '09:00', title: 'First item', done: false }],
    }),
  },
  process: {
    type: 'process',
    label: 'Process / SOP',
    description: 'A sequential procedure with one active step and live progress',
    icon: Workflow,
    category: 'planning',
    accent: '#a3e635',
    restingFace: true,
    defaultSize: { width: 360, height: C * 6 },
    defaultData: () => ({
      steps: [{ id: uid(), label: 'First step', status: 'active' }],
    }),
  },
  risk_register: {
    type: 'risk_register',
    label: 'Risk Register',
    description: 'Score likelihood and impact, record mitigation, resolve risks',
    icon: ShieldAlert,
    category: 'planning',
    accent: '#fb7185',
    restingFace: true,
    defaultSize: { width: 440, height: C * 6 },
    defaultData: () => ({
      items: [
        {
          id: uid(),
          risk: 'New risk',
          likelihood: 2,
          impact: 2,
          mitigation: '',
          status: 'open',
        },
      ],
    }),
  },
  decision_matrix: {
    type: 'decision_matrix',
    label: 'Decision Matrix',
    description: 'Compare options against weighted criteria and reveal a winner',
    icon: Grid2x2,
    category: 'planning',
    accent: '#c084fc',
    restingFace: true,
    defaultSize: { width: 440, height: C * 6 },
    defaultData: () => ({
      criteria: [{ id: uid(), label: 'Value', weight: 1 }],
      options: [
        { id: uid(), label: 'Option A', scores: [3] },
        { id: uid(), label: 'Option B', scores: [3] },
      ],
    }),
  },
  swot: {
    type: 'swot',
    label: 'SWOT Analysis',
    description: 'Strengths, weaknesses, opportunities, and threats in one view',
    icon: Columns3,
    category: 'planning',
    accent: '#f59e0b',
    restingFace: true,
    defaultSize: { width: 400, height: C * 6 },
    defaultData: () => ({ strengths: [''], weaknesses: [''], opportunities: [''], threats: [''] }),
  },
  timesheet: {
    type: 'timesheet',
    label: 'Timesheet',
    description: 'Log hours, mark billable work, and calculate live totals',
    icon: Timer,
    category: 'tracking',
    accent: '#22d3ee',
    restingFace: true,
    defaultSize: { width: 400, height: C * 6 },
    defaultData: () => ({
      currency: '$',
      hourlyRate: 0,
      entries: [{ id: uid(), date: todayISO(), label: 'Work', hours: 1, billable: true }],
    }),
  },
  inventory: {
    type: 'inventory',
    label: 'Inventory',
    description: 'Track quantities and immediately surface low-stock items',
    icon: Package,
    category: 'tracking',
    accent: '#facc15',
    restingFace: true,
    defaultSize: { width: 400, height: C * 6 },
    defaultData: () => ({
      items: [{ id: uid(), name: 'Item', quantity: 1, minimum: 0, unit: 'pcs' }],
    }),
  },
  logbook: {
    type: 'logbook',
    label: 'Logbook',
    description: 'Chronicle daily events, incidents, experiments, changes, service, audits, and journeys',
    icon: BookMarked,
    category: 'notes',
    accent: '#94a3b8',
    restingFace: true,
    defaultSize: { width: 400, height: C * 7 },
    defaultData: () => ({
      skin: 'daily_log',
      entries: [{ id: uid(), timestamp: new Date().toISOString(), text: 'First entry', level: 'note' }],
    }),
    skinField: 'skin',
    rendererOwnedSkinDetails: ['audit_trail', 'travel_log'],
    skins: [
      {
        value: 'daily_log',
        label: 'Daily Log',
        description: 'Chronological dated entries.',
        implementation: 'renderer-ready',
        presentation: 'timeline',
        icon: CalendarDays,
        accent: '#e472e2',
      },
      {
        value: 'incident_log',
        label: 'Incident Log',
        description: 'Severity, impact, response, and resolution.',
        implementation: 'renderer-ready',
        presentation: 'ledger',
        icon: Siren,
        accent: '#e47572',
      },
      {
        value: 'lab_notebook',
        label: 'Lab Notebook',
        description: 'Hypothesis, method, observation, and conclusion.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: FlaskConical,
        accent: '#729ce4',
      },
      {
        value: 'change_log',
        label: 'Change Log',
        description: 'Version, change, author, and date.',
        implementation: 'renderer-ready',
        presentation: 'ledger',
        icon: GitCommitHorizontal,
        accent: '#b872e4',
      },
      {
        value: 'maintenance_log',
        label: 'Maintenance Log',
        description: 'Asset, work performed, parts, and next service.',
        implementation: 'renderer-ready',
        presentation: 'form',
        icon: Wrench,
        accent: '#e472c6',
      },
      {
        value: 'audit_trail',
        label: 'Audit Trail',
        description: 'Creates append-only entries with actor and source.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: ShieldCheck,
        accent: '#72e49f',
      },
      {
        value: 'travel_log',
        label: 'Travel Log',
        description: 'Adds place, distance, media, and trip context.',
        implementation: 'schema-extension',
        presentation: 'map',
        icon: MapPinned,
        accent: '#a372e4',
      },
    ],
  },
  line_chart: {
    type: 'line_chart',
    label: 'Line Chart',
    description: 'Plot an editable trend with latest, average, and maximum outputs',
    icon: ChartLine,
    category: 'data',
    accent: '#38bdf8',
    restingFace: true,
    defaultSize: { width: 400, height: C * 6 },
    defaultData: () => ({
      title: 'Trend',
      unit: '',
      points: [
        { id: uid(), label: 'A', value: 3 },
        { id: uid(), label: 'B', value: 5 },
        { id: uid(), label: 'C', value: 4 },
      ],
    }),
  },
  pie_chart: {
    type: 'pie_chart',
    label: 'Donut Chart',
    description: 'A lightweight share breakdown with editable colors and values',
    icon: ChartPie,
    category: 'data',
    accent: '#f472b6',
    restingFace: true,
    defaultSize: { width: 360, height: C * 7 },
    defaultData: () => ({
      title: 'Breakdown',
      mode: 'donut',
      segments: [
        { id: uid(), label: 'A', value: 60, color: '#38bdf8' },
        { id: uid(), label: 'B', value: 40, color: '#a3e635' },
      ],
    }),
  },
  unit_converter: {
    type: 'unit_converter',
    label: 'Unit Converter',
    description: 'Fast local conversions for length, mass, temperature, and time',
    icon: ArrowLeftRight,
    category: 'data',
    accent: '#34d399',
    restingFace: true,
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      skin: 'general',
      category: 'length',
      value: 1,
      from: 'm',
      to: 'ft',
      precision: 2,
    }),
    skinField: 'skin',
    rendererOwnedSkinDetails: ['currency', 'custom_formula'],
    skins: [
      {
        value: 'general',
        label: 'General',
        description: 'Everyday length, weight, temperature, and duration conversions.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Sparkles,
        accent: '#a7e472',
      },
      {
        value: 'cooking',
        label: 'Cooking',
        description: 'Cups, spoons, weight, temperature, and kitchen-friendly units.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: ChefHat,
        accent: '#e472e2',
      },
      {
        value: 'engineering',
        label: 'Engineering',
        description: 'Length, area, volume, pressure, energy, and power.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Ruler,
        accent: '#c9e472',
      },
      {
        value: 'data',
        label: 'Data',
        description: 'Bits, bytes, transfer sizes, and decimal or binary prefixes.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Binary,
        accent: '#72d1e4',
      },
      {
        value: 'temperature',
        label: 'Temperature',
        description: 'A focused Celsius, Fahrenheit, and Kelvin surface.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: ThermometerSun,
        accent: '#e4b272',
      },
      {
        value: 'currency',
        label: 'Currency',
        description: 'A clearly dated manual exchange rate without a network dependency.',
        implementation: 'schema-extension',
        presentation: 'standard',
        icon: CircleDollarSign,
        accent: '#72c6e4',
      },
      {
        value: 'custom_formula',
        label: 'Custom Formula',
        description: 'A bounded factor and offset conversion with your own unit names.',
        implementation: 'schema-extension',
        presentation: 'form',
        icon: SquareFunction,
        accent: '#72e4e0',
      },
    ],
  },
  game_tuner: {
    type: 'game_tuner',
    label: 'Game Mechanics Tuner',
    description: 'Sliders for tuning game feel',
    icon: Gamepad2,
    category: 'specialist',
    accent: '#c4b5fd',
    defaultSize: { width: 320, height: C * 4 },
    defaultData: () => ({ grip: 50, drift: 20, stability: 80 }),
    pack: 'game_dev',
  },
  audio_player: {
    type: 'audio_player',
    label: 'Synthesizer & Audio Player',
    description: 'BPM, key, and signal chain scratchpad',
    icon: AudioLines,
    category: 'specialist',
    accent: '#7dd3fc',
    defaultSize: { width: 360, height: C * 8 },
    sizing: { minWidth: 320, minHeight: C * 8, maxWidth: 640, maxHeight: C * 8, autoHeight: true },
    defaultData: () => ({
      bpm: 120,
      key: 'C Minor',
      signalChain: 'Chorus -> Delay -> Reverb',
      isPlaying: false,
    }),
    pack: 'music_production',
  },
} satisfies Record<string, WidgetDefinition>
