import {
  ArrowLeftRight,
  AudioLines,
  BookMarked,
  CalendarRange,
  ChartLine,
  ChartPie,
  ClipboardList,
  Columns3,
  Gamepad2,
  Grid2x2,
  List,
  Package,
  ShieldAlert,
  Timer,
  Workflow,
} from 'lucide-react'
import type { WidgetDefinition } from '../contracts/registry'
import { C, uid, todayISO } from './definitionHelpers'

/** Professional, ops, and specialist widgets (outline … audio_player). Extracted verbatim from registry.ts; key order preserved. */
export const PROFESSIONAL_WIDGET_DEFINITIONS = {
  outline: {
    type: 'outline',
    label: 'Outline',
    description: 'A keyboard-friendly nested outline for structuring ideas',
    icon: List,
    category: 'notes',
    accent: '#60a5fa',
    restingFace: true,
    defaultSize: { width: 360, height: C * 6 },
    defaultData: () => ({
      items: [{ id: uid(), text: 'First idea', depth: 0, collapsed: false }],
    }),
  },
  form: {
    type: 'form',
    label: 'Form',
    description: 'Build and complete a compact form with required-field tracking',
    icon: ClipboardList,
    category: 'data',
    accent: '#2dd4bf',
    restingFace: true,
    defaultSize: { width: 400, height: C * 7 },
    defaultData: () => ({
      title: 'Quick form',
      fields: [{ id: uid(), label: 'Name', type: 'text', value: '', required: true }],
    }),
  },
  daily_agenda: {
    type: 'daily_agenda',
    label: 'Daily Agenda',
    description: 'A focused schedule of timed, completable items for one day',
    icon: CalendarRange,
    category: 'planning',
    accent: '#7dd3fc',
    restingFace: true,
    defaultSize: { width: 360, height: C * 7 },
    defaultData: () => ({
      date: todayISO(),
      items: [{ id: uid(), time: '09:00', title: 'First item', done: false }],
    }),
  },
  process: {
    type: 'process',
    label: 'Process / SOP',
    description: 'A sequential procedure with one active step and live progress',
    icon: Workflow,
    category: 'planning',
    accent: '#a3e635',
    restingFace: true,
    defaultSize: { width: 360, height: C * 6 },
    defaultData: () => ({
      steps: [{ id: uid(), label: 'First step', status: 'active' }],
    }),
  },
  risk_register: {
    type: 'risk_register',
    label: 'Risk Register',
    description: 'Score likelihood and impact, record mitigation, resolve risks',
    icon: ShieldAlert,
    category: 'planning',
    accent: '#fb7185',
    restingFace: true,
    defaultSize: { width: 440, height: C * 6 },
    defaultData: () => ({
      items: [
        {
          id: uid(),
          risk: 'New risk',
          likelihood: 2,
          impact: 2,
          mitigation: '',
          status: 'open',
        },
      ],
    }),
  },
  decision_matrix: {
    type: 'decision_matrix',
    label: 'Decision Matrix',
    description: 'Compare options against weighted criteria and reveal a winner',
    icon: Grid2x2,
    category: 'planning',
    accent: '#c084fc',
    restingFace: true,
    defaultSize: { width: 440, height: C * 6 },
    defaultData: () => ({
      criteria: [{ id: uid(), label: 'Value', weight: 1 }],
      options: [
        { id: uid(), label: 'Option A', scores: [3] },
        { id: uid(), label: 'Option B', scores: [3] },
      ],
    }),
  },
  swot: {
    type: 'swot',
    label: 'SWOT Analysis',
    description: 'Strengths, weaknesses, opportunities, and threats in one view',
    icon: Columns3,
    category: 'planning',
    accent: '#f59e0b',
    restingFace: true,
    defaultSize: { width: 400, height: C * 6 },
    defaultData: () => ({ strengths: [''], weaknesses: [''], opportunities: [''], threats: [''] }),
  },
  timesheet: {
    type: 'timesheet',
    label: 'Timesheet',
    description: 'Log hours, mark billable work, and calculate live totals',
    icon: Timer,
    category: 'tracking',
    accent: '#22d3ee',
    restingFace: true,
    defaultSize: { width: 400, height: C * 6 },
    defaultData: () => ({
      currency: '$',
      hourlyRate: 0,
      entries: [{ id: uid(), date: todayISO(), label: 'Work', hours: 1, billable: true }],
    }),
  },
  inventory: {
    type: 'inventory',
    label: 'Inventory',
    description: 'Track quantities and immediately surface low-stock items',
    icon: Package,
    category: 'tracking',
    accent: '#facc15',
    restingFace: true,
    defaultSize: { width: 400, height: C * 6 },
    defaultData: () => ({
      items: [{ id: uid(), name: 'Item', quantity: 1, minimum: 0, unit: 'pcs' }],
    }),
  },
  logbook: {
    type: 'logbook',
    label: 'Logbook',
    description: 'A chronological record of timestamped notes and warnings',
    icon: BookMarked,
    category: 'notes',
    accent: '#94a3b8',
    restingFace: true,
    defaultSize: { width: 360, height: C * 6 },
    defaultData: () => ({
      entries: [{ id: uid(), timestamp: new Date().toISOString(), text: 'First entry', level: 'note' }],
    }),
  },
  line_chart: {
    type: 'line_chart',
    label: 'Line Chart',
    description: 'Plot an editable trend with latest, average, and maximum outputs',
    icon: ChartLine,
    category: 'data',
    accent: '#38bdf8',
    restingFace: true,
    defaultSize: { width: 400, height: C * 6 },
    defaultData: () => ({
      title: 'Trend',
      unit: '',
      points: [
        { id: uid(), label: 'A', value: 3 },
        { id: uid(), label: 'B', value: 5 },
        { id: uid(), label: 'C', value: 4 },
      ],
    }),
  },
  pie_chart: {
    type: 'pie_chart',
    label: 'Donut Chart',
    description: 'A lightweight share breakdown with editable colors and values',
    icon: ChartPie,
    category: 'data',
    accent: '#f472b6',
    restingFace: true,
    defaultSize: { width: 360, height: C * 7 },
    defaultData: () => ({
      title: 'Breakdown',
      mode: 'donut',
      segments: [
        { id: uid(), label: 'A', value: 60, color: '#38bdf8' },
        { id: uid(), label: 'B', value: 40, color: '#a3e635' },
      ],
    }),
  },
  unit_converter: {
    type: 'unit_converter',
    label: 'Unit Converter',
    description: 'Fast local conversions for length, mass, temperature, and time',
    icon: ArrowLeftRight,
    category: 'data',
    accent: '#34d399',
    restingFace: true,
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({ category: 'length', value: 1, from: 'm', to: 'ft', precision: 2 }),
  },
  game_tuner: {
    type: 'game_tuner',
    label: 'Game Mechanics Tuner',
    description: 'Sliders for tuning game feel',
    icon: Gamepad2,
    category: 'specialist',
    accent: '#c4b5fd',
    defaultSize: { width: 320, height: C * 4 },
    defaultData: () => ({ grip: 50, drift: 20, stability: 80 }),
    pack: 'game_dev',
  },
  audio_player: {
    type: 'audio_player',
    label: 'Synthesizer & Audio Player',
    description: 'BPM, key, and signal chain scratchpad',
    icon: AudioLines,
    category: 'specialist',
    accent: '#7dd3fc',
    defaultSize: { width: 360, height: C * 8 },
    sizing: { minWidth: 320, minHeight: C * 8, maxWidth: 640, maxHeight: C * 8, autoHeight: true },
    defaultData: () => ({
      bpm: 120,
      key: 'C Minor',
      signalChain: 'Chorus -> Delay -> Reverb',
      isPlaying: false,
    }),
    pack: 'music_production',
  },
} satisfies Record<string, WidgetDefinition>
