import {
  BookOpen,
  CalendarClock,
  Code2,
  FileText,
  FolderOpen,
  History,
  ArrowLeftRight,
  Circle,
  Focus,
  List,
  ListTree,
  MemoryStick,
  MessageSquareWarning,
  PenLine,
  Quote,
  Rows3,
  StickyNote,
  Table2,
} from 'lucide-react'
import type { WidgetDefinition } from '../contracts/registry'
import { C } from './definitionHelpers'

/** Structure and notes widgets (canvas_node … sticky_note). Extracted verbatim from registry.ts; key order preserved. */
export const STRUCTURE_NOTES_WIDGET_DEFINITIONS = {
  canvas_node: {
    type: 'canvas_node',
    label: 'Canvas',
    description: 'A whole board inside a card — click its name to enter it',
    icon: FolderOpen,
    category: 'structure',
    accent: '#a3e635',
    defaultSize: { width: 280, height: C * 2 },
    sizing: { minWidth: C * 5, minHeight: C * 2, autoHeight: true },
    // canvasId is assigned by the store when the backing canvas is created.
    defaultData: () => ({ canvasId: '', skin: 'portal' }),
    rendererOwnedSkinDetails: ['live_thumbnail', 'dashboard_door', 'folder_index'],
  },
  notes: {
    type: 'notes',
    label: 'Note',
    description: 'Plain, sticky, and quote skins in one writing card',
    icon: FileText,
    category: 'notes',
    accent: '#e2e8f0',
    defaultSize: { width: 320, height: C * 5 },
    sizing: { minWidth: C * 4, autoHeight: true },
    defaultData: () => ({ text: '', mode: 'plain', color: 'yellow', attribution: '' }),
    rendererOwnedSkinDetails: ['versioned_note'],
    // Every Note skin is declared here so it wears an icon that says what it
    // is. The catalogue merge only fills gaps, and its generated entries fall
    // back to one icon per presentation family — which put a bar chart on
    // Markdown, a checklist on Typewriter, and a grid on Version History.
    // The rest of each generated entry is repeated verbatim.
    skins: [
      { value: 'plain', label: 'Plain', icon: FileText, accent: '#e2e8f0' },
      { value: 'sticky', label: 'Sticky', icon: StickyNote, accent: '#fcd34d' },
      { value: 'quote', label: 'Quote', icon: Quote, accent: '#c4b5fd' },
      {
        value: 'daily_log',
        label: 'Daily Log',
        description: 'Timestamped journal styling optimized for short dated entries.',
        implementation: 'renderer-ready',
        presentation: 'time',
        icon: CalendarClock,
        accent: '#e4a772',
      },
      {
        value: 'markdown_page',
        label: 'Markdown Page',
        description: 'Reading-first typography with headings, code, lists, and links.',
        implementation: 'renderer-ready',
        presentation: 'chart',
        icon: BookOpen,
        accent: '#729ce4',
      },
      {
        value: 'typewriter',
        label: 'Typewriter',
        description:
          'Distraction-free long-form writing with a narrow measure and current-line focus.',
        implementation: 'renderer-ready',
        presentation: 'form',
        icon: PenLine,
        accent: '#72cfe4',
      },
      {
        value: 'callout',
        label: 'Callout',
        description: 'A concise warning, tip, decision, or important-fact treatment.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: MessageSquareWarning,
        accent: '#e47572',
      },
      {
        value: 'versioned_note',
        label: 'Versioned Note',
        description:
          'Keeps named snapshots and compares the current text with an earlier version.',
        implementation: 'schema-extension',
        presentation: 'matrix',
        icon: History,
        accent: '#729ce4',
      },
    ],
  },
  bullets: {
    type: 'bullets',
    label: 'Bullets',
    description: 'Quick unordered list of short points',
    icon: List,
    category: 'notes',
    accent: '#93c5fd',
    // Bullets are a column of points and nothing else — the card is exactly
    // its list, so there is no edge worth dragging.
    defaultSize: { width: C * 6, height: C * 3 },
    sizing: { minWidth: C * 5, autoHeight: true, fixed: true },
    defaultData: () => ({
      items: [{ id: crypto.randomUUID(), text: 'First point' }],
      skin: 'dots',
    }),
    rendererOwnedSkinDetails: ['nested_outline', 'rolling_log'],
  },
  linked_list: {
    type: 'linked_list',
    label: 'Linked List',
    description: 'An ordered chain of stable nodes with traversable head, tail, and current value',
    icon: ListTree,
    category: 'structure',
    accent: '#67e8f9',
    restingFace: true,
    defaultSize: { width: C * 9, height: C * 6 },
    sizing: { minWidth: C * 6, minHeight: C * 4 },
    defaultData: () => ({
      nodes: [
        { id: crypto.randomUUID(), value: 'Head' },
        { id: crypto.randomUUID(), value: 'Middle' },
        { id: crypto.randomUUID(), value: 'Tail' },
      ],
      selectedId: null,
      skin: 'chain',
    }),
    skinField: 'skin',
    skins: [
      {
        value: 'chain',
        label: 'Chain',
        description: 'A classic head-to-tail row with one directional pointer between nodes.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: ListTree,
        accent: '#67e8f9',
      },
      {
        value: 'vertical',
        label: 'Vertical Rail',
        description: 'A tall reorderable sequence for longer values and narrow cards.',
        implementation: 'renderer-ready',
        presentation: 'steps',
        icon: Rows3,
        accent: '#a7f3d0',
      },
      {
        value: 'compact',
        label: 'Compact Index',
        description: 'A dense numbered ledger with explicit next-node references.',
        implementation: 'renderer-ready',
        presentation: 'ledger',
        icon: Table2,
        accent: '#93c5fd',
      },
      {
        value: 'focus',
        label: 'Focus Navigator',
        description: 'Shows one current node with previous and next navigation.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: Focus,
        accent: '#c4b5fd',
      },
      {
        value: 'doubly_linked',
        label: 'Doubly Linked',
        description: 'Shows both previous and next pointers around every node.',
        implementation: 'renderer-ready',
        presentation: 'standard',
        icon: ArrowLeftRight,
        accent: '#f9a8d4',
      },
      {
        value: 'circular',
        label: 'Circular',
        description: 'Reconnects the tail to the head and wraps traversal forever.',
        implementation: 'renderer-ready',
        presentation: 'map',
        icon: Circle,
        accent: '#fcd34d',
      },
      {
        value: 'memory_map',
        label: 'Memory Map',
        description: 'A pointer table with stable pseudo-addresses for technical reasoning.',
        implementation: 'renderer-ready',
        presentation: 'terminal',
        icon: MemoryStick,
        accent: '#86efac',
      },
    ],
  },
  quote: {
    type: 'quote',
    label: 'Quote',
    description: 'A pull-quote or callout with attribution',
    icon: Quote,
    category: 'notes',
    accent: '#fbcfe8',
    defaultSize: { width: 320, height: C * 4 },
    defaultData: () => ({ text: 'The canvas stretches on, in every direction.', attribution: '' }),
  },
  code: {
    type: 'code',
    label: 'Code Snippet',
    description: 'Monospace code block with a language tag',
    icon: Code2,
    category: 'notes',
    accent: '#7dd3fc',
    defaultSize: { width: 360, height: C * 5 },
    defaultData: () => ({ language: 'ts', code: '' }),
  },
  sticky_note: {
    type: 'sticky_note',
    label: 'Sticky Note',
    description: 'A quick colored note — pick a hue, jot it down',
    icon: StickyNote,
    category: 'notes',
    accent: '#fde047',
    defaultSize: { width: 260, height: C * 4 },
    sizing: { minWidth: C * 4, autoHeight: true },
    defaultData: () => ({ text: '', color: 'yellow' }),
  },
} satisfies Record<string, WidgetDefinition>
