import {
  BookMarked,
  BookOpen,
  BrainCircuit,
  Calculator,
  ClipboardList,
  FunctionSquare,
  Globe,
  Goal,
  GraduationCap,
  Hourglass,
  Languages,
  Layers,
  NotebookPen,
  Target,
  TimerReset,
} from 'lucide-react'
import type { WidgetDefinition } from '../contracts/registry'
import { C, uid } from './definitionHelpers'

/** Study and learning widgets (flashcards … quiz). Extracted verbatim from registry.ts; key order preserved. */
export const STUDY_WIDGET_DEFINITIONS = {
  flashcards: {
    type: 'flashcards',
    label: 'Flashcards',
    description: 'A study deck — click the card to flip it',
    icon: Layers,
    category: 'notes',
    accent: '#c4b5fd',
    defaultSize: { width: 300, height: C * 5 },
    defaultData: () => ({
      cards: [{ id: uid(), front: '', back: '' }],
      current: 0,
    }),
  },
  goal_tracker: {
    type: 'goal_tracker',
    label: 'Goal Tracker',
    description: 'One goal, its milestones, and live progress',
    icon: Goal,
    category: 'tracking',
    accent: '#86efac',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      goal: '',
      milestones: [{ id: uid(), label: '', done: false }],
    }),
  },
  stopwatch: {
    type: 'stopwatch',
    label: 'Stopwatch',
    description: 'Elapsed time with laps',
    icon: Hourglass,
    category: 'tracking',
    accent: '#fde047',
    defaultSize: { width: 240, height: C * 4 },
    defaultData: () => ({ elapsedMs: 0, startedAt: null, laps: [] }),
    availability: 'existing-only',
    unavailableReason: 'Stopwatch now lives inside the Timer widget.',
  },
  reading_list: {
    type: 'reading_list',
    label: 'Reading List',
    description: 'Books & articles with queued/reading/done states',
    icon: BookOpen,
    category: 'tracking',
    accent: '#fdba74',
    defaultSize: { width: 320, height: C * 4 },
    defaultData: () => ({
      title: 'Chart',
      items: [{ id: uid(), title: '', status: 'queued' }],
    }),
  },
  world_clock: {
    type: 'world_clock',
    label: 'World Clock',
    description: 'Local time in the cities you care about',
    icon: Globe,
    category: 'data',
    accent: '#67e8f9',
    defaultSize: { width: 280, height: C * 4 },
    defaultData: () => ({ zones: ['America/New_York', 'Europe/London', 'Asia/Tokyo'] }),
  },
  pomodoro: {
    type: 'pomodoro',
    label: 'Pomodoro Timer',
    description: 'Work/break focus cycles with a session counter',
    icon: TimerReset,
    category: 'study',
    accent: '#fb7185',
    defaultSize: { width: 260, height: C * 5 },
    defaultData: () => ({
      label: 'Focus',
      workMinutes: 25,
      breakMinutes: 5,
      phase: 'work',
      endAt: null,
      remainingSeconds: 25 * 60,
      completed: 0,
    }),
    availability: 'existing-only',
    unavailableReason: 'Pomodoro now lives inside the Timer widget.',
  },
  vocab: {
    type: 'vocab',
    label: 'Vocabulary',
    description: 'Term & definition list with known toggles',
    icon: Languages,
    category: 'study',
    accent: '#c4b5fd',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      terms: [{ id: uid(), term: '', definition: '', known: false }],
    }),
  },
  grade_calc: {
    type: 'grade_calc',
    label: 'Grade Calculator',
    description: 'Weighted components → your live course grade',
    icon: Calculator,
    category: 'study',
    accent: '#5eead4',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      components: [
        { id: uid(), name: 'Exams', score: 0, weight: 50 },
        { id: uid(), name: 'Homework', score: 0, weight: 50 },
      ],
    }),
  },
  gpa: {
    type: 'gpa',
    label: 'GPA Tracker',
    description: 'Courses & credits → your computed GPA',
    icon: GraduationCap,
    category: 'study',
    accent: '#93c5fd',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      courses: [{ id: uid(), name: '', credits: 3, points: 4 }],
    }),
  },
  assignment: {
    type: 'assignment',
    label: 'Assignments',
    description: 'Homework tracker with due dates and status',
    icon: ClipboardList,
    category: 'study',
    accent: '#fca5a5',
    defaultSize: { width: 340, height: C * 5 },
    defaultData: () => ({
      items: [{ id: uid(), title: '', due: '', status: 'todo' }],
    }),
  },
  cornell: {
    type: 'cornell',
    label: 'Cornell Notes',
    description: 'Cue column, notes, and a summary band',
    icon: NotebookPen,
    category: 'study',
    accent: '#fcd34d',
    defaultSize: { width: 360, height: C * 6 },
    defaultData: () => ({ cues: '', notes: '', summary: '' }),
  },
  formula_sheet: {
    type: 'formula_sheet',
    label: 'Formula Sheet',
    description: 'A quick-reference list of named formulas',
    icon: FunctionSquare,
    category: 'study',
    accent: '#a5b4fc',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      formulas: [{ id: uid(), name: '', expression: '' }],
    }),
  },
  citation: {
    type: 'citation',
    label: 'Citations',
    description: 'Source manager with an APA/MLA/Chicago toggle',
    icon: BookMarked,
    category: 'study',
    accent: '#d8b4fe',
    defaultSize: { width: 340, height: C * 5 },
    defaultData: () => ({
      style: 'APA',
      sources: [{ id: uid(), title: '', author: '', year: '' }],
    }),
  },
  study_goal: {
    type: 'study_goal',
    label: 'Study Goal',
    description: 'Logged vs target study hours with live progress',
    icon: Target,
    category: 'study',
    accent: '#86efac',
    defaultSize: { width: 300, height: C * 4 },
    defaultData: () => ({ subject: '', targetHours: 10, loggedHours: 0 }),
  },
  quiz: {
    type: 'quiz',
    label: 'Quiz',
    description: 'A self-check question — pick, then reveal the answer',
    icon: BrainCircuit,
    category: 'study',
    accent: '#f9a8d4',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      prompt: '',
      options: [
        { id: uid(), text: '', correct: true },
        { id: uid(), text: '', correct: false },
      ],
      picked: null,
    }),
  },
} satisfies Record<string, WidgetDefinition>
