import {
  AlignHorizontalDistributeCenter,
  BadgeCheck,
  BookMarked,
  BookOpen,
  BrainCircuit,
  Calculator,
  CalendarClock,
  ChartSpline,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  FlaskConical,
  FunctionSquare,
  Globe,
  Goal,
  LayoutGrid,
  PlaneTakeoff,
  Sunrise,
  GraduationCap,
  Hourglass,
  Languages,
  Layers,
  ListMinus,
  NotebookPen,
  Target,
  TimerReset,
} from 'lucide-react'
import type { WidgetDefinition } from '../contracts/registry'
import { C, uid } from './definitionHelpers'

/** Study and learning widgets (flashcards … quiz). Extracted verbatim from registry.ts; key order preserved. */
export const STUDY_WIDGET_DEFINITIONS = {
  flashcards: {
    type: 'flashcards',
    label: 'Study Deck',
    description: 'Flashcard, vocabulary, and self-quiz skins',
    icon: Layers,
    category: 'notes',
    accent: '#c4b5fd',
    defaultSize: { width: 360, height: C * 6 },
    defaultData: () => ({
      cards: [{ id: uid(), front: '', back: '' }],
      current: 0,
      mode: 'flashcards',
      vocabulary: { terms: [{ id: uid(), term: '', definition: '', known: false }] },
      quiz: { prompt: '', options: [{ id: uid(), text: '', correct: true }, { id: uid(), text: '', correct: false }], picked: null },
    }),
    skins: [
      { value: 'flashcards', label: 'Flashcards', icon: Layers, accent: '#c4b5fd' },
      { value: 'vocabulary', label: 'Vocabulary', icon: Languages, accent: '#38bdf8' },
      { value: 'quiz', label: 'Quiz', icon: BrainCircuit, accent: '#f472b6' },
    ],
  },
  canvas_lms: {
    type: 'canvas_lms',
    label: 'College Canvas',
    description: 'Private Canvas LMS dashboard for courses, work, grades, and news',
    icon: GraduationCap,
    category: 'study',
    accent: '#e45b52',
    defaultSize: { width: 380, height: C * 7 },
    defaultData: () => ({ skin: 'overview' }),
    skinField: 'skin',
    skins: [
      {
        value: 'overview',
        label: 'Overview',
        icon: LayoutGrid,
        accent: '#e45b52',
        description: 'A compact snapshot of courses and upcoming work.',
        presentation: 'dashboard',
        implementation: 'renderer-ready',
      },
      {
        value: 'courses',
        label: 'Courses',
        icon: BookOpen,
        accent: '#7baee4',
        description: 'Active classes, terms, and course links.',
        presentation: 'grid',
        implementation: 'renderer-ready',
      },
      {
        value: 'assignments',
        label: 'Assignments',
        icon: ClipboardList,
        accent: '#e4b672',
        description: 'Upcoming Canvas work ordered by due date.',
        presentation: 'timeline',
        implementation: 'renderer-ready',
      },
      {
        value: 'grades',
        label: 'Grades',
        icon: Calculator,
        accent: '#72c995',
        description: 'Current grades reported by each course.',
        presentation: 'ledger',
        implementation: 'renderer-ready',
      },
      {
        value: 'announcements',
        label: 'Announcements',
        icon: NotebookPen,
        accent: '#b58be4',
        description: 'Recent instructor announcements across courses.',
        presentation: 'cards',
        implementation: 'renderer-ready',
      },
    ],
  },
  goal_tracker: {
    type: 'goal_tracker',
    label: 'Goal',
    description: 'Simple progress, milestones, study hours, and OKR skins',
    icon: Goal,
    category: 'tracking',
    accent: '#86efac',
    defaultSize: { width: 360, height: C * 7 },
    defaultData: () => ({
      goal: '',
      milestones: [{ id: uid(), label: '', done: false }],
      mode: 'milestones',
      simple: { label: 'Progress', percent: 40 },
      hours: { subject: '', targetHours: 10, loggedHours: 0 },
      okr: { objective: 'Meaningful objective', keyResults: [{ id: uid(), label: 'Key result', current: 0, target: 100, weight: 1 }] },
    }),
    skins: [
      { value: 'simple', label: 'Simple', icon: Target, accent: '#86efac' },
      { value: 'milestones', label: 'Milestones', icon: Goal, accent: '#fbbf24' },
      { value: 'hours', label: 'Study Hours', icon: Hourglass, accent: '#38bdf8' },
      { value: 'okr', label: 'OKR', icon: Target, accent: '#f472b6' },
    ],
  },
  stopwatch: {
    type: 'stopwatch',
    label: 'Stopwatch',
    description: 'Elapsed time with laps',
    icon: Hourglass,
    category: 'tracking',
    accent: '#fde047',
    defaultSize: { width: 240, height: C * 4 },
    defaultData: () => ({ elapsedMs: 0, startedAt: null, laps: [] }),
  },
  reading_list: {
    type: 'reading_list',
    label: 'Reading List',
    description: 'Books & articles with queued/reading/done states',
    icon: BookOpen,
    category: 'tracking',
    accent: '#fdba74',
    defaultSize: { width: 320, height: C * 4 },
    defaultData: () => ({
      title: 'Chart',
      items: [{ id: uid(), title: '', status: 'queued' }],
    }),
  },
  world_clock: {
    type: 'world_clock',
    label: 'World Clock',
    description: 'Local time in the cities you care about',
    icon: Globe,
    category: 'data',
    accent: '#67e8f9',
    // Overlap Band and Meeting Planner lay 24 columns beside a city label, so
    // the card starts wider than a plain list of readings would need.
    defaultSize: { width: 360, height: C * 5 },
    defaultData: () => ({
      zones: ['America/New_York', 'Europe/London', 'Asia/Tokyo'],
      skin: 'city_grid',
    }),
    skinField: 'skin',
    // Only Travel Clock keeps anything of its own — the home/destination
    // pairing. The rest re-read the stored zone list, so their controls stay
    // session-local and the saved card holds nothing but cities.
    rendererOwnedSkinDetails: ['travel_clock', 'sunlight'],
    // Metadata mirrors the generated catalogue exactly; only the icon is ours.
    skins: [
      { value: 'city_grid', label: 'City Grid', description: 'Large digital times arranged by city.', implementation: 'renderer-ready', presentation: 'grid', icon: LayoutGrid, accent: '#e4a772' },
      { value: 'analog_wall', label: 'Analog Wall', description: 'A wall-clock presentation for rapid daylight recognition.', implementation: 'renderer-ready', presentation: 'grid', icon: Clock3, accent: '#e4a772' },
      { value: 'overlap_band', label: 'Overlap Band', description: 'Highlights the shared working hours across selected zones.', implementation: 'renderer-ready', presentation: 'standard', icon: AlignHorizontalDistributeCenter, accent: '#e472cd' },
      { value: 'meeting_planner', label: 'Meeting Planner', description: 'Scrubs one local time and shows its equivalent everywhere.', implementation: 'renderer-ready', presentation: 'standard', icon: CalendarClock, accent: '#e4a772' },
      { value: 'travel_clock', label: 'Travel Clock', description: 'Adds origin, destination, departure, and adaptation guidance.', implementation: 'schema-extension', presentation: 'map', icon: PlaneTakeoff, accent: '#e4a772' },
      { value: 'sunlight', label: 'Sunlight', description: 'Adds sunrise, sunset, and local daylight state for every city.', implementation: 'schema-extension', presentation: 'standard', icon: Sunrise, accent: '#d572e4' },
    ],
  },
  pomodoro: {
    type: 'pomodoro',
    label: 'Pomodoro Timer',
    description: 'Work/break focus cycles with a session counter',
    icon: TimerReset,
    category: 'study',
    accent: '#fb7185',
    defaultSize: { width: 260, height: C * 5 },
    defaultData: () => ({
      label: 'Focus',
      workMinutes: 25,
      breakMinutes: 5,
      phase: 'work',
      endAt: null,
      remainingSeconds: 25 * 60,
      completed: 0,
    }),
  },
  vocab: {
    type: 'vocab',
    label: 'Vocabulary',
    description: 'Term & definition list with known toggles',
    icon: Languages,
    category: 'study',
    accent: '#c4b5fd',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      terms: [{ id: uid(), term: '', definition: '', known: false }],
    }),
  },
  grade_calc: {
    type: 'grade_calc',
    label: 'Grades',
    description: 'Weighted course grade and GPA skins',
    icon: Calculator,
    category: 'study',
    accent: '#5eead4',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      components: [
        { id: uid(), name: 'Exams', score: 0, weight: 50 },
        { id: uid(), name: 'Homework', score: 0, weight: 50 },
      ],
      mode: 'weighted',
      gpa: { courses: [{ id: uid(), name: '', credits: 3, points: 4 }] },
    }),
    rendererOwnedSkinDetails: ['rubric', 'dropped_scores', 'curve_simulator'],
    skins: [
      {
        value: 'weighted',
        label: 'Weighted Grade',
        icon: Calculator,
        accent: '#5eead4',
        description: 'Balances coursework scores by their share of the final grade.',
        presentation: 'standard',
        implementation: 'renderer-ready',
      },
      {
        value: 'gpa',
        label: 'GPA',
        icon: GraduationCap,
        accent: '#a78bfa',
        description: 'Calculates cumulative grade points across course credits.',
        presentation: 'ledger',
        implementation: 'renderer-ready',
      },
      {
        value: 'pass_fail',
        label: 'Pass / Fail',
        icon: BadgeCheck,
        accent: '#72e479',
        description: 'Focuses on the margin above or below a required grade.',
        presentation: 'standard',
        implementation: 'renderer-ready',
      },
      {
        value: 'what_if',
        label: 'What-if',
        icon: FlaskConical,
        accent: '#e4cd72',
        description: 'Makes one hypothetical score prominent while preserving current marks.',
        presentation: 'dashboard',
        implementation: 'renderer-ready',
      },
      {
        value: 'rubric',
        label: 'Rubric',
        icon: ClipboardCheck,
        accent: '#e4cd72',
        description: 'Scores criteria separately and computes a weighted result.',
        presentation: 'matrix',
        implementation: 'schema-extension',
      },
      {
        value: 'dropped_scores',
        label: 'Dropped Scores',
        icon: ListMinus,
        accent: '#e4cd72',
        description: 'Previews a result after excluding the lowest scores.',
        presentation: 'dashboard',
        implementation: 'schema-extension',
      },
      {
        value: 'curve_simulator',
        label: 'Curve Simulator',
        icon: ChartSpline,
        accent: '#e47d72',
        description: 'Compares raw and curved grade scenarios.',
        presentation: 'chart',
        implementation: 'schema-extension',
      },
    ],
  },
  gpa: {
    type: 'gpa',
    label: 'GPA Tracker',
    description: 'Courses & credits → your computed GPA',
    icon: GraduationCap,
    category: 'study',
    accent: '#93c5fd',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      courses: [{ id: uid(), name: '', credits: 3, points: 4 }],
    }),
  },
  assignment: {
    type: 'assignment',
    label: 'Assignments',
    description: 'Homework tracker with due dates and status',
    icon: ClipboardList,
    category: 'study',
    accent: '#fca5a5',
    defaultSize: { width: 340, height: C * 5 },
    defaultData: () => ({
      items: [{ id: uid(), title: '', due: '', status: 'todo' }],
    }),
  },
  cornell: {
    type: 'cornell',
    label: 'Cornell Notes',
    description: 'Cue column, notes, and a summary band',
    icon: NotebookPen,
    category: 'study',
    accent: '#fcd34d',
    defaultSize: { width: 360, height: C * 6 },
    defaultData: () => ({ cues: '', notes: '', summary: '' }),
  },
  formula_sheet: {
    type: 'formula_sheet',
    label: 'Formula Sheet',
    description: 'A quick-reference list of named formulas',
    icon: FunctionSquare,
    category: 'study',
    accent: '#a5b4fc',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      formulas: [{ id: uid(), name: '', expression: '' }],
    }),
  },
  citation: {
    type: 'citation',
    label: 'Citations',
    description: 'Source manager with an APA/MLA/Chicago toggle',
    icon: BookMarked,
    category: 'study',
    accent: '#d8b4fe',
    defaultSize: { width: 340, height: C * 5 },
    defaultData: () => ({
      style: 'APA',
      sources: [{ id: uid(), title: '', author: '', year: '' }],
    }),
  },
  study_goal: {
    type: 'study_goal',
    label: 'Study Goal',
    description: 'Logged vs target study hours with live progress',
    icon: Target,
    category: 'study',
    accent: '#86efac',
    defaultSize: { width: 300, height: C * 4 },
    defaultData: () => ({ subject: '', targetHours: 10, loggedHours: 0 }),
  },
  quiz: {
    type: 'quiz',
    label: 'Quiz',
    description: 'A self-check question — pick, then reveal the answer',
    icon: BrainCircuit,
    category: 'study',
    accent: '#f9a8d4',
    defaultSize: { width: 320, height: C * 5 },
    defaultData: () => ({
      prompt: '',
      options: [
        { id: uid(), text: '', correct: true },
        { id: uid(), text: '', correct: false },
      ],
      picked: null,
    }),
  },
} satisfies Record<string, WidgetDefinition>
