import type { ModuleType } from './moduleTypes'

export const MODULE_LABELS: Record<ModuleType, string> = {
  notes: 'Note',
  bullets: 'Bullets',
  checklist: 'Tasks',
  table: 'Table',
  sketchpad: 'Drawing',
  excalidraw: 'Excalidraw',
  budget: 'Budget',
  progress: 'Progress',
  ai_generator: 'AI Generator',
  timeline: 'Timeline',
  dialog: 'Dialog',
  game_tuner: 'Game Mechanics Tuner',
  audio_player: 'Synthesizer & Audio Player',
  canvas_node: 'Canvas',
  kanban: 'Kanban',
  countdown: 'Countdown',
  habit: 'Habit Tracker',
  links: 'Link List',
  code: 'Code Snippet',
  quote: 'Quote',
  poll: 'Poll',
  contact: 'Contact Card',
  media: 'Media',
  metrics: 'Metrics',
  sticky_note: 'Sticky Note',
  calendar: 'Calendar',
  timer: 'Timer',
  timekeeper: 'Timer',
  tracker: 'Tracker',
  rating: 'Rating',
  color_palette: 'Color Palette',
  mood_tracker: 'Mood Tracker',
  calculator: 'Calculator',
  bar_chart: 'Chart',
  counter: 'Counter',
  pros_cons: 'Pros & Cons',
  weekly_planner: 'Week Planner',
  goal_tracker: 'Goal',
  stopwatch: 'Stopwatch',
  reading_list: 'Reading List',
  flashcards: 'Study Deck',
  meeting_notes: 'Meeting Notes',
  priority_matrix: 'Priority Matrix',
  decision: 'Decision Picker',
  world_clock: 'World Clock',
  pomodoro: 'Pomodoro Timer',
  vocab: 'Vocabulary',
  grade_calc: 'Grades',
  gpa: 'GPA Tracker',
  assignment: 'Assignments',
  cornell: 'Cornell Notes',
  formula_sheet: 'Formula Sheet',
  citation: 'Citations',
  study_goal: 'Study Goal',
  quiz: 'Quiz',
  text_input: 'Text Input',
  number_input: 'Number Input',
  toggle: 'Toggle',
  branch_gate: 'Bool Gate',
  formula: 'Formula',
  status: 'Status',
  date_picker: 'Date',
  outline: 'Outline',
  form: 'Form',
  daily_agenda: 'Daily Agenda',
  process: 'Process / SOP',
  risk_register: 'Risk Register',
  decision_matrix: 'Decision Matrix',
  swot: 'SWOT Analysis',
  timesheet: 'Timesheet',
  inventory: 'Inventory',
  logbook: 'Logbook',
  line_chart: 'Line Chart',
  pie_chart: 'Donut Chart',
  unit_converter: 'Unit Converter',
  clock_pulse: 'Schedule Pulse',
  comparator: 'Comparator',
  aggregator: 'Aggregator',
  range_mapper: 'Range Mapper',
  latch: 'Snapshot Latch',
  random_picker: 'Random Picker',
  sequencer: 'Sequencer',
  template: 'Text Composer',
  recorder: 'Recorder',
  notifier: 'Notifier',
  subscriptions: 'Subscriptions',
  debt_payoff: 'Debt Payoff',
  expense_split: 'Expense Split',
  invoices: 'Invoices',
  meal_planner: 'Meal Planner',
  recipe: 'Recipe',
  home_maintenance: 'Home Maintenance',
  chore_rotation: 'Chore Rotation',
  renewals_vault: 'Renewals Vault',
  medications: 'Medications',
  workout_plan: 'Workout Plan',
  job_applications: 'Job Applications',
  okr: 'OKRs',
  decision_journal: 'Decision Journal',
  weekly_review: 'Weekly Review',
  snippet_library: 'Snippet Library',
  keep_in_touch: 'Keep in Touch',
  gifts_occasions: 'Gifts & Occasions',
  trip_itinerary: 'Trip Itinerary',
  guest_list: 'Guest List',
  savings_circle:'Savings Circle', zakat:'Zakat & Giving', remittance_planner:'Remittance', price_book:'Price Book',
  utility_runway:'Utility Runway', fuel_log:'Fuel Log', side_income:'Income Streams', wishlist_saver:'Wishlist',
  vitals_log:'Vitals', cycle_tracker:'Cycle', fasting_window:'Fasting', hydration:'Hydration', sleep_ledger:'Sleep Ledger', stretch_deck:'Stretch Deck',
  prayer_times:'Prayer Times', scripture_plan:'Scripture Plan', gratitude_jar:'Gratitude Jar', prayer_wall:'Prayer Wall',
  outage_schedule:'Power Schedule', borrowed_items:'Borrow Ledger', plant_care:'Plant Shelf', go_bag:'Go Bag', bin_night:'Bin Night', sun_window:'Sun Window', moving_boxes:'Moving Boxes',
  meeting_cost:'Meeting Meter', waiting_on:'Waiting On', office_hours:'Overlap Finder', scope_meter:'Scope Meter', handover_note:'Handover', crit_queue:'Crit Room', on_call:'On-Call', estimate_builder:'Estimate',
  past_papers:'Past Papers', memorization_ladder:'Memorization', experiments:'Experiments', mistake_bank:'Mistake Bank', skill_tree:'Skill Tree',
  care_plan:'Care Plan', gift_ledger:'Gift Ledger', team_kudos:'Applause Meter', potluck_matrix:'Potluck Board', star_chart:'Star Chart', pet_care:'Pet Card',
  visa_runway:'Visa Runway', packing_matrix:'Packing', jet_lag_shifter:'Jet Lag Plan', currency_pocket:'Cash Pockets', commission_queue:'Commission Queue', content_pipeline:'Content Pipeline',
  loop:'Loop', batch_processor:'Batch Processor', parallel_runner:'Parallel Runner', race:'Race', transaction:'Transaction', subroutine:'Subroutine', approval_gate:'Approval Gate', workflow_lock:'Workflow Lock',
  webhook_receiver:'Webhook Receiver', manual_trigger:'Manual Trigger', canvas_lifecycle:'Canvas Lifecycle', event_merger:'Event Merger', data_join:'Data Join', object_builder:'Object Builder', event_correlator:'Event Correlator', multi_source_aggregator:'Multi-Source Aggregator',
  widget_creator:'Widget Creator', widget_updater:'Widget Updater', widget_deleter:'Widget Deleter', branch_builder:'Branch Builder', relation_builder:'Relation Builder', canvas_router:'Canvas Router', clone_branch:'Clone Branch', template_instantiator:'Template Instantiator', archive_action:'Archive Action', auto_layout_action:'Auto Layout Action', focus_action:'Focus Action',
  variable_store:'Variable Store', key_value_store:'Key-Value Store', queue:'Queue', stack_store:'Stack', set_store:'Set Store', state_machine:'State Machine', idempotency_store:'Idempotency Store', session_store:'Session Store', mutex:'Mutex',
  script_block:'Script Block', local_function:'Local Function', http_request:'HTTP Request', webhook_sender:'Webhook Sender', secret_reference:'Secret Reference', environment_config:'Environment Config',
  automation_console:'Automation Console', test_data_generator:'Test Data Generator', automation_recorder:'Automation Recorder', workflow_test_suite:'Workflow Test Suite', failure_inbox:'Failure Inbox', run_ledger:'Run Ledger',
}
