import type { ModuleType } from './moduleTypes'
import type { AiGeneratorData, AudioPlayerData, BarChartData, BudgetData, BulletsData, CalculatorData, CalendarData, CanvasNodeData, ChecklistData, CodeData, ColorPaletteData, ContactData, CounterData, DecisionData, DialogData, FlashcardsData, GameTunerData, GoalTrackerData, HabitData, LinksData, MediaData, MeetingNotesData, MetricsData, MoodTrackerData, TextData, PollData, ProsConsData, RatingData, ReadingListData, SketchpadData, TableData } from './widgetDataCore'
import type { CanvasLmsData, CitationData, FormulaSheetData, GradeCalcData } from './widgetDataEducation'
import type { BranchGateData, DatePickerData, DecisionMatrixData, FormWidgetData, FormulaData, InventoryData, LogbookData, NumberInputData, OutlineData, ProcessData, RiskRegisterData, StatusData, SwotData, TextInputData, TimesheetData, ToggleData } from './widgetDataWorkflow'
import type { AggregatorData, AtlasWidgetData, AutomationCoreData, ChoreRotationData, ClockPulseData, ComparatorData, DebtPayoffData, DecisionJournalData, ExpenseSplitData, GiftsOccasionsData, GuestListData, HomeMaintenanceData, InvoicesData, JobApplicationsData, KeepInTouchData, LatchData, LocationData, MealPlannerData, MedicationsData, NotifierData, RangeMapperData, RecipeData, RecorderData, RenewalsVaultData, SequencerData, SnippetLibraryData, SubscriptionsData, TemplateData, TimekeeperData, TripItineraryData, UnitConverterData, WeeklyReviewData, WorkoutPlanData } from './widgetDataExpansion'

/** Maps every module type to its data schema. */
export interface ModuleDataMap {
  text: TextData
  bullets: BulletsData
  checklist: ChecklistData
  table: TableData
  sketchpad: SketchpadData
    budget: BudgetData
    ai_generator: AiGeneratorData
    dialog: DialogData
  game_tuner: GameTunerData
  audio_player: AudioPlayerData
  canvas_node: CanvasNodeData
      habit: HabitData
  links: LinksData
  code: CodeData
  poll: PollData
  contact: ContactData
  media: MediaData
  metrics: MetricsData
    calendar: CalendarData
    timekeeper: TimekeeperData
  tracker: AtlasWidgetData
  rating: RatingData
  color_palette: ColorPaletteData
  mood_tracker: MoodTrackerData
  calculator: CalculatorData
  bar_chart: BarChartData
  counter: CounterData
  pros_cons: ProsConsData
    goal_tracker: GoalTrackerData
    reading_list: ReadingListData
  flashcards: FlashcardsData
  canvas_lms: CanvasLmsData
  meeting_notes: MeetingNotesData
    decision: DecisionData
    location: LocationData
      grade_calc: GradeCalcData
        formula_sheet: FormulaSheetData
  citation: CitationData
      text_input: TextInputData
  number_input: NumberInputData
  toggle: ToggleData
  branch_gate: BranchGateData
  formula: FormulaData
  status: StatusData
  date_picker: DatePickerData
  outline: OutlineData
  form: FormWidgetData
    process: ProcessData
  risk_register: RiskRegisterData
  decision_matrix: DecisionMatrixData
  swot: SwotData
  timesheet: TimesheetData
  inventory: InventoryData
  logbook: LogbookData
      unit_converter: UnitConverterData
  clock_pulse: ClockPulseData
  comparator: ComparatorData
  aggregator: AggregatorData
  range_mapper: RangeMapperData
  latch: LatchData
    sequencer: SequencerData
  template: TemplateData
  recorder: RecorderData
  notifier: NotifierData
  subscriptions: SubscriptionsData
  debt_payoff: DebtPayoffData
  expense_split: ExpenseSplitData
  invoices: InvoicesData
  meal_planner: MealPlannerData
  recipe: RecipeData
  home_maintenance: HomeMaintenanceData
  chore_rotation: ChoreRotationData
  renewals_vault: RenewalsVaultData
  medications: MedicationsData
  workout_plan: WorkoutPlanData
  job_applications: JobApplicationsData
    decision_journal: DecisionJournalData
  weekly_review: WeeklyReviewData
  snippet_library: SnippetLibraryData
  keep_in_touch: KeepInTouchData
  gifts_occasions: GiftsOccasionsData
  trip_itinerary: TripItineraryData
  guest_list: GuestListData
  savings_circle: AtlasWidgetData
  zakat: AtlasWidgetData
  remittance_planner: AtlasWidgetData
  price_book: AtlasWidgetData
  utility_runway: AtlasWidgetData
  fuel_log: AtlasWidgetData
  side_income: AtlasWidgetData
  wishlist_saver: AtlasWidgetData
  vitals_log: AtlasWidgetData
  cycle_tracker: AtlasWidgetData
  fasting_window: AtlasWidgetData
  hydration: AtlasWidgetData
  sleep_ledger: AtlasWidgetData
  stretch_deck: AtlasWidgetData
  prayer_times: AtlasWidgetData
  scripture_plan: AtlasWidgetData
  gratitude_jar: AtlasWidgetData
  prayer_wall: AtlasWidgetData
  outage_schedule: AtlasWidgetData
  borrowed_items: AtlasWidgetData
  plant_care: AtlasWidgetData
  go_bag: AtlasWidgetData
  bin_night: AtlasWidgetData
  sun_window: AtlasWidgetData
  moving_boxes: AtlasWidgetData
  meeting_cost: AtlasWidgetData
  waiting_on: AtlasWidgetData
  office_hours: AtlasWidgetData
  scope_meter: AtlasWidgetData
  handover_note: AtlasWidgetData
  crit_queue: AtlasWidgetData
  on_call: AtlasWidgetData
  estimate_builder: AtlasWidgetData
  past_papers: AtlasWidgetData
  memorization_ladder: AtlasWidgetData
  experiments: AtlasWidgetData
  mistake_bank: AtlasWidgetData
  skill_tree: AtlasWidgetData
  care_plan: AtlasWidgetData
  gift_ledger: AtlasWidgetData
  team_kudos: AtlasWidgetData
  potluck_matrix: AtlasWidgetData
  star_chart: AtlasWidgetData
  pet_care: AtlasWidgetData
  visa_runway: AtlasWidgetData
  packing_matrix: AtlasWidgetData
  jet_lag_shifter: AtlasWidgetData
  currency_pocket: AtlasWidgetData
  commission_queue: AtlasWidgetData
  content_pipeline: AtlasWidgetData
  loop: AutomationCoreData
  batch_processor: AutomationCoreData
  parallel_runner: AutomationCoreData
  race: AutomationCoreData
  transaction: AutomationCoreData
  subroutine: AutomationCoreData
  approval_gate: AutomationCoreData
  workflow_lock: AutomationCoreData
  webhook_receiver: AutomationCoreData
  manual_trigger: AutomationCoreData
  canvas_lifecycle: AutomationCoreData
  event_merger: AutomationCoreData
  data_join: AutomationCoreData
  object_builder: AutomationCoreData
  event_correlator: AutomationCoreData
  multi_source_aggregator: AutomationCoreData
  widget_creator: AutomationCoreData
  widget_updater: AutomationCoreData
  widget_deleter: AutomationCoreData
  branch_builder: AutomationCoreData
  relation_builder: AutomationCoreData
  canvas_router: AutomationCoreData
  clone_branch: AutomationCoreData
  template_instantiator: AutomationCoreData
  archive_action: AutomationCoreData
  auto_layout_action: AutomationCoreData
  focus_action: AutomationCoreData
  variable_store: AutomationCoreData
  key_value_store: AutomationCoreData
  queue: AutomationCoreData
  stack_store: AutomationCoreData
  set_store: AutomationCoreData
  state_machine: AutomationCoreData
  idempotency_store: AutomationCoreData
  session_store: AutomationCoreData
  mutex: AutomationCoreData
  script_block: AutomationCoreData
  local_function: AutomationCoreData
  http_request: AutomationCoreData
  webhook_sender: AutomationCoreData
  secret_reference: AutomationCoreData
  environment_config: AutomationCoreData
  automation_console: AutomationCoreData
  test_data_generator: AutomationCoreData
  automation_recorder: AutomationCoreData
  workflow_test_suite: AutomationCoreData
  failure_inbox: AutomationCoreData
  run_ledger: AutomationCoreData
}

export type ModuleData = ModuleDataMap[ModuleType]
