export * from './widgetDataCore'
export * from './widgetDataEducation'
export * from './widgetDataWorkflow'
export * from './widgetDataExpansion'
export type { ModuleData, ModuleDataMap } from './widgetDataMap'
