#!/usr/bin/env bash
# Build the collaboration engine (grovepad-yrs, yrs = Rust Yjs) for every
# Apple slice the app ships, wrap the static libraries in an XCFramework and
# regenerate the Swift bindings.
#
# Outputs (both generated — never edit them by hand, rerun this script):
#   apple/Yrs/GrovepadYrsFFI.xcframework          linked by Package.swift
#   apple/Sources/GrovepadCollaboration/Engine/grovepad_yrs.swift
#
# The bindings carry UniFFI checksums of the library they were generated
# from, so the two outputs must always come from the same run.
#
# Needs rustup with: aarch64-apple-darwin aarch64-apple-ios aarch64-apple-ios-sim
# (x86_64-apple-darwin is added to the Mac slice when installed).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APPLE="$(cd "$HERE/.." && pwd)"
# Keep the cache inside the crate on the internal disk (never an exFAT volume).
export CARGO_TARGET_DIR="$HERE/target"
OUT="$HERE/GrovepadYrsFFI.xcframework"
SWIFT_OUT="$APPLE/Sources/GrovepadCollaboration/Engine"
STAGE="$CARGO_TARGET_DIR/xcframework-stage"
LIB=libgrovepad_yrs.a

installed="$(rustup target list --installed)"
need() { grep -qx "$1" <<<"$installed" || { echo "build-xcframework.sh: rustup target add $1" >&2; exit 1; }; }
need aarch64-apple-darwin
need aarch64-apple-ios
need aarch64-apple-ios-sim

mac_targets=(aarch64-apple-darwin)
grep -qx x86_64-apple-darwin <<<"$installed" && mac_targets+=(x86_64-apple-darwin)

export MACOSX_DEPLOYMENT_TARGET=26.0
export IPHONEOS_DEPLOYMENT_TARGET=26.0
for target in "${mac_targets[@]}" aarch64-apple-ios aarch64-apple-ios-sim; do
  (cd "$HERE" && cargo build --release --locked --target "$target")
done

rm -rf "$STAGE" && mkdir -p "$STAGE/macos" "$STAGE/headers"

# Bindings from the host library (library mode reads the UniFFI metadata).
(cd "$HERE" && cargo run --quiet --release --features cli --bin uniffi-bindgen -- \
  generate --library "$CARGO_TARGET_DIR/aarch64-apple-darwin/release/$LIB" \
  --language swift --out-dir "$STAGE/bindings" --no-format)

cp "$STAGE/bindings/grovepad_yrsFFI.h" "$STAGE/headers/"
cat > "$STAGE/headers/module.modulemap" <<'EOF'
module grovepad_yrsFFI {
    header "grovepad_yrsFFI.h"
    export *
}
EOF

mac_libs=()
for target in "${mac_targets[@]}"; do mac_libs+=("$CARGO_TARGET_DIR/$target/release/$LIB"); done
lipo -create "${mac_libs[@]}" -output "$STAGE/macos/$LIB"

rm -rf "$OUT"
xcodebuild -create-xcframework \
  -library "$STAGE/macos/$LIB" -headers "$STAGE/headers" \
  -library "$CARGO_TARGET_DIR/aarch64-apple-ios/release/$LIB" -headers "$STAGE/headers" \
  -library "$CARGO_TARGET_DIR/aarch64-apple-ios-sim/release/$LIB" -headers "$STAGE/headers" \
  -output "$OUT" >/dev/null

mkdir -p "$SWIFT_OUT"
{
  echo "// GENERATED by apple/Yrs/build-xcframework.sh (uniffi-bindgen, library mode). Do not edit."
  echo "// swiftlint:disable all"
  cat "$STAGE/bindings/grovepad_yrs.swift"
} > "$SWIFT_OUT/grovepad_yrs.swift"

echo "Built $OUT"
du -sh "$OUT"
