import type {
  AiGeneratorData,
  AudioPlayerData,
  BarChartData,
  BudgetData,
  BulletsData,
  CalculatorData,
  CalendarData,
  CanvasNodeData,
  ChecklistData,
  CodeData,
  ColorPaletteData,
  ContactData,
  CounterData,
  CountdownData,
  DecisionData,
  DialogData,
  DividerData,
  FlashcardsData,
  GameTunerData,
  GoalTrackerData,
  HabitData,
  KanbanData,
  LinksData,
  MediaData,
  MeetingNotesData,
  MetricsData,
  MoodTrackerData,
  NotesData,
  PollData,
  PriorityMatrixData,
  ProgressData,
  ProsConsData,
  QuoteData,
  RatingData,
  ReadingListData,
  SketchpadData,
  StickyNoteData,
  StopwatchData,
  TableData,
  TimelineData,
  TimerData,
  WeeklyPlannerData,
  WorldClockData,
} from '../../../types/widgetDataCore'
import type { WidgetRendererFamily } from './contracts'
import {
  AiGeneratorWidget, AudioPlayerWidget, BarChartWidget, BudgetWidget, BulletsWidget,
  CalculatorWidget, CalendarWidget, CanvasNodeWidget, ChecklistWidget, CodeWidget,
  ColorPaletteWidget, ContactWidget, CounterWidget, CountdownWidget, DecisionWidget,
  DialogWidget, DividerWidget, FlashcardsWidget, GameTunerWidget, GoalTrackerWidget,
  HabitWidget, KanbanWidget, LinksWidget, MediaWidget, MeetingNotesWidget, MetricsWidget,
  MoodTrackerWidget, NotesWidget, PollWidget, PriorityMatrixWidget, ProgressWidget,
  ProsConsWidget, QuoteWidget, RatingWidget, ReadingListWidget, SketchpadWidget,
  StickyNoteWidget, StopwatchWidget, TableWidget, TimekeeperWidget, TimelineWidget, TimerWidget,
  WeeklyPlannerWidget, WorldClockWidget,
} from './lazyCoreWidgets'

export const coreWidgetRendererFamily: WidgetRendererFamily = {
  id: 'core',
  renderers: {
    notes: ({ widget, onUpdate, onHeightChange }) => <NotesWidget data={widget.data as NotesData} onChange={onUpdate} onHeightChange={onHeightChange} />,
    bullets: ({ widget, onUpdate, onHeightChange }) => <BulletsWidget data={widget.data as BulletsData} onChange={onUpdate} onHeightChange={onHeightChange} />,
    checklist: ({ widget, onUpdate, onHeightChange }) => <ChecklistWidget data={widget.data as ChecklistData} onChange={onUpdate} onHeightChange={onHeightChange} />,
    table: ({ widget, onUpdate }) => <TableWidget data={widget.data as TableData} onChange={onUpdate} />,
    sketchpad: ({ widget }) => <SketchpadWidget data={widget.data as SketchpadData} />,
    budget: ({ widget, onUpdate }) => <BudgetWidget data={widget.data as BudgetData} onChange={onUpdate} />,
    progress: ({ widget, onUpdate }) => <ProgressWidget data={widget.data as ProgressData} onChange={onUpdate} />,
    ai_generator: ({ widget, onUpdate }) => <AiGeneratorWidget data={widget.data as AiGeneratorData} widgetId={widget.id} onChange={onUpdate} />,
    timeline: ({ widget }) => <TimelineWidget data={widget.data as TimelineData} />,
    dialog: ({ widget, onUpdate }) => <DialogWidget data={widget.data as DialogData} onChange={onUpdate} />,
    game_tuner: ({ widget, onUpdate }) => <GameTunerWidget data={widget.data as GameTunerData} onChange={onUpdate} />,
    audio_player: ({ widget, onUpdate }) => <AudioPlayerWidget data={widget.data as AudioPlayerData} onChange={onUpdate} />,
    canvas_node: ({ widget }) => <CanvasNodeWidget data={widget.data as CanvasNodeData} />,
    kanban: ({ widget, onUpdate }) => <KanbanWidget data={widget.data as KanbanData} onChange={onUpdate} />,
    countdown: ({ widget, onUpdate }) => <CountdownWidget data={widget.data as CountdownData} onChange={onUpdate} />,
    habit: ({ widget, onUpdate }) => <HabitWidget data={widget.data as HabitData} onChange={onUpdate} />,
    links: ({ widget, onUpdate }) => <LinksWidget data={widget.data as LinksData} onChange={onUpdate} />,
    code: ({ widget, onUpdate }) => <CodeWidget data={widget.data as CodeData} onChange={onUpdate} />,
    quote: ({ widget, onUpdate }) => <QuoteWidget data={widget.data as QuoteData} onChange={onUpdate} />,
    poll: ({ widget, onUpdate }) => <PollWidget data={widget.data as PollData} onChange={onUpdate} />,
    contact: ({ widget, onUpdate }) => <ContactWidget data={widget.data as ContactData} onChange={onUpdate} />,
    media: ({ widget, onUpdate }) => <MediaWidget data={widget.data as MediaData} onChange={onUpdate} />,
    metrics: ({ widget, onUpdate }) => <MetricsWidget data={widget.data as MetricsData} onChange={onUpdate} />,
    divider: ({ widget, onUpdate }) => <DividerWidget data={widget.data as DividerData} onChange={onUpdate} />,
    sticky_note: ({ widget, onUpdate, onHeightChange }) => <StickyNoteWidget data={widget.data as StickyNoteData} onChange={onUpdate} onHeightChange={onHeightChange} />,
    calendar: ({ widget, onUpdate }) => <CalendarWidget data={widget.data as CalendarData} onChange={onUpdate} />,
    timer: ({ widget, onUpdate }) => <TimerWidget data={widget.data as TimerData} onChange={onUpdate} />,
    timekeeper: ({ widget, onUpdate }) => <TimekeeperWidget data={widget.data as import('../../../types/widgetDataExpansion').TimekeeperData} onChange={onUpdate} />,
    rating: ({ widget, onUpdate }) => <RatingWidget data={widget.data as RatingData} onChange={onUpdate} />,
    color_palette: ({ widget, onUpdate }) => <ColorPaletteWidget data={widget.data as ColorPaletteData} onChange={onUpdate} />,
    mood_tracker: ({ widget, onUpdate }) => <MoodTrackerWidget data={widget.data as MoodTrackerData} onChange={onUpdate} />,
    calculator: ({ widget, onUpdate }) => <CalculatorWidget data={widget.data as CalculatorData} onChange={onUpdate} />,
    bar_chart: ({ widget, onUpdate }) => <BarChartWidget data={widget.data as BarChartData} onChange={onUpdate} />,
    counter: ({ widget, onUpdate }) => <CounterWidget data={widget.data as CounterData} onChange={onUpdate} />,
    pros_cons: ({ widget, onUpdate }) => <ProsConsWidget data={widget.data as ProsConsData} onChange={onUpdate} />,
    weekly_planner: ({ widget, onUpdate }) => <WeeklyPlannerWidget data={widget.data as WeeklyPlannerData} onChange={onUpdate} />,
    goal_tracker: ({ widget, onUpdate }) => <GoalTrackerWidget data={widget.data as GoalTrackerData} onChange={onUpdate} />,
    stopwatch: ({ widget, onUpdate }) => <StopwatchWidget data={widget.data as StopwatchData} onChange={onUpdate} />,
    reading_list: ({ widget, onUpdate }) => <ReadingListWidget data={widget.data as ReadingListData} onChange={onUpdate} />,
    flashcards: ({ widget, onUpdate }) => <FlashcardsWidget data={widget.data as FlashcardsData} onChange={onUpdate} />,
    meeting_notes: ({ widget, onUpdate }) => <MeetingNotesWidget data={widget.data as MeetingNotesData} onChange={onUpdate} />,
    priority_matrix: ({ widget, onUpdate }) => <PriorityMatrixWidget data={widget.data as PriorityMatrixData} onChange={onUpdate} />,
    decision: ({ widget, onUpdate, onHeightChange }) => <DecisionWidget data={widget.data as DecisionData} onChange={onUpdate} onHeightChange={onHeightChange} />,
    world_clock: ({ widget, onUpdate }) => <WorldClockWidget data={widget.data as WorldClockData} onChange={onUpdate} />,
  },
}
