import { lazy } from 'react'

const loadEssentialWidgets = () => import('../modules/EssentialWidgets')

export const BranchGateWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).BranchGateWidget }))
export const DailyAgendaWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).DailyAgendaWidget }))
export const DatePickerWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).DatePickerWidget }))
export const DecisionMatrixWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).DecisionMatrixWidget }))
export const FormWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).FormWidget }))
export const FormulaWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).FormulaWidget }))
export const InventoryWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).InventoryWidget }))
export const LineChartWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).LineChartWidget }))
export const LogbookWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).LogbookWidget }))
export const NumberInputWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).NumberInputWidget }))
export const OutlineWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).OutlineWidget }))
export const PieChartWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).PieChartWidget }))
export const ProcessWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).ProcessWidget }))
export const RiskRegisterWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).RiskRegisterWidget }))
export const StatusWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).StatusWidget }))
export const SwotWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).SwotWidget }))
export const TextInputWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).TextInputWidget }))
export const TimesheetWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).TimesheetWidget }))
export const ToggleWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).ToggleWidget }))
export const UnitConverterWidget = lazy(async () => ({ default: (await loadEssentialWidgets()).UnitConverterWidget }))
