import type { LucideIcon } from 'lucide-react'
import {
  Activity, BadgeDollarSign, BatteryCharging, Bed, BookOpen, Boxes, BriefcaseBusiness,
  CalendarClock, CircleDollarSign, CircleGauge, ClipboardCheck, CloudSun, Coins, CookingPot,
  Film, FlaskConical, Fuel, Gift, GlassWater, GraduationCap,
  HandCoins, HeartHandshake, Hourglass, LampDesk, Luggage, MoonStar, PackageCheck,
  PanelsTopLeft, PawPrint, Plane, PlugZap, ReceiptText, ScrollText, Send,
  ShieldCheck, Sparkles, Sprout, Star, Stethoscope, Sun, Tags, TentTree, Users, WalletCards,
} from 'lucide-react'
import type { AtlasWidgetData, DomainPack, ModuleType } from '../types/spatial'
import type { WidgetCategory } from './registry'

export const ATLAS_TYPES = [
  'savings_circle','zakat','remittance_planner','price_book','utility_runway','fuel_log','side_income','wishlist_saver',
  'vitals_log','cycle_tracker','fasting_window','hydration','sleep_ledger','stretch_deck',
  'prayer_times','scripture_plan','gratitude_jar','prayer_wall',
  'outage_schedule','borrowed_items','plant_care','go_bag','bin_night','sun_window','moving_boxes',
  'meeting_cost','waiting_on','office_hours','scope_meter','handover_note','crit_queue','on_call','estimate_builder',
  'past_papers','memorization_ladder','experiments','mistake_bank','skill_tree',
  'care_plan','gift_ledger','team_kudos','potluck_matrix','star_chart','pet_care',
  'visa_runway','packing_matrix','jet_lag_shifter','currency_pocket','commission_queue','content_pipeline',
] as const satisfies readonly ModuleType[]

export type AtlasType = (typeof ATLAS_TYPES)[number]
type AtlasVisual = 'ring'|'crescent'|'arc'|'ledger'|'vessel'|'gauge'|'streams'|'frost'|'monitor'|'orbit'|'eclipse'|'moon'|'deck'|'horizon'|'book'|'jar'|'constellation'|'schedule'|'tags'|'plant'|'bag'|'bins'|'dome'|'boxes'|'meter'|'hourglass'|'combs'|'pressure'|'clipboard'|'stamps'|'pager'|'receipt'|'grid'|'ladder'|'dishes'|'vault'|'beads'|'balance'|'vu'|'plates'|'stars'|'pet'|'passport'|'suitcase'|'clocks'|'wallet'|'easels'|'film'
type AtlasValueType = 'number'|'text'|'boolean'|'series'
export interface AtlasFieldSpec { key:string; label:string; valueType:AtlasValueType; timeSensitive?:boolean; writable?:'primary'|'secondary'|'target'|'text'|'date'|'timeStart'|'timeEnd'|'enabled' }
export interface AtlasSpec {
  label:string; description:string; icon:LucideIcon; category:WidgetCategory; pack?:DomainPack
  accent:string; visual:AtlasVisual; heroField:string; fields:AtlasFieldSpec[]; commands:string[]
  aliases:string[]; defaults?:Partial<AtlasWidgetData>
}

const life = 'life' as const
const n=(key:string,label:string,timeSensitive=false):AtlasFieldSpec=>({key,label,valueType:'number',timeSensitive})
const t=(key:string,label:string,timeSensitive=false):AtlasFieldSpec=>({key,label,valueType:'text',timeSensitive})
const b=(key:string,label:string,timeSensitive=false):AtlasFieldSpec=>({key,label,valueType:'boolean',timeSensitive})
const s=(key:string,label:string):AtlasFieldSpec=>({key,label,valueType:'series'})
const w=(key:string,label:string,slot:AtlasFieldSpec['writable'],valueType:AtlasValueType='number'):AtlasFieldSpec=>({key,label,valueType,writable:slot})
const A=(label:string,description:string,icon:LucideIcon,category:WidgetCategory,accent:string,visual:AtlasVisual,heroField:string,fields:AtlasFieldSpec[],commands:string[],aliases:string[],pack?:DomainPack,defaults?:Partial<AtlasWidgetData>):AtlasSpec=>({label,description,icon,category,accent,visual,heroField,fields,commands,aliases,pack,defaults})

export const ATLAS_CATALOG: Record<AtlasType,AtlasSpec> = {
  savings_circle:A('Savings Circle','Rotate contributions, turns, and payouts',Coins,'life','#fbbf24','ring','my_turn',[b('my_turn','My turn',true),t('next_payout_date','Next payout',true),n('pot_total','Pot total'),n('rounds_left','Rounds left'),w('contribution_amount','Contribution','primary')],['advance_round'],['committee','stokvel','chit fund','susu','tanda'],life,{primary:100,target:8}),
  zakat:A('Zakat & Giving','Calculate giving against a wealth threshold',MoonStar,'life','#eab308','crescent','due_amount',[n('due_amount','Due amount'),n('days_until_due','Days until due',true),b('above_nisab','Above nisab'),w('assets_total','Assets','primary'),w('nisab_value','Nisab','target')],['mark_paid'],['zakat','tithe','nisab','giving'],life,{primary:5000,target:4000,secondary:2.5}),
  remittance_planner:A('Remittance','Plan recurring cross-border transfers',Send,'life','#38bdf8','arc','send_amount_local',[n('send_amount_local','Send amount'),t('next_send_date','Next send',true),t('best_provider','Best provider'),n('effective_fee_pct','Effective fee'),w('exchange_rate','Exchange rate','secondary')],['mark_sent'],['remittance','send money home','transfer fee'],life,{primary:500,secondary:1.2}),
  price_book:A('Price Book','Remember fair prices across stores',Tags,'life','#34d399','ledger','watched_item_is_cheap',[b('watched_item_is_cheap','Watched item cheap'),t('cheapest_store','Cheapest store'),n('basket_median_total','Basket median'),w('watched_price','Watched price','primary')],['log_price'],['fair price','price history','market prices'],life),
  utility_runway:A('Utility Runway','Estimate prepaid utility days remaining',BatteryCharging,'life','#22d3ee','vessel','days_left',[n('days_left','Days left',true),n('daily_burn','Daily burn'),n('level_pct','Level'),w('current_level','Current level','primary'),w('capacity','Capacity','target')],['log_reading','log_topup'],['prepaid meter','water tank','gas cylinder','data bundle'],life,{primary:65,target:100}),
  fuel_log:A('Fuel Log','Track efficiency and cost per distance',Fuel,'life','#fb923c','gauge','last_efficiency',[n('cost_per_km','Cost per km'),n('last_efficiency','Efficiency'),s('efficiency_series','Efficiency series'),b('efficiency_drifting','Efficiency drifting'),w('odometer','Odometer','primary')],['log_fillup'],['fuel economy','mileage log','petrol','kwh per km'],life,{primary:12000,secondary:7.4}),
  side_income:A('Income Streams','Track platform thresholds and pending payouts',HandCoins,'life','#4ade80','streams','total_pending',[n('total_pending','Total pending'),t('next_payout','Next payout',true),n('nearest_threshold_pct','Nearest threshold'),w('pending_amount','Pending amount','primary')],['log_earning'],['side hustle','gig income','platform payout'],life,{primary:68,target:100}),
  wishlist_saver:A('Wishlist','Cool impulses and forecast affordability',Gift,'life','#f472b6','frost','any_cooled_and_affordable',[t('next_affordable','Next affordable',true),n('total_wanted','Total wanted'),b('any_cooled_and_affordable','Cooled and affordable',true),w('monthly_savings_rate','Monthly savings','primary')],['add_item'],['wishlist','cooling off','save for purchase'],life,{primary:120,target:500}),
  vitals_log:A('Vitals','Log clinical readings against target bands',Stethoscope,'life','#fb7185','monitor','in_range',[n('latest_systolic','Systolic'),n('latest_glucose','Glucose'),b('in_range','In range'),s('week_series','Week series'),w('reading','Reading','primary')],['log_reading'],['blood pressure','glucose log','vitals'],life,{primary:122,target:130,secondary:96}),
  cycle_tracker:A('Cycle','Predict phases with local-only privacy',MoonStar,'life','#c084fc','orbit','phase',[t('phase','Phase',true),n('days_until_period','Days until period',true),b('in_pms_window','PMS window',true),w('cycle_length','Cycle length','target')],['log_period_start'],['period tracker','cycle','menstruation'],life,{primary:12,target:28,privateMode:true}),
  fasting_window:A('Fasting','Track a recurring eating boundary',CalendarClock,'life','#a78bfa','eclipse','fasting_now',[b('fasting_now','Fasting now',true),n('minutes_to_open','Minutes to open',true),t('window_label','Window',true),w('open_time','Open time','timeEnd','text'),w('close_time','Close time','timeStart','text')],['start_fast','end_fast'],['fasting','ramadan','iftar','suhoor','intermittent fast'],life,{timeStart:'05:10',timeEnd:'19:42',mode:'ramadan'}),
  hydration:A('Hydration','Keep daily water intake on pace',GlassWater,'life','#22d3ee','vessel','pct_of_target',[n('pct_of_target','Target progress',true),b('on_track','On track',true),w('daily_target_ml','Daily target','target'),w('current_ml','Current','primary')],['add_glass','reset_day'],['water tracker','hydration','glasses of water'],life,{primary:900,target:2200}),
  sleep_ledger:A('Sleep Ledger','See sleep debt and nightly timing',Bed,'life','#818cf8','moon','debt_hours',[n('debt_hours','Sleep debt',true),n('last_night_hours','Last night'),s('week_series','Week series'),w('sleep_target','Sleep target','target')],['log_night'],['sleep debt','bedtime log','sleep hours'],life,{primary:6.5,target:8}),
  stretch_deck:A('Stretch Deck','Draw a remembered movement break',Activity,'life','#4ade80','deck','current_stretch',[t('current_stretch','Current stretch'),n('done_today','Done today'),w('body_area','Body area','text','text')],['draw_next','mark_done'],['stretch break','desk stretch','movement cards'],life,{text:'Shoulder roll'}),
  prayer_times:A('Prayer Times','Follow today’s solar prayer rhythm',Sun,'life','#fbbf24','horizon','minutes_to_next',[t('next_prayer','Next prayer',true),n('minutes_to_next','Minutes to next',true),n('prayers_done_today','Prayers done'),t('fajr','Fajr',true),t('dhuhr','Dhuhr',true),t('asr','Asr',true),t('maghrib','Maghrib',true),t('isha','Isha',true),w('location','Location','text','text')],['mark_prayed'],['prayer times','maghrib','fajr','salah','namaz'],life,{times:{fajr:'05:10',dhuhr:'12:35',asr:'16:18',maghrib:'19:42',isha:'21:05'},text:'Local'}),
  scripture_plan:A('Scripture Plan','Pace a divided reading plan',BookOpen,'life','#eab308','book','today_portion',[t('today_portion','Today’s portion',true),n('pct_complete','Complete'),b('on_schedule','On schedule',true),n('catchup_per_day','Catch-up pace'),w('total_divisions','Divisions','target')],['mark_read'],['quran plan','bible in a year','scripture reading'],life,{primary:8,target:30}),
  gratitude_jar:A('Gratitude Jar','Collect gratitude into a visible ritual',Sparkles,'life','#f59e0b','jar','gratitude_count',[n('gratitude_count','Gratitudes'),t('random_gratitude','Random gratitude'),b('added_today','Added today',true),w('prompt','Prompt','text','text')],['add_gratitude','draw_memory'],['gratitude journal','thankful','gratitude jar'],life),
  prayer_wall:A('Prayer Wall','Hold intentions and answered prayers',LampDesk,'life','#fb7185','constellation','answered_count',[n('open_count','Open prayers'),n('answered_count','Answered'),t('oldest_prayer','Oldest prayer',true),w('new_prayer','New prayer','text','text')],['add_prayer','mark_answered'],['prayer wall','prayer requests','intentions'],life),
  outage_schedule:A('Power Schedule','Plan around scheduled outages',PlugZap,'life','#f97316','schedule','power_on',[b('power_on','Power on',true),n('minutes_to_outage','Minutes to outage',true),t('next_window','Next outage',true),w('schedule_rules','Schedule','text','text')],['log_outage'],['load shedding','power cut','outage schedule'],life,{timeStart:'18:00',timeEnd:'20:00'}),
  borrowed_items:A('Borrow Ledger','Remember who holds borrowed things',Tags,'life','#d97706','tags','overdue_count',[n('overdue_count','Overdue',true),t('oldest_item','Oldest item',true),t('holder','Holder'),w('new_item','Item','text','text')],['lend_item','mark_returned'],['borrowed items','lent to','who has my'],life),
  plant_care:A('Plant Shelf','Keep every plant’s care rhythm',Sprout,'life','#84cc16','plant','due_today_count',[n('due_today_count','Due today',true),t('thirstiest','Thirstiest',true),b('all_watered','All watered',true),w('interval_days','Water interval','target')],['water','water_all_due'],['plant care','water plants','houseplants'],life,{primary:5,target:7}),
  go_bag:A('Go Bag','Maintain emergency-kit readiness',ShieldCheck,'life','#f59e0b','bag','readiness_pct',[n('readiness_pct','Readiness'),n('expired_count','Expired',true),t('next_expiry','Next expiry',true),w('people_count','People','target')],['mark_replaced'],['go bag','emergency kit','earthquake kit'],life,{primary:72,target:100}),
  bin_night:A('Bin Night','Surface the right collection stream',PackageCheck,'life','#22c55e','bins','is_collection_eve',[t('tonight_bin','Tonight’s bin',true),b('is_collection_eve','Collection eve',true),w('schedule_rules','Schedule rules','text','text')],['advance_schedule'],['bin night','trash collection','recycling day'],life,{text:'Green bin'}),
  sun_window:A('Sun Window','Track daylight and golden hour offline',CloudSun,'life','#fbbf24','dome','is_golden_hour',[n('minutes_to_sunset','Minutes to sunset',true),b('is_golden_hour','Golden hour',true),n('daylight_today','Daylight hours',true),t('sunrise','Sunrise',true),t('sunset','Sunset',true),w('latitude','Latitude','primary')],['refresh_sun'],['sunset','golden hour','daylight','solar window'],life,{primary:41.3,times:{sunrise:'05:42',sunset:'19:55'}}),
  moving_boxes:A('Moving Boxes','Search boxes and unpack by room',Boxes,'life','#d97706','boxes','unpacked_pct',[n('unpacked_pct','Unpacked'),n('boxes_left','Boxes left'),t('find_result','Find result'),w('search_query','Search','text','text')],['mark_unpacked','add_box'],['moving boxes','which box','unpack move'],life,{primary:2,target:8}),
  meeting_cost:A('Meeting Meter','Expose the live cost of meetings',CircleDollarSign,'tracking','#f97316','meter','cost_so_far',[n('cost_so_far','Cost so far',true),b('running','Running',true),s('cost_series','Cost series'),w('attendee_count','Attendees','target'),w('avg_rate','Average rate','secondary')],['start','stop'],['meeting cost','meeting meter','payroll meeting'],undefined,{target:6,secondary:45,enabled:false}),
  waiting_on:A('Waiting On','Age delegated requests and follow-ups',Hourglass,'tracking','#f59e0b','hourglass','overdue_count',[n('overdue_count','Overdue',true),n('oldest_wait_days','Oldest wait',true),t('oldest_item','Oldest item',true),w('new_request','Request','text','text')],['mark_pinged','mark_received'],['waiting on','follow up with','awaiting reply']),
  office_hours:A('Overlap Finder','Find working-hour overlap across zones',Users,'tracking','#38bdf8','combs','overlap_now',[b('overlap_now','Overlap now',true),t('next_overlap','Next overlap',true),n('overlap_hours_today','Overlap hours',true),w('workday_start','Workday start','timeStart','text'),w('workday_end','Workday end','timeEnd','text')],['add_person'],['timezone overlap','office hours','remote team time'],undefined,{timeStart:'09:00',timeEnd:'17:00'}),
  scope_meter:A('Scope Meter','Measure requests against contract caps',CircleGauge,'tracking','#fb7185','pressure','over_scope',[n('revisions_left','Revisions left'),b('over_scope','Over scope'),n('extras_value','Extras value'),w('revision_cap','Revision cap','target')],['log_request'],['scope creep','revision limit','change order'],undefined,{primary:2,target:3}),
  handover_note:A('Handover','Transfer flagged state between shifts',ClipboardCheck,'tracking','#60a5fa','clipboard','acknowledged',[n('open_flags','Open flags'),b('acknowledged','Acknowledged'),t('flag_summary','Flag summary'),w('new_flag','New flag','text','text')],['add_flag','acknowledge_all'],['shift handover','sbar','handoff note']),
  crit_queue:A('Crit Room','Collect review stamps by round',PanelsTopLeft,'tracking','#a78bfa','stamps','all_approved',[n('approvals','Approvals'),b('all_approved','All approved'),n('round','Round'),w('reviewer_count','Reviewers','target')],['stamp','new_round'],['design critique','approval round','review queue']),
  on_call:A('On Call','Show the live rota holder',BriefcaseBusiness,'tracking','#84cc16','pager','is_me',[t('holder_now','Holder now',true),b('is_me','Is me',true),n('next_handoff_in','Handoff in',true),w('rotation_schedule','Rotation','text','text')],['log_incident'],['on call rota','pager duty','who is on call']),
  estimate_builder:A('Estimate','Build quotes with margin awareness',ReceiptText,'tracking','#2dd4bf','receipt','quote_total',[n('quote_total','Quote total'),n('margin_pct','Margin'),t('quote_text','Quote text'),n('win_rate','Win rate'),w('risk_multiplier','Risk multiplier','secondary')],['add_line','mark_won','mark_lost'],['quote builder','job estimate','price a job'],undefined,{primary:800,secondary:1.15,target:500}),
  past_papers:A('Past Papers','Track exam-paper coverage and scores',GraduationCap,'study','#818cf8','grid','avg_score',[n('papers_left','Papers left'),n('avg_score','Average score'),t('weakest_topic','Weakest topic'),s('trend','Score trend'),w('score','Score','primary')],['log_attempt'],['past papers','mock exam scores','exam practice'],undefined,{primary:72,target:100}),
  memorization_ladder:A('Memorization','Review ordered material before it decays',BookOpen,'study','#eab308','ladder','overall_strength_pct',[n('due_segments','Due segments',true),n('overall_strength_pct','Strength',true),t('next_review','Next review',true),w('segment_count','Segments','target')],['mark_reviewed','advance_frontier'],['hifz','memorization ladder','learn script'],undefined,{primary:64,target:20}),
  experiments:A('Experiments','Run hypothesis-to-verdict learning loops',FlaskConical,'study','#34d399','dishes','win_rate',[n('running_count','Running'),n('win_rate','Win rate'),t('last_verdict','Last verdict'),w('hypothesis','Hypothesis','text','text')],['start_experiment','record_result'],['experiment log','hypothesis test','ab test']),
  mistake_bank:A('Mistake Bank','Detect recurring error patterns',BadgeDollarSign,'study','#fb7185','vault','recurrence_alert',[t('top_category','Top category'),b('recurrence_alert','Recurrence alert',true),n('cost_total','Total cost'),w('mistake','Mistake','text','text')],['deposit'],['mistake log','blunder journal','trading mistakes']),
  skill_tree:A('Skill Tree','Unlock skills through prerequisites',TentTree,'study','#a78bfa','constellation','frontier',[n('unlocked_count','Unlocked'),t('frontier','Frontier'),n('pct_complete','Complete'),w('new_skill','New skill','text','text')],['complete_node'],['skill tree','learning roadmap','prerequisite map']),
  care_plan:A('Care Plan','Coordinate a gentle daily care strip',HeartHandshake,'life','#f472b6','beads','today_complete',[t('last_checkin','Last check-in',true),n('tasks_due','Tasks due',true),b('today_complete','Today complete',true),w('care_note','Care note','text','text')],['log_care_event'],['eldercare','care plan','caregiver checklist'],life),
  gift_ledger:A('Gift Ledger','Balance given and received reciprocity',Gift,'life','#ef4444','balance','owed_count',[n('owed_count','Owed'),t('next_reciprocity','Next reciprocity',true),n('balance_with','Balance'),w('gift_amount','Gift amount','primary')],['log_gift'],['hongbao','salami','shagun','gift ledger','owambe'],life),
  team_kudos:A('Applause Meter','Accumulate and digest team recognition',Sparkles,'life','#f59e0b','vu','kudos_this_week',[n('kudos_this_week','Kudos this week'),t('top_receiver','Top receiver'),t('digest','Digest'),w('message','Kudos message','text','text')],['give_kudos','flush_digest'],['team kudos','recognition','applause meter'],life),
  potluck_matrix:A('Potluck Board','Expose missing dishes and dietary gaps',CookingPot,'life','#fb923c','plates','gaps',[n('gaps','Gaps'),t('missing_category','Missing category'),n('dietary_conflicts','Dietary conflicts'),w('dish','Dish','text','text')],['claim_dish'],['potluck','iftar dishes','church supper','braai'],life),
  star_chart:A('Star Chart','Track family stars and rewards',Star,'life','#fbbf24','stars','reward_ready',[n('stars','Stars'),b('reward_ready','Reward ready'),t('leader','Leader'),w('reward_threshold','Reward threshold','target')],['give_star','redeem'],['star chart','reward chart','kids chores'],life,{primary:6,target:10}),
  pet_care:A('Pet Card','Unify feeding, walks, vet dates, and weight',PawPrint,'life','#84cc16','pet','overdue',[t('next_due','Next due',true),b('overdue','Overdue',true),s('weight_series','Weight series'),w('pet_name','Pet name','text','text')],['log_feed','log_walk','log_weight'],['pet care','new pet','feeding walks vet'],life,{text:'Milo'}),
  visa_runway:A('Visa Runway','Calculate rolling visa-day allowance',ScrollText,'life','#ef4444','passport','days_left',[n('days_left','Days left',true),t('must_exit_by','Must exit by',true),n('window_days_used','Window days used',true),b('overstay_risk','Overstay risk',true),w('allowed_days','Allowed days','target')],['log_entry','log_exit'],['schengen days','visa days left','90 in 180'],life,{primary:42,target:90}),
  packing_matrix:A('Packing','Balance item weights across bags',Luggage,'life','#38bdf8','suitcase','overweight',[n('kg_remaining','Kg remaining'),b('overweight','Overweight'),n('unpacked_count','Unpacked'),w('bag_limit_kg','Bag limit','target'),w('packed_kg','Packed weight','primary')],['pack_item'],['packing list weight','overweight suitcase','bag allowance'],life,{primary:17,target:23}),
  jet_lag_shifter:A('Jet Lag Plan','Converge sleep toward destination time',Plane,'life','#818cf8','clocks','shift_remaining_hours',[t('tonight_bedtime','Tonight bedtime',true),n('days_to_aligned','Days to aligned',true),n('shift_remaining_hours','Shift remaining',true),w('departure_date','Departure','date','text'),w('tz_delta','Timezone delta','secondary')],['advance_night'],['jet lag plan','shift sleep before flight'],life,{secondary:6,date:new Date(Date.now()+5*86400000).toISOString().slice(0,10)}),
  currency_pocket:A('Cash Pockets','Aggregate cash held across currencies',WalletCards,'life','#2dd4bf','wallet','total_home_value',[n('total_home_value','Home value'),b('pocket_low','Pocket low'),w('amount','Amount','primary'),w('rates','Rates','secondary')],['spend','add_cash'],['travel cash','multiple currencies','currency wallet'],life,{primary:240,secondary:1}),
  commission_queue:A('Commission Queue','Manage capped creative slots and stages',LampDesk,'specialist','#f472b6','easels','slots_open',[n('slots_open','Slots open'),n('queue_revenue','Queue revenue'),t('current_piece','Current piece'),w('slot_cap','Slot cap','target')],['advance_stage','deliver'],['art commissions','commission slots','artist queue'],'creative_writing',{primary:2,target:4}),
  content_pipeline:A('Content Pipeline','Protect publishing cadence across platforms',Film,'planning','#ef4444','film','cadence_health_pct',[t('next_post','Next post',true),n('overdue_slots','Overdue slots',true),n('cadence_health_pct','Cadence health',true),n('ideas_count','Ideas'),w('new_idea','New idea','text','text')],['advance','mark_posted'],['content calendar','video channel','posting pipeline'],undefined,{primary:76,target:100}),
}

const today=()=>new Date().toISOString().slice(0,10)
export function defaultAtlasData(type:AtlasType):AtlasWidgetData {
  const spec=ATLAS_CATALOG[type]
  const base:AtlasWidgetData={
    label:spec.label,mode:'standard',primary:0,secondary:0,target:100,text:'',date:today(),
    timeStart:'09:00',timeEnd:'17:00',enabled:true,privateMode:false,actionCount:0,lastActionAt:null,
    items:[
      {id:crypto.randomUUID(),label:'First item',value:1,done:false,date:today(),status:'active',note:''},
      {id:crypto.randomUUID(),label:'Next item',value:0,done:false,date:today(),status:'waiting',note:''},
    ],
    history:[{t:Date.now(),v:0}],times:{},
  }
  return {...base,...spec.defaults,times:{...base.times,...spec.defaults?.times}}
}

export const ATLAS_TYPE_SET:ReadonlySet<ModuleType>=new Set(ATLAS_TYPES)
