import type { LucideIcon } from 'lucide-react'
import { Activity, Archive, Beaker, Blocks, Braces, Bug, CirclePlay, Combine, Database, FileClock, FileJson, Focus, GitBranch, GitMerge, Globe2, Group, Hand, KeyRound, Layers3, ListEnd, ListPlus, LockKeyhole, Network, PackageOpen, Radio, Repeat2, Route, ScrollText, Send, Server, ShieldCheck, Shuffle, Split, SquareStack, TestTube2, Trash2, Variable, Webhook, Workflow, Wrench } from 'lucide-react'
import type { AutomationCoreData, ModuleType } from '../types/spatial'
import type { WidgetCategory } from './registry'

export const AUTOMATION_CORE_TYPES = [
  'loop','batch_processor','parallel_runner','race','transaction','subroutine','approval_gate','workflow_lock',
  'webhook_receiver','manual_trigger','canvas_lifecycle','event_merger','data_join','object_builder','event_correlator','multi_source_aggregator',
  'widget_creator','widget_updater','widget_deleter','branch_builder','relation_builder','canvas_router','auto_grouper','clone_branch','template_instantiator','archive_action','auto_layout_action','focus_action',
  'variable_store','key_value_store','queue','stack_store','set_store','state_machine','idempotency_store','session_store','mutex',
  'script_block','local_function','http_request','webhook_sender','secret_reference','environment_config',
  'automation_console','test_data_generator','automation_recorder','workflow_test_suite','failure_inbox','run_ledger',
] as const satisfies readonly ModuleType[]

export type AutomationCoreType=(typeof AUTOMATION_CORE_TYPES)[number]
type AutomationKind='orchestrator'|'source'|'join'|'canvas'|'state'|'integration'|'observability'
interface Spec {label:string;description:string;icon:LucideIcon;category:WidgetCategory;accent:string;kind:AutomationKind;aliases:string[]}
const s=(label:string,description:string,icon:LucideIcon,kind:AutomationKind,aliases:string[]=[],accent='#a78bfa'):Spec=>({label,description,icon,kind,aliases,accent,category:kind==='state'?'data':kind==='observability'?'tracking':'automation'})

export const AUTOMATION_CORE_CATALOG:Record<AutomationCoreType,Spec>={
  loop:s('Loop','Run a branch once for every input item',Repeat2,'orchestrator',['for each','iterate']), batch_processor:s('Batch Processor','Process work in bounded concurrent chunks',PackageOpen,'orchestrator',['batch','chunks']), parallel_runner:s('Parallel Runner','Launch branches together and join their results',Split,'orchestrator',['parallel','fan out']), race:s('Race','Continue with the first branch to finish',Shuffle,'orchestrator',['first result']), transaction:s('Transaction','Commit several canvas mutations atomically',ShieldCheck,'orchestrator',['atomic','rollback']), subroutine:s('Subroutine','Expose a reusable callable widget cluster',Blocks,'orchestrator',['function graph']), approval_gate:s('Approval Gate','Pause visibly for a human decision',Hand,'orchestrator',['human approval']), workflow_lock:s('Workflow Lock','Prevent concurrent duplicate workflow runs',LockKeyhole,'orchestrator',['run lock']),
  webhook_receiver:s('Webhook Receiver','Receive structured events from external services',Webhook,'source',['incoming webhook']), manual_trigger:s('Manual Trigger','Launch a workflow from a visible button',CirclePlay,'source',['run button']), canvas_lifecycle:s('Canvas Lifecycle','Emit events when a canvas is entered or left',FileClock,'source',['canvas opened']), event_merger:s('Event Merger','Merge asynchronous sources into one ordered stream',GitMerge,'source',['merge events']), data_join:s('Data Join','Join two collections using matching keys',Combine,'join',['join records']), object_builder:s('Object Builder','Construct one object from multiple connected values',FileJson,'join',['build json']), event_correlator:s('Event Correlator','Match related events arriving from different sources',Network,'join',['correlate']), multi_source_aggregator:s('Multi Source Aggregator','Collect dynamic streams into one collection',Layers3,'join',['fan in']),
  widget_creator:s('Widget Creator','Create widgets from incoming records',ListPlus,'canvas',['spawn','spawn widget']), widget_updater:s('Widget Updater','Find and update existing widgets',Wrench,'canvas',['modify widget']), widget_deleter:s('Widget Deleter','Safely delete widgets matching a rule',Trash2,'canvas',['remove widget'],'#fb7185'), branch_builder:s('Branch Builder','Turn records into connected child structures',GitBranch,'canvas',['create branch']), relation_builder:s('Relation Builder','Create or remove graph relationships',Route,'canvas',['create relation']), canvas_router:s('Canvas Router','Move generated structures to another canvas',Route,'canvas',['move to canvas']), auto_grouper:s('Auto Grouper','Maintain widget groups from rules',Group,'canvas',['group widgets']), clone_branch:s('Clone Branch','Duplicate a connected graph structure',GitBranch,'canvas',['copy branch']), template_instantiator:s('Template Instantiator','Generate a predefined multi-widget system',Blocks,'canvas',['instantiate template']), archive_action:s('Archive Action','Move completed structures into an archive canvas',Archive,'canvas',['archive']), auto_layout_action:s('Auto Layout Action','Arrange only the branch changed by a workflow',Shuffle,'canvas',['layout branch']), focus_action:s('Focus Action','Navigate to and highlight a workflow result',Focus,'canvas',['frame widget']),
  variable_store:s('Variable Store','Persist a named reusable value',Variable,'state',['variable']), key_value_store:s('Key Value Store','Persist dynamically addressed values',Database,'state',['dictionary']), queue:s('Queue','Release persistent work in first-in order',ListEnd,'state',['fifo']), stack_store:s('Stack','Release persistent work in last-in order',SquareStack,'state',['lifo']), set_store:s('Set Store','Remember unique values and membership',Database,'state',['unique set']), state_machine:s('State Machine','Enforce legal transitions between states',Workflow,'state',['finite state']), idempotency_store:s('Idempotency Store','Prevent an event from being processed twice',ShieldCheck,'state',['dedupe event']), session_store:s('Session Store','Retain state only for the current session',Database,'state',['temporary state']), mutex:s('Mutex','Provide exclusive ownership of a shared resource',LockKeyhole,'state',['exclusive lock']),
  script_block:s('Script Block','Run sandboxed code against explicit ports',Braces,'integration',['javascript','code automation']), local_function:s('Local Function','Define reusable typed code for workflows',Braces,'integration',['custom function']), http_request:s('HTTP Request','Call an external API and publish its response',Globe2,'integration',['api request']), webhook_sender:s('Webhook Sender','Send structured events to another service',Send,'integration',['outgoing webhook']), secret_reference:s('Secret Reference','Reference credentials without exposing them',KeyRound,'integration',['credential']), environment_config:s('Environment Config','Provide reusable non-secret runtime configuration',Server,'integration',['env config']),
  automation_console:s('Automation Console','Inspect workflow runs, timing and failures',Activity,'observability',['run console']), test_data_generator:s('Test Data Generator','Produce repeatable workflow test payloads',Beaker,'observability',['mock data']), automation_recorder:s('Automation Recorder','Capture manual canvas operations as a workflow',Radio,'observability',['record actions']), workflow_test_suite:s('Workflow Test Suite','Run saved cases against expected outputs',TestTube2,'observability',['automation tests']), failure_inbox:s('Failure Inbox','Collect uncaught workflow failures for review',Bug,'observability',['error inbox'],'#fb7185'), run_ledger:s('Run Ledger','Keep an auditable automation action history',ScrollText,'observability',['audit log']),
}

export function defaultAutomationCoreData(type:AutomationCoreType):AutomationCoreData{
  const spec=AUTOMATION_CORE_CATALOG[type]
  return {label:spec.label,input:'',output:'',config:'{}',mode:'standard',enabled:true,running:false,count:0,concurrency:1,lastRunAt:null,lastError:'',items:[]}
}
export const AUTOMATION_CORE_SET:ReadonlySet<ModuleType>=new Set(AUTOMATION_CORE_TYPES)
