// Generated by scripts/build-widget-skin-reorganization.py.
// Source: docs/widget-skin-opportunity-catalogue.md. Do not hand-edit.

export type SkinOwnershipKind =
  | 'skin'
  | 'capability'
  | 'control'
  | 'preset'
  | 'move'
  | 'new-widget'

export interface SkinOwnership {
  kind: SkinOwnershipKind
  target: string
}

export const WIDGET_SKIN_OWNERSHIP = {
  "branch_gate": {
    "pass_block": {
      "kind": "skin",
      "target": "Bool Gate"
    },
    "inverter": {
      "kind": "skin",
      "target": "Bool Gate"
    },
    "arm_disarm": {
      "kind": "skin",
      "target": "Bool Gate"
    },
    "permission": {
      "kind": "skin",
      "target": "Bool Gate"
    },
    "and_or": {
      "kind": "capability",
      "target": "Bool Gate"
    },
    "debounced_gate": {
      "kind": "capability",
      "target": "Bool Gate"
    }
  },
  "canvas_node": {
    "portal": {
      "kind": "skin",
      "target": "Canvas"
    },
    "cover": {
      "kind": "skin",
      "target": "Canvas"
    },
    "live_thumbnail": {
      "kind": "capability",
      "target": "Canvas"
    },
    "dashboard_door": {
      "kind": "capability",
      "target": "Canvas"
    },
    "folder_index": {
      "kind": "capability",
      "target": "Canvas"
    }
  },
  "bullets": {
    "dots": {
      "kind": "skin",
      "target": "Bullets"
    },
    "numbered": {
      "kind": "skin",
      "target": "Bullets"
    },
    "compact_chips": {
      "kind": "skin",
      "target": "Bullets"
    },
    "two_column": {
      "kind": "skin",
      "target": "Bullets"
    },
    "nested_outline": {
      "kind": "move",
      "target": "Outline"
    },
    "rolling_log": {
      "kind": "move",
      "target": "Logbook"
    }
  },
  "code": {
    "editor": {
      "kind": "skin",
      "target": "Code Snippet"
    },
    "terminal": {
      "kind": "skin",
      "target": "Code Snippet"
    },
    "config": {
      "kind": "skin",
      "target": "Code Snippet"
    },
    "compact_snippet": {
      "kind": "skin",
      "target": "Code Snippet"
    },
    "diff": {
      "kind": "new-widget",
      "target": "Diff Viewer"
    },
    "runnable_example": {
      "kind": "new-widget",
      "target": "Code Runner"
    }
  },
  "logbook": {
    "daily_log": {
      "kind": "preset",
      "target": "Logbook"
    },
    "incident_log": {
      "kind": "preset",
      "target": "Logbook"
    },
    "lab_notebook": {
      "kind": "preset",
      "target": "Logbook"
    },
    "change_log": {
      "kind": "preset",
      "target": "Logbook"
    },
    "maintenance_log": {
      "kind": "preset",
      "target": "Logbook"
    },
    "audit_trail": {
      "kind": "preset",
      "target": "Logbook"
    },
    "travel_log": {
      "kind": "move",
      "target": "Trip Itinerary"
    }
  },
  "meeting_notes": {
    "agenda": {
      "kind": "preset",
      "target": "Meeting Notes"
    },
    "minutes": {
      "kind": "preset",
      "target": "Meeting Notes"
    },
    "stand_up": {
      "kind": "preset",
      "target": "Meeting Notes"
    },
    "retrospective": {
      "kind": "preset",
      "target": "Meeting Notes"
    },
    "one_to_one": {
      "kind": "preset",
      "target": "Meeting Notes"
    },
    "decision_review": {
      "kind": "preset",
      "target": "Meeting Notes"
    },
    "handoff": {
      "kind": "preset",
      "target": "Meeting Notes"
    }
  },
  "notes": {
    "daily_log": {
      "kind": "move",
      "target": "Logbook"
    },
    "markdown_page": {
      "kind": "skin",
      "target": "Note"
    },
    "typewriter": {
      "kind": "skin",
      "target": "Note"
    },
    "callout": {
      "kind": "skin",
      "target": "Note"
    },
    "versioned_note": {
      "kind": "capability",
      "target": "Note"
    }
  },
  "outline": {
    "tree": {
      "kind": "skin",
      "target": "Outline"
    },
    "roman": {
      "kind": "skin",
      "target": "Outline"
    },
    "scenes": {
      "kind": "skin",
      "target": "Outline"
    },
    "sitemap": {
      "kind": "skin",
      "target": "Outline"
    },
    "course": {
      "kind": "skin",
      "target": "Outline"
    },
    "work_breakdown": {
      "kind": "new-widget",
      "target": "Work Breakdown"
    },
    "collapsible_brief": {
      "kind": "capability",
      "target": "Outline"
    }
  },
  "flashcards": {
    "cloze": {
      "kind": "skin",
      "target": "Study Deck"
    },
    "leitner_boxes": {
      "kind": "capability",
      "target": "Study Deck"
    },
    "spaced_repetition": {
      "kind": "capability",
      "target": "Study Deck"
    },
    "match_pairs": {
      "kind": "capability",
      "target": "Study Deck"
    },
    "image_recall": {
      "kind": "capability",
      "target": "Study Deck"
    }
  },
  "calendar": {
    "month": {
      "kind": "skin",
      "target": "Calendar"
    },
    "week": {
      "kind": "skin",
      "target": "Calendar"
    },
    "agenda": {
      "kind": "skin",
      "target": "Calendar"
    },
    "year_heatmap": {
      "kind": "skin",
      "target": "Calendar"
    },
    "availability": {
      "kind": "new-widget",
      "target": "Shift Planner"
    },
    "shift_rota": {
      "kind": "new-widget",
      "target": "Shift Planner"
    },
    "birthday_and_anniversary": {
      "kind": "move",
      "target": "Gifts & Occasions"
    }
  },
  "date_picker": {
    "deadline": {
      "kind": "skin",
      "target": "Date"
    },
    "anniversary": {
      "kind": "move",
      "target": "Gifts & Occasions"
    },
    "relative_date": {
      "kind": "skin",
      "target": "Date"
    },
    "range": {
      "kind": "capability",
      "target": "Date"
    },
    "recurring_date": {
      "kind": "capability",
      "target": "Date"
    },
    "milestone": {
      "kind": "capability",
      "target": "Date"
    }
  },
  "decision_matrix": {
    "weighted_matrix": {
      "kind": "skin",
      "target": "Decision Matrix"
    },
    "scorecard": {
      "kind": "skin",
      "target": "Decision Matrix"
    },
    "winner_board": {
      "kind": "skin",
      "target": "Decision Matrix"
    },
    "pairwise": {
      "kind": "capability",
      "target": "Decision Matrix"
    },
    "sensitivity": {
      "kind": "capability",
      "target": "Decision Matrix"
    },
    "threshold": {
      "kind": "capability",
      "target": "Decision Matrix"
    }
  },
  "decision": {
    "wheel": {
      "kind": "skin",
      "target": "Decision Picker"
    },
    "coin_dice": {
      "kind": "control",
      "target": "Decision Picker"
    },
    "tournament": {
      "kind": "new-widget",
      "target": "Decision Tournament"
    },
    "elimination": {
      "kind": "new-widget",
      "target": "Decision Tournament"
    },
    "consensus": {
      "kind": "new-widget",
      "target": "Consensus Board"
    }
  },
  "poll": {
    "bars": {
      "kind": "skin",
      "target": "Poll"
    },
    "donut": {
      "kind": "skin",
      "target": "Poll"
    },
    "approval": {
      "kind": "control",
      "target": "Poll"
    },
    "ranked_choice": {
      "kind": "new-widget",
      "target": "Ranked Poll"
    },
    "pairwise": {
      "kind": "new-widget",
      "target": "Ranked Poll"
    },
    "live_room": {
      "kind": "new-widget",
      "target": "Live Poll"
    },
    "anonymous": {
      "kind": "control",
      "target": "Poll"
    }
  },
  "process": {
    "stepper": {
      "kind": "skin",
      "target": "Process / SOP"
    },
    "checklist_sop": {
      "kind": "skin",
      "target": "Process / SOP"
    },
    "runbook": {
      "kind": "skin",
      "target": "Process / SOP"
    },
    "recipe": {
      "kind": "move",
      "target": "Recipe"
    },
    "incident": {
      "kind": "new-widget",
      "target": "Incident Response"
    },
    "swimlane": {
      "kind": "new-widget",
      "target": "Workflow Designer"
    },
    "branching_procedure": {
      "kind": "new-widget",
      "target": "Workflow Designer"
    }
  },
  "pros_cons": {
    "balance": {
      "kind": "skin",
      "target": "Pros & Cons"
    },
    "debate": {
      "kind": "skin",
      "target": "Pros & Cons"
    },
    "red_team": {
      "kind": "skin",
      "target": "Pros & Cons"
    },
    "weighted_trade_off": {
      "kind": "capability",
      "target": "Pros & Cons"
    },
    "reversible_irreversible": {
      "kind": "capability",
      "target": "Pros & Cons"
    }
  },
  "risk_register": {
    "register": {
      "kind": "skin",
      "target": "Risk Register"
    },
    "heatmap": {
      "kind": "skin",
      "target": "Risk Register"
    },
    "top_risks": {
      "kind": "skin",
      "target": "Risk Register"
    },
    "raid": {
      "kind": "skin",
      "target": "Risk Register"
    },
    "controls": {
      "kind": "capability",
      "target": "Risk Register"
    },
    "fmea": {
      "kind": "new-widget",
      "target": "FMEA"
    },
    "bow_tie": {
      "kind": "new-widget",
      "target": "Bow-tie Analysis"
    }
  },
  "swot": {
    "classic": {
      "kind": "skin",
      "target": "SWOT Analysis"
    },
    "personal": {
      "kind": "skin",
      "target": "SWOT Analysis"
    },
    "competitor": {
      "kind": "skin",
      "target": "SWOT Analysis"
    },
    "one_page": {
      "kind": "skin",
      "target": "SWOT Analysis"
    },
    "tows": {
      "kind": "capability",
      "target": "SWOT Analysis"
    },
    "evidence_backed": {
      "kind": "capability",
      "target": "SWOT Analysis"
    }
  },
  "checklist": {
    "inbox": {
      "kind": "preset",
      "target": "Tasks"
    },
    "shopping": {
      "kind": "preset",
      "target": "Tasks"
    },
    "recurring": {
      "kind": "capability",
      "target": "Tasks"
    },
    "sprint": {
      "kind": "preset",
      "target": "Tasks"
    },
    "dependencies": {
      "kind": "capability",
      "target": "Tasks"
    },
    "routine": {
      "kind": "preset",
      "target": "Tasks"
    }
  },
  "citation": {
    "bibliography": {
      "kind": "skin",
      "target": "Citations"
    },
    "source_cards": {
      "kind": "skin",
      "target": "Citations"
    },
    "annotated": {
      "kind": "skin",
      "target": "Citations"
    },
    "footnotes": {
      "kind": "skin",
      "target": "Citations"
    },
    "literature_matrix": {
      "kind": "new-widget",
      "target": "Literature Matrix"
    },
    "evidence_map": {
      "kind": "new-widget",
      "target": "Evidence Map"
    }
  },
  "cornell": {
    "lecture": {
      "kind": "skin",
      "target": "Cornell Notes"
    },
    "reading": {
      "kind": "skin",
      "target": "Cornell Notes"
    },
    "problem_solving": {
      "kind": "skin",
      "target": "Cornell Notes"
    },
    "interview": {
      "kind": "skin",
      "target": "Cornell Notes"
    },
    "research": {
      "kind": "skin",
      "target": "Cornell Notes"
    }
  },
  "formula_sheet": {
    "reference_sheet": {
      "kind": "skin",
      "target": "Formula Sheet"
    },
    "equation_cards": {
      "kind": "skin",
      "target": "Formula Sheet"
    },
    "exam_strip": {
      "kind": "skin",
      "target": "Formula Sheet"
    },
    "derivation": {
      "kind": "capability",
      "target": "Formula Sheet"
    },
    "unit_aware": {
      "kind": "capability",
      "target": "Formula Sheet"
    },
    "worked_example": {
      "kind": "capability",
      "target": "Formula Sheet"
    }
  },
  "grade_calc": {
    "pass_fail": {
      "kind": "skin",
      "target": "Grades"
    },
    "what_if": {
      "kind": "skin",
      "target": "Grades"
    },
    "rubric": {
      "kind": "new-widget",
      "target": "Rubric"
    },
    "dropped_scores": {
      "kind": "capability",
      "target": "Grades"
    },
    "curve_simulator": {
      "kind": "capability",
      "target": "Grades"
    }
  },
  "budget": {
    "category_plan": {
      "kind": "skin",
      "target": "Budget"
    },
    "envelope": {
      "kind": "skin",
      "target": "Budget"
    },
    "zero_based": {
      "kind": "preset",
      "target": "Budget"
    },
    "50_30_20": {
      "kind": "preset",
      "target": "Budget"
    },
    "cashflow": {
      "kind": "capability",
      "target": "Budget"
    },
    "sinking_funds": {
      "kind": "capability",
      "target": "Budget"
    },
    "shared_budget": {
      "kind": "capability",
      "target": "Budget"
    },
    "project_budget": {
      "kind": "capability",
      "target": "Budget"
    }
  },
  "calculator": {
    "basic": {
      "kind": "control",
      "target": "Calculator"
    },
    "scientific": {
      "kind": "control",
      "target": "Calculator"
    },
    "tape": {
      "kind": "control",
      "target": "Calculator"
    },
    "finance": {
      "kind": "new-widget",
      "target": "Finance Calculator"
    },
    "programmer": {
      "kind": "new-widget",
      "target": "Programmer Calculator"
    },
    "date_math": {
      "kind": "new-widget",
      "target": "Date Calculator"
    },
    "named_variables": {
      "kind": "control",
      "target": "Calculator"
    }
  },
  "bar_chart": {
    "area": {
      "kind": "skin",
      "target": "Chart"
    },
    "sparkline": {
      "kind": "skin",
      "target": "Chart"
    },
    "gauge": {
      "kind": "move",
      "target": "Metrics"
    },
    "progress_ring": {
      "kind": "move",
      "target": "Metrics"
    },
    "heatmap": {
      "kind": "new-widget",
      "target": "Heatmap"
    },
    "scatter": {
      "kind": "new-widget",
      "target": "Scatter Plot"
    },
    "stacked": {
      "kind": "capability",
      "target": "Chart"
    }
  },
  "form": {
    "intake": {
      "kind": "preset",
      "target": "Form"
    },
    "survey": {
      "kind": "preset",
      "target": "Form"
    },
    "feedback": {
      "kind": "preset",
      "target": "Form"
    },
    "rsvp": {
      "kind": "preset",
      "target": "Form"
    },
    "inspection": {
      "kind": "preset",
      "target": "Form"
    },
    "application": {
      "kind": "preset",
      "target": "Form"
    },
    "conditional_form": {
      "kind": "preset",
      "target": "Form"
    }
  },
  "formula": {
    "two_input": {
      "kind": "control",
      "target": "Formula"
    },
    "percent_change": {
      "kind": "control",
      "target": "Formula"
    },
    "ratio": {
      "kind": "control",
      "target": "Formula"
    },
    "growth": {
      "kind": "control",
      "target": "Formula"
    },
    "expression": {
      "kind": "control",
      "target": "Formula"
    },
    "weighted_score": {
      "kind": "move",
      "target": "Decision Matrix"
    },
    "conditional": {
      "kind": "control",
      "target": "Formula"
    }
  },
  "idempotency_store": {
    "duplicate_guard": {
      "kind": "control",
      "target": "Idempotency Store"
    },
    "request_ledger": {
      "kind": "control",
      "target": "Idempotency Store"
    },
    "import_guard": {
      "kind": "control",
      "target": "Idempotency Store"
    },
    "ttl_cache": {
      "kind": "control",
      "target": "Idempotency Store"
    },
    "result_cache": {
      "kind": "control",
      "target": "Idempotency Store"
    },
    "scoped_keys": {
      "kind": "control",
      "target": "Idempotency Store"
    }
  },
  "metrics": {
    "kpi_tiles": {
      "kind": "skin",
      "target": "Metrics"
    },
    "big_number": {
      "kind": "skin",
      "target": "Metrics"
    },
    "scoreboard": {
      "kind": "skin",
      "target": "Metrics"
    },
    "traffic_lights": {
      "kind": "skin",
      "target": "Metrics"
    },
    "delta": {
      "kind": "capability",
      "target": "Metrics"
    },
    "target": {
      "kind": "capability",
      "target": "Metrics"
    },
    "executive_strip": {
      "kind": "capability",
      "target": "Metrics"
    }
  },
  "mutex": {
    "lock": {
      "kind": "control",
      "target": "Mutex"
    },
    "critical_section": {
      "kind": "control",
      "target": "Mutex"
    },
    "semaphore": {
      "kind": "control",
      "target": "Mutex"
    },
    "keyed_lock": {
      "kind": "control",
      "target": "Mutex"
    },
    "lease": {
      "kind": "control",
      "target": "Mutex"
    },
    "fair_queue": {
      "kind": "control",
      "target": "Mutex"
    }
  },
  "number_input": {
    "stepper": {
      "kind": "skin",
      "target": "Number Input"
    },
    "slider": {
      "kind": "skin",
      "target": "Number Input"
    },
    "dial": {
      "kind": "skin",
      "target": "Number Input"
    },
    "currency": {
      "kind": "control",
      "target": "Number Input"
    },
    "percent": {
      "kind": "control",
      "target": "Number Input"
    },
    "duration": {
      "kind": "control",
      "target": "Number Input"
    },
    "range": {
      "kind": "capability",
      "target": "Number Input"
    }
  },
  "queue": {
    "fifo": {
      "kind": "control",
      "target": "Queue"
    },
    "inbox": {
      "kind": "control",
      "target": "Queue"
    },
    "work_queue": {
      "kind": "control",
      "target": "Queue"
    },
    "priority": {
      "kind": "control",
      "target": "Queue"
    },
    "delayed": {
      "kind": "control",
      "target": "Queue"
    },
    "dead_letter": {
      "kind": "control",
      "target": "Queue"
    },
    "assigned": {
      "kind": "control",
      "target": "Queue"
    }
  },
  "rating": {
    "stars": {
      "kind": "skin",
      "target": "Rating"
    },
    "slider": {
      "kind": "skin",
      "target": "Rating"
    },
    "emoji": {
      "kind": "skin",
      "target": "Rating"
    },
    "traffic_light": {
      "kind": "skin",
      "target": "Rating"
    },
    "nps": {
      "kind": "skin",
      "target": "Rating"
    },
    "rubric": {
      "kind": "capability",
      "target": "Rating"
    },
    "confidence": {
      "kind": "capability",
      "target": "Rating"
    }
  },
  "set_store": {
    "unique_values": {
      "kind": "control",
      "target": "Set Store"
    },
    "tags": {
      "kind": "control",
      "target": "Set Store"
    },
    "watchlist": {
      "kind": "control",
      "target": "Set Store"
    },
    "allowlist_denylist": {
      "kind": "control",
      "target": "Set Store"
    },
    "expiring_set": {
      "kind": "control",
      "target": "Set Store"
    },
    "annotated_set": {
      "kind": "control",
      "target": "Set Store"
    }
  },
  "stack_store": {
    "lifo": {
      "kind": "control",
      "target": "Stack"
    },
    "undo_history": {
      "kind": "control",
      "target": "Stack"
    },
    "breadcrumbs": {
      "kind": "control",
      "target": "Stack"
    },
    "recent_items": {
      "kind": "control",
      "target": "Stack"
    },
    "named_frames": {
      "kind": "control",
      "target": "Stack"
    },
    "checkpoint": {
      "kind": "control",
      "target": "Stack"
    }
  },
  "state_machine": {
    "workflow": {
      "kind": "control",
      "target": "State Machine"
    },
    "approval": {
      "kind": "move",
      "target": "Approval Gate"
    },
    "incident": {
      "kind": "move",
      "target": "Incident Response"
    },
    "order": {
      "kind": "control",
      "target": "State Machine"
    },
    "content": {
      "kind": "control",
      "target": "State Machine"
    },
    "diagram": {
      "kind": "control",
      "target": "State Machine"
    },
    "guarded": {
      "kind": "control",
      "target": "State Machine"
    }
  },
  "table": {
    "grid": {
      "kind": "skin",
      "target": "Table"
    },
    "compact_ledger": {
      "kind": "skin",
      "target": "Table"
    },
    "cards": {
      "kind": "skin",
      "target": "Table"
    },
    "database": {
      "kind": "new-widget",
      "target": "Database"
    },
    "kanban": {
      "kind": "new-widget",
      "target": "Database"
    },
    "gallery": {
      "kind": "new-widget",
      "target": "Database"
    },
    "form_view": {
      "kind": "new-widget",
      "target": "Database"
    },
    "pivot": {
      "kind": "new-widget",
      "target": "Database"
    }
  },
  "text_input": {
    "single_line": {
      "kind": "control",
      "target": "Text Input"
    },
    "multiline": {
      "kind": "control",
      "target": "Text Input"
    },
    "search": {
      "kind": "control",
      "target": "Text Input"
    },
    "url": {
      "kind": "control",
      "target": "Text Input"
    },
    "email": {
      "kind": "control",
      "target": "Text Input"
    },
    "tags": {
      "kind": "control",
      "target": "Text Input"
    },
    "command": {
      "kind": "control",
      "target": "Text Input"
    }
  },
  "toggle": {
    "switch": {
      "kind": "skin",
      "target": "Toggle"
    },
    "checkbox": {
      "kind": "skin",
      "target": "Toggle"
    },
    "power": {
      "kind": "skin",
      "target": "Toggle"
    },
    "segment": {
      "kind": "skin",
      "target": "Toggle"
    },
    "availability": {
      "kind": "skin",
      "target": "Toggle"
    },
    "tri_state": {
      "kind": "capability",
      "target": "Toggle"
    }
  },
  "unit_converter": {
    "general": {
      "kind": "control",
      "target": "Unit Converter"
    },
    "cooking": {
      "kind": "control",
      "target": "Unit Converter"
    },
    "engineering": {
      "kind": "control",
      "target": "Unit Converter"
    },
    "data": {
      "kind": "control",
      "target": "Unit Converter"
    },
    "temperature": {
      "kind": "control",
      "target": "Unit Converter"
    },
    "currency": {
      "kind": "control",
      "target": "Unit Converter"
    },
    "custom_formula": {
      "kind": "control",
      "target": "Unit Converter"
    }
  },
  "world_clock": {
    "city_grid": {
      "kind": "skin",
      "target": "World Clock"
    },
    "analog_wall": {
      "kind": "skin",
      "target": "World Clock"
    },
    "overlap_band": {
      "kind": "move",
      "target": "Overlap Finder"
    },
    "meeting_planner": {
      "kind": "move",
      "target": "Overlap Finder"
    },
    "travel_clock": {
      "kind": "move",
      "target": "Jet Lag Plan"
    },
    "sunlight": {
      "kind": "move",
      "target": "Sun Window"
    }
  },
  "ai_generator": {
    "brainstorm": {
      "kind": "control",
      "target": "AI Generator"
    },
    "rewrite": {
      "kind": "control",
      "target": "AI Generator"
    },
    "summarize": {
      "kind": "control",
      "target": "AI Generator"
    },
    "extract": {
      "kind": "control",
      "target": "AI Generator"
    },
    "classify": {
      "kind": "control",
      "target": "AI Generator"
    },
    "structured_output": {
      "kind": "control",
      "target": "AI Generator"
    },
    "prompt_lab": {
      "kind": "control",
      "target": "AI Generator"
    }
  },
  "color_palette": {
    "swatches": {
      "kind": "skin",
      "target": "Color Palette"
    },
    "gradient": {
      "kind": "skin",
      "target": "Color Palette"
    },
    "brand": {
      "kind": "skin",
      "target": "Color Palette"
    },
    "accessibility": {
      "kind": "skin",
      "target": "Color Palette"
    },
    "ramp": {
      "kind": "capability",
      "target": "Color Palette"
    },
    "image_extract": {
      "kind": "capability",
      "target": "Color Palette"
    },
    "design_tokens": {
      "kind": "capability",
      "target": "Color Palette"
    }
  },
  "dialog": {
    "screenplay": {
      "kind": "new-widget",
      "target": "Screenplay"
    },
    "chat": {
      "kind": "skin",
      "target": "Dialog"
    },
    "interview": {
      "kind": "skin",
      "target": "Dialog"
    },
    "roleplay": {
      "kind": "skin",
      "target": "Dialog"
    },
    "comic": {
      "kind": "capability",
      "target": "Dialog"
    },
    "localization": {
      "kind": "capability",
      "target": "Dialog"
    },
    "audio_transcript": {
      "kind": "new-widget",
      "target": "Transcript"
    }
  },
  "sketchpad": {
    "whiteboard": {
      "kind": "skin",
      "target": "Drawing"
    },
    "graph_paper": {
      "kind": "skin",
      "target": "Drawing"
    },
    "dot_grid": {
      "kind": "skin",
      "target": "Drawing"
    },
    "storyboard": {
      "kind": "capability",
      "target": "Drawing"
    },
    "annotation": {
      "kind": "capability",
      "target": "Drawing"
    }
  },
  "media": {
    "image": {
      "kind": "skin",
      "target": "Media"
    },
    "video": {
      "kind": "new-widget",
      "target": "Video Player"
    },
    "audio": {
      "kind": "move",
      "target": "Audio Player"
    },
    "document_preview": {
      "kind": "new-widget",
      "target": "Document Viewer"
    },
    "before_after": {
      "kind": "new-widget",
      "target": "Media Gallery"
    },
    "gallery": {
      "kind": "new-widget",
      "target": "Media Gallery"
    },
    "moodboard": {
      "kind": "new-widget",
      "target": "Media Gallery"
    }
  },
  "contact": {
    "personal": {
      "kind": "preset",
      "target": "Contact Card"
    },
    "business": {
      "kind": "preset",
      "target": "Contact Card"
    },
    "emergency": {
      "kind": "preset",
      "target": "Contact Card"
    },
    "vendor": {
      "kind": "preset",
      "target": "Contact Card"
    },
    "relationship": {
      "kind": "move",
      "target": "Keep in Touch"
    },
    "household": {
      "kind": "preset",
      "target": "Contact Card"
    },
    "care_contact": {
      "kind": "move",
      "target": "Care Plan"
    }
  },
  "counter": {
    "tally": {
      "kind": "skin",
      "target": "Counter"
    },
    "clicker": {
      "kind": "skin",
      "target": "Counter"
    },
    "goal_counter": {
      "kind": "skin",
      "target": "Counter"
    },
    "up_down": {
      "kind": "skin",
      "target": "Counter"
    },
    "multi_counter": {
      "kind": "new-widget",
      "target": "Multi-counter"
    },
    "timed_rate": {
      "kind": "new-widget",
      "target": "Rate Meter"
    },
    "resetting_period": {
      "kind": "capability",
      "target": "Counter"
    }
  },
  "goal_tracker": {
    "thermometer": {
      "kind": "skin",
      "target": "Goal"
    },
    "burn_up": {
      "kind": "skin",
      "target": "Goal"
    },
    "score_ring": {
      "kind": "skin",
      "target": "Goal"
    },
    "streak_goal": {
      "kind": "capability",
      "target": "Goal"
    },
    "savings_goal": {
      "kind": "capability",
      "target": "Goal"
    },
    "outcome_inputs": {
      "kind": "capability",
      "target": "Goal"
    }
  },
  "habit": {
    "week_grid": {
      "kind": "skin",
      "target": "Habit Tracker"
    },
    "month_heatmap": {
      "kind": "skin",
      "target": "Habit Tracker"
    },
    "chain": {
      "kind": "skin",
      "target": "Habit Tracker"
    },
    "scorecard": {
      "kind": "skin",
      "target": "Habit Tracker"
    },
    "routine_stack": {
      "kind": "capability",
      "target": "Habit Tracker"
    },
    "minimum_target": {
      "kind": "capability",
      "target": "Habit Tracker"
    },
    "flexible_frequency": {
      "kind": "capability",
      "target": "Habit Tracker"
    }
  },
  "inventory": {
    "stock_list": {
      "kind": "skin",
      "target": "Inventory"
    },
    "pantry": {
      "kind": "skin",
      "target": "Inventory"
    },
    "asset_register": {
      "kind": "new-widget",
      "target": "Asset Register"
    },
    "equipment_checkout": {
      "kind": "new-widget",
      "target": "Equipment Checkout"
    },
    "locations": {
      "kind": "skin",
      "target": "Inventory"
    },
    "batch_and_expiry": {
      "kind": "capability",
      "target": "Inventory"
    },
    "scan_first": {
      "kind": "capability",
      "target": "Inventory"
    }
  },
  "links": {
    "bookmark_grid": {
      "kind": "skin",
      "target": "Link List"
    },
    "reading_queue": {
      "kind": "preset",
      "target": "Link List"
    },
    "resource_list": {
      "kind": "preset",
      "target": "Link List"
    },
    "link_in_bio": {
      "kind": "preset",
      "target": "Link List"
    },
    "research_trail": {
      "kind": "capability",
      "target": "Link List"
    },
    "watch_later": {
      "kind": "move",
      "target": "Reading List"
    },
    "health_monitor": {
      "kind": "new-widget",
      "target": "URL Monitor"
    }
  },
  "mood_tracker": {
    "week_check_in": {
      "kind": "skin",
      "target": "Mood Tracker"
    },
    "month_heatmap": {
      "kind": "skin",
      "target": "Mood Tracker"
    },
    "mood_wheel": {
      "kind": "skin",
      "target": "Mood Tracker"
    },
    "mood_journal": {
      "kind": "capability",
      "target": "Mood Tracker"
    },
    "energy_matrix": {
      "kind": "capability",
      "target": "Mood Tracker"
    },
    "trend": {
      "kind": "capability",
      "target": "Mood Tracker"
    }
  },
  "reading_list": {
    "bookshelf": {
      "kind": "skin",
      "target": "Reading List"
    },
    "reading_queue": {
      "kind": "skin",
      "target": "Reading List"
    },
    "curriculum": {
      "kind": "skin",
      "target": "Reading List"
    },
    "reference_library": {
      "kind": "skin",
      "target": "Reading List"
    },
    "reading_log": {
      "kind": "capability",
      "target": "Reading List"
    },
    "citation_trail": {
      "kind": "capability",
      "target": "Reading List"
    }
  },
  "status": {
    "badge": {
      "kind": "skin",
      "target": "Status"
    },
    "traffic_light": {
      "kind": "skin",
      "target": "Status"
    },
    "progress": {
      "kind": "skin",
      "target": "Status"
    },
    "pipeline": {
      "kind": "skin",
      "target": "Status"
    },
    "availability": {
      "kind": "skin",
      "target": "Status"
    },
    "approval": {
      "kind": "move",
      "target": "Approval Gate"
    },
    "service_health": {
      "kind": "new-widget",
      "target": "Service Status"
    }
  },
  "timekeeper": {
    "hourglass": {
      "kind": "skin",
      "target": "Timer"
    },
    "intervals": {
      "kind": "new-widget",
      "target": "Interval Timer"
    },
    "tabata": {
      "kind": "new-widget",
      "target": "Interval Timer"
    },
    "chess_clock": {
      "kind": "new-widget",
      "target": "Chess Clock"
    },
    "lap_timer": {
      "kind": "move",
      "target": "Stopwatch"
    },
    "multi_stage_timer": {
      "kind": "new-widget",
      "target": "Interval Timer"
    }
  },
  "timesheet": {
    "daily": {
      "kind": "skin",
      "target": "Timesheet"
    },
    "weekly": {
      "kind": "skin",
      "target": "Timesheet"
    },
    "project": {
      "kind": "skin",
      "target": "Timesheet"
    },
    "client": {
      "kind": "skin",
      "target": "Timesheet"
    },
    "shift": {
      "kind": "skin",
      "target": "Timesheet"
    },
    "timer": {
      "kind": "capability",
      "target": "Timesheet"
    },
    "approval": {
      "kind": "capability",
      "target": "Timesheet"
    }
  },
  "aggregator": {
    "average": {
      "kind": "control",
      "target": "Aggregator"
    },
    "sum": {
      "kind": "control",
      "target": "Aggregator"
    },
    "minimum_maximum": {
      "kind": "control",
      "target": "Aggregator"
    },
    "count": {
      "kind": "control",
      "target": "Aggregator"
    },
    "any_all": {
      "kind": "control",
      "target": "Aggregator"
    },
    "weighted": {
      "kind": "control",
      "target": "Aggregator"
    },
    "rolling_window": {
      "kind": "control",
      "target": "Aggregator"
    }
  },
  "approval_gate": {
    "manual": {
      "kind": "control",
      "target": "Approval Gate"
    },
    "preview": {
      "kind": "control",
      "target": "Approval Gate"
    },
    "two_person": {
      "kind": "control",
      "target": "Approval Gate"
    },
    "quorum": {
      "kind": "control",
      "target": "Approval Gate"
    },
    "timeout": {
      "kind": "control",
      "target": "Approval Gate"
    },
    "policy": {
      "kind": "control",
      "target": "Approval Gate"
    }
  },
  "comparator": {
    "threshold": {
      "kind": "control",
      "target": "Comparator"
    },
    "range": {
      "kind": "control",
      "target": "Comparator"
    },
    "equality": {
      "kind": "control",
      "target": "Comparator"
    },
    "gap": {
      "kind": "control",
      "target": "Comparator"
    },
    "hysteresis": {
      "kind": "control",
      "target": "Comparator"
    },
    "change": {
      "kind": "control",
      "target": "Comparator"
    },
    "freshness": {
      "kind": "control",
      "target": "Comparator"
    }
  },
  "http_request": {
    "rest": {
      "kind": "control",
      "target": "HTTP Request"
    },
    "health_check": {
      "kind": "new-widget",
      "target": "URL Monitor"
    },
    "form_post": {
      "kind": "control",
      "target": "HTTP Request"
    },
    "graphql": {
      "kind": "control",
      "target": "HTTP Request"
    },
    "file_upload": {
      "kind": "control",
      "target": "HTTP Request"
    },
    "pagination": {
      "kind": "control",
      "target": "HTTP Request"
    },
    "authenticated": {
      "kind": "control",
      "target": "HTTP Request"
    }
  },
  "notifier": {
    "in_app": {
      "kind": "control",
      "target": "Notifier"
    },
    "system": {
      "kind": "control",
      "target": "Notifier"
    },
    "banner": {
      "kind": "control",
      "target": "Notifier"
    },
    "reminder": {
      "kind": "control",
      "target": "Notifier"
    },
    "escalation": {
      "kind": "control",
      "target": "Notifier"
    },
    "digest": {
      "kind": "control",
      "target": "Notifier"
    },
    "quiet_hours": {
      "kind": "control",
      "target": "Notifier"
    }
  },
  "range_mapper": {
    "bands": {
      "kind": "control",
      "target": "Range Mapper"
    },
    "gauge_labels": {
      "kind": "control",
      "target": "Range Mapper"
    },
    "grade": {
      "kind": "control",
      "target": "Range Mapper"
    },
    "priority": {
      "kind": "control",
      "target": "Range Mapper"
    },
    "risk": {
      "kind": "control",
      "target": "Range Mapper"
    },
    "gradient": {
      "kind": "control",
      "target": "Range Mapper"
    },
    "lookup": {
      "kind": "control",
      "target": "Range Mapper"
    }
  },
  "recorder": {
    "event_log": {
      "kind": "skin",
      "target": "Recorder"
    },
    "trend": {
      "kind": "skin",
      "target": "Recorder"
    },
    "daily_snapshot": {
      "kind": "skin",
      "target": "Recorder"
    },
    "min_max": {
      "kind": "skin",
      "target": "Recorder"
    },
    "rolling_window": {
      "kind": "capability",
      "target": "Recorder"
    },
    "audit": {
      "kind": "capability",
      "target": "Recorder"
    },
    "distribution": {
      "kind": "capability",
      "target": "Recorder"
    }
  },
  "clock_pulse": {
    "once": {
      "kind": "control",
      "target": "Schedule Pulse"
    },
    "interval": {
      "kind": "control",
      "target": "Schedule Pulse"
    },
    "daily": {
      "kind": "control",
      "target": "Schedule Pulse"
    },
    "weekly": {
      "kind": "control",
      "target": "Schedule Pulse"
    },
    "business_hours": {
      "kind": "control",
      "target": "Schedule Pulse"
    },
    "cron": {
      "kind": "control",
      "target": "Schedule Pulse"
    },
    "solar": {
      "kind": "move",
      "target": "Sun Window"
    }
  },
  "sequencer": {
    "steps": {
      "kind": "control",
      "target": "Sequencer"
    },
    "round_robin": {
      "kind": "control",
      "target": "Sequencer"
    },
    "playlist": {
      "kind": "control",
      "target": "Sequencer"
    },
    "wizard": {
      "kind": "control",
      "target": "Sequencer"
    },
    "state_timeline": {
      "kind": "control",
      "target": "Sequencer"
    },
    "conditional_sequence": {
      "kind": "control",
      "target": "Sequencer"
    }
  },
  "latch": {
    "baseline": {
      "kind": "control",
      "target": "Snapshot Latch"
    },
    "before_after": {
      "kind": "control",
      "target": "Snapshot Latch"
    },
    "peak_hold": {
      "kind": "control",
      "target": "Snapshot Latch"
    },
    "last_known_good": {
      "kind": "control",
      "target": "Snapshot Latch"
    },
    "snapshot_history": {
      "kind": "control",
      "target": "Snapshot Latch"
    },
    "change_detector": {
      "kind": "control",
      "target": "Snapshot Latch"
    }
  },
  "template": {
    "sentence": {
      "kind": "control",
      "target": "Text Composer"
    },
    "email": {
      "kind": "control",
      "target": "Text Composer"
    },
    "notification": {
      "kind": "control",
      "target": "Text Composer"
    },
    "url_builder": {
      "kind": "control",
      "target": "Text Composer"
    },
    "filename": {
      "kind": "control",
      "target": "Text Composer"
    },
    "json": {
      "kind": "control",
      "target": "Text Composer"
    },
    "markdown": {
      "kind": "control",
      "target": "Text Composer"
    }
  },
  "webhook_sender": {
    "json": {
      "kind": "control",
      "target": "Webhook Sender"
    },
    "form_payload": {
      "kind": "control",
      "target": "Webhook Sender"
    },
    "event_envelope": {
      "kind": "control",
      "target": "Webhook Sender"
    },
    "signed": {
      "kind": "control",
      "target": "Webhook Sender"
    },
    "retrying": {
      "kind": "control",
      "target": "Webhook Sender"
    },
    "batch": {
      "kind": "control",
      "target": "Webhook Sender"
    },
    "connector_message": {
      "kind": "control",
      "target": "Webhook Sender"
    }
  },
  "widget_creator": {
    "single": {
      "kind": "control",
      "target": "Widget Creator"
    },
    "from_form": {
      "kind": "control",
      "target": "Widget Creator"
    },
    "from_template": {
      "kind": "control",
      "target": "Widget Creator"
    },
    "batch": {
      "kind": "control",
      "target": "Widget Creator"
    },
    "scheduled": {
      "kind": "control",
      "target": "Widget Creator"
    },
    "child_canvas": {
      "kind": "control",
      "target": "Widget Creator"
    }
  },
  "workflow_lock": {
    "guard": {
      "kind": "control",
      "target": "Workflow Lock"
    },
    "maintenance": {
      "kind": "control",
      "target": "Workflow Lock"
    },
    "emergency_stop": {
      "kind": "control",
      "target": "Workflow Lock"
    },
    "lease": {
      "kind": "control",
      "target": "Workflow Lock"
    },
    "owner_lock": {
      "kind": "control",
      "target": "Workflow Lock"
    },
    "rate_window": {
      "kind": "control",
      "target": "Workflow Lock"
    }
  },
  "chore_rotation": {
    "weekly": {
      "kind": "skin",
      "target": "Chore Rotation"
    },
    "zones": {
      "kind": "skin",
      "target": "Chore Rotation"
    },
    "fairness": {
      "kind": "skin",
      "target": "Chore Rotation"
    },
    "kids": {
      "kind": "skin",
      "target": "Chore Rotation"
    },
    "points": {
      "kind": "capability",
      "target": "Chore Rotation"
    },
    "availability": {
      "kind": "capability",
      "target": "Chore Rotation"
    },
    "shift": {
      "kind": "capability",
      "target": "Chore Rotation"
    }
  },
  "debt_payoff": {
    "snowball": {
      "kind": "skin",
      "target": "Debt Payoff"
    },
    "avalanche": {
      "kind": "skin",
      "target": "Debt Payoff"
    },
    "timeline": {
      "kind": "skin",
      "target": "Debt Payoff"
    },
    "motivation": {
      "kind": "skin",
      "target": "Debt Payoff"
    },
    "hybrid": {
      "kind": "capability",
      "target": "Debt Payoff"
    },
    "payment_planner": {
      "kind": "capability",
      "target": "Debt Payoff"
    }
  },
  "decision_journal": {
    "decision_card": {
      "kind": "skin",
      "target": "Decision Journal"
    },
    "review_queue": {
      "kind": "skin",
      "target": "Decision Journal"
    },
    "predictions": {
      "kind": "skin",
      "target": "Decision Journal"
    },
    "lessons": {
      "kind": "skin",
      "target": "Decision Journal"
    },
    "bias_check": {
      "kind": "capability",
      "target": "Decision Journal"
    },
    "outcome_score": {
      "kind": "capability",
      "target": "Decision Journal"
    },
    "recurring_decision": {
      "kind": "capability",
      "target": "Decision Journal"
    }
  },
  "expense_split": {
    "equal": {
      "kind": "skin",
      "target": "Expense Split"
    },
    "shares": {
      "kind": "skin",
      "target": "Expense Split"
    },
    "percentages": {
      "kind": "skin",
      "target": "Expense Split"
    },
    "settlement": {
      "kind": "skin",
      "target": "Expense Split"
    },
    "trip": {
      "kind": "capability",
      "target": "Expense Split"
    },
    "household": {
      "kind": "capability",
      "target": "Expense Split"
    },
    "event": {
      "kind": "capability",
      "target": "Expense Split"
    }
  },
  "gifts_occasions": {
    "timeline": {
      "kind": "skin",
      "target": "Gifts & Occasions"
    },
    "ideas": {
      "kind": "skin",
      "target": "Gifts & Occasions"
    },
    "budget": {
      "kind": "skin",
      "target": "Gifts & Occasions"
    },
    "purchased": {
      "kind": "skin",
      "target": "Gifts & Occasions"
    },
    "family": {
      "kind": "capability",
      "target": "Gifts & Occasions"
    },
    "shipping": {
      "kind": "capability",
      "target": "Gifts & Occasions"
    },
    "traditions": {
      "kind": "capability",
      "target": "Gifts & Occasions"
    }
  },
  "guest_list": {
    "rsvp": {
      "kind": "skin",
      "target": "Guest List"
    },
    "dietary": {
      "kind": "skin",
      "target": "Guest List"
    },
    "check_in": {
      "kind": "skin",
      "target": "Guest List"
    },
    "households": {
      "kind": "skin",
      "target": "Guest List"
    },
    "capacity": {
      "kind": "skin",
      "target": "Guest List"
    },
    "seating": {
      "kind": "capability",
      "target": "Guest List"
    },
    "communication": {
      "kind": "capability",
      "target": "Guest List"
    }
  },
  "home_maintenance": {
    "due_soon": {
      "kind": "skin",
      "target": "Home Maintenance"
    },
    "calendar": {
      "kind": "skin",
      "target": "Home Maintenance"
    },
    "by_room": {
      "kind": "skin",
      "target": "Home Maintenance"
    },
    "seasonal": {
      "kind": "skin",
      "target": "Home Maintenance"
    },
    "asset": {
      "kind": "capability",
      "target": "Home Maintenance"
    },
    "contractor": {
      "kind": "capability",
      "target": "Home Maintenance"
    },
    "history": {
      "kind": "capability",
      "target": "Home Maintenance"
    }
  },
  "invoices": {
    "receivables": {
      "kind": "skin",
      "target": "Invoices"
    },
    "payables": {
      "kind": "skin",
      "target": "Invoices"
    },
    "aging": {
      "kind": "skin",
      "target": "Invoices"
    },
    "pipeline": {
      "kind": "skin",
      "target": "Invoices"
    },
    "cashflow": {
      "kind": "capability",
      "target": "Invoices"
    },
    "client": {
      "kind": "capability",
      "target": "Invoices"
    },
    "recurring": {
      "kind": "capability",
      "target": "Invoices"
    }
  },
  "job_applications": {
    "pipeline": {
      "kind": "skin",
      "target": "Job Applications"
    },
    "follow_up": {
      "kind": "skin",
      "target": "Job Applications"
    },
    "calendar": {
      "kind": "skin",
      "target": "Job Applications"
    },
    "companies": {
      "kind": "skin",
      "target": "Job Applications"
    },
    "interview_prep": {
      "kind": "capability",
      "target": "Job Applications"
    },
    "offer_compare": {
      "kind": "capability",
      "target": "Job Applications"
    },
    "networking": {
      "kind": "capability",
      "target": "Job Applications"
    }
  },
  "keep_in_touch": {
    "queue": {
      "kind": "skin",
      "target": "Keep in Touch"
    },
    "radar": {
      "kind": "skin",
      "target": "Keep in Touch"
    },
    "calendar": {
      "kind": "skin",
      "target": "Keep in Touch"
    },
    "circles": {
      "kind": "skin",
      "target": "Keep in Touch"
    },
    "reciprocity": {
      "kind": "capability",
      "target": "Keep in Touch"
    },
    "conversation_notes": {
      "kind": "capability",
      "target": "Keep in Touch"
    },
    "crm": {
      "kind": "capability",
      "target": "Keep in Touch"
    }
  },
  "meal_planner": {
    "week": {
      "kind": "skin",
      "target": "Meal Planner"
    },
    "today": {
      "kind": "skin",
      "target": "Meal Planner"
    },
    "batch_cooking": {
      "kind": "skin",
      "target": "Meal Planner"
    },
    "pantry_first": {
      "kind": "skin",
      "target": "Meal Planner"
    },
    "nutrition": {
      "kind": "capability",
      "target": "Meal Planner"
    },
    "family_vote": {
      "kind": "capability",
      "target": "Meal Planner"
    },
    "leftovers": {
      "kind": "capability",
      "target": "Meal Planner"
    }
  },
  "medications": {
    "today": {
      "kind": "skin",
      "target": "Medications"
    },
    "schedule": {
      "kind": "skin",
      "target": "Medications"
    },
    "refills": {
      "kind": "skin",
      "target": "Medications"
    },
    "travel": {
      "kind": "skin",
      "target": "Medications"
    },
    "as_needed": {
      "kind": "capability",
      "target": "Medications"
    },
    "caregiver": {
      "kind": "capability",
      "target": "Medications"
    },
    "adherence": {
      "kind": "capability",
      "target": "Medications"
    }
  },
  "recipe": {
    "cook": {
      "kind": "skin",
      "target": "Recipe"
    },
    "scale": {
      "kind": "skin",
      "target": "Recipe"
    },
    "mise_en_place": {
      "kind": "skin",
      "target": "Recipe"
    },
    "step_timer": {
      "kind": "skin",
      "target": "Recipe"
    },
    "shopping": {
      "kind": "skin",
      "target": "Recipe"
    },
    "nutrition": {
      "kind": "capability",
      "target": "Recipe"
    },
    "cost": {
      "kind": "capability",
      "target": "Recipe"
    }
  },
  "renewals_vault": {
    "timeline": {
      "kind": "skin",
      "target": "Renewals Vault"
    },
    "wallet": {
      "kind": "skin",
      "target": "Renewals Vault"
    },
    "compliance": {
      "kind": "skin",
      "target": "Renewals Vault"
    },
    "annual_cost": {
      "kind": "skin",
      "target": "Renewals Vault"
    },
    "documents": {
      "kind": "capability",
      "target": "Renewals Vault"
    },
    "workflow": {
      "kind": "capability",
      "target": "Renewals Vault"
    }
  },
  "snippet_library": {
    "code": {
      "kind": "preset",
      "target": "Snippet Library"
    },
    "writing": {
      "kind": "preset",
      "target": "Snippet Library"
    },
    "support_replies": {
      "kind": "preset",
      "target": "Snippet Library"
    },
    "prompts": {
      "kind": "preset",
      "target": "Snippet Library"
    },
    "commands": {
      "kind": "preset",
      "target": "Snippet Library"
    },
    "variables": {
      "kind": "preset",
      "target": "Snippet Library"
    },
    "usage": {
      "kind": "preset",
      "target": "Snippet Library"
    }
  },
  "subscriptions": {
    "list": {
      "kind": "skin",
      "target": "Subscriptions"
    },
    "cost_breakdown": {
      "kind": "skin",
      "target": "Subscriptions"
    },
    "renewal_calendar": {
      "kind": "skin",
      "target": "Subscriptions"
    },
    "audit": {
      "kind": "skin",
      "target": "Subscriptions"
    },
    "household": {
      "kind": "capability",
      "target": "Subscriptions"
    },
    "usage_value": {
      "kind": "capability",
      "target": "Subscriptions"
    }
  },
  "trip_itinerary": {
    "days": {
      "kind": "skin",
      "target": "Trip Itinerary"
    },
    "timeline": {
      "kind": "skin",
      "target": "Trip Itinerary"
    },
    "bookings": {
      "kind": "skin",
      "target": "Trip Itinerary"
    },
    "offline": {
      "kind": "skin",
      "target": "Trip Itinerary"
    },
    "map": {
      "kind": "capability",
      "target": "Trip Itinerary"
    },
    "group": {
      "kind": "capability",
      "target": "Trip Itinerary"
    },
    "travel_day": {
      "kind": "capability",
      "target": "Trip Itinerary"
    }
  },
  "weekly_review": {
    "guided": {
      "kind": "preset",
      "target": "Weekly Review"
    },
    "scorecard": {
      "kind": "preset",
      "target": "Weekly Review"
    },
    "wins_lessons": {
      "kind": "preset",
      "target": "Weekly Review"
    },
    "gtd": {
      "kind": "preset",
      "target": "Weekly Review"
    },
    "team": {
      "kind": "preset",
      "target": "Weekly Review"
    },
    "monthly": {
      "kind": "preset",
      "target": "Weekly Review"
    },
    "life_areas": {
      "kind": "preset",
      "target": "Weekly Review"
    }
  },
  "workout_plan": {
    "plan": {
      "kind": "skin",
      "target": "Workout Plan"
    },
    "session": {
      "kind": "skin",
      "target": "Workout Plan"
    },
    "circuit": {
      "kind": "skin",
      "target": "Workout Plan"
    },
    "strength": {
      "kind": "preset",
      "target": "Workout Plan"
    },
    "cardio": {
      "kind": "preset",
      "target": "Workout Plan"
    },
    "mobility": {
      "kind": "preset",
      "target": "Workout Plan"
    },
    "progress": {
      "kind": "capability",
      "target": "Workout Plan"
    }
  },
  "game_tuner": {
    "character": {
      "kind": "preset",
      "target": "Game Mechanics Tuner"
    },
    "vehicle": {
      "kind": "preset",
      "target": "Game Mechanics Tuner"
    },
    "camera": {
      "kind": "preset",
      "target": "Game Mechanics Tuner"
    },
    "combat": {
      "kind": "preset",
      "target": "Game Mechanics Tuner"
    },
    "difficulty": {
      "kind": "preset",
      "target": "Game Mechanics Tuner"
    },
    "economy": {
      "kind": "preset",
      "target": "Game Mechanics Tuner"
    },
    "controller_feel": {
      "kind": "preset",
      "target": "Game Mechanics Tuner"
    }
  },
  "audio_player": {
    "player": {
      "kind": "skin",
      "target": "Synthesizer & Audio Player"
    },
    "synth": {
      "kind": "new-widget",
      "target": "Synthesizer"
    },
    "metronome": {
      "kind": "new-widget",
      "target": "Metronome"
    },
    "loop": {
      "kind": "control",
      "target": "Synthesizer & Audio Player"
    },
    "sampler": {
      "kind": "new-widget",
      "target": "Sampler"
    },
    "podcast": {
      "kind": "preset",
      "target": "Synthesizer & Audio Player"
    },
    "a_b_compare": {
      "kind": "new-widget",
      "target": "Audio Compare"
    }
  }
} as const satisfies Record<
  string,
  Readonly<Record<string, SkinOwnership>>
>
