// GENERATED by apple/Yrs/build-xcframework.sh (uniffi-bindgen, library mode). Do not edit.
// swiftlint:disable all
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(grovepad_yrsFFI)
import grovepad_yrsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_grovepad_yrs_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_grovepad_yrs_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureGrovepadYrsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * One canvas's shared document plus its collaborative undo manager.
 */
public protocol CanvasCrdtProtocol: AnyObject, Sendable {
    
    /**
     * Apply this person's edits in one transaction with the local-store
     * origin. Returns the update to send, empty when nothing changed.
     */
    func applyLocalEdits(edits: [CrdtEdit]) throws  -> Data
    
    /**
     * Apply edits that must not be undoable or re-sent (the empty-canvas seed
     * a read-only role writes when the server has nothing yet).
     */
    func applyRemoteEdits(edits: [CrdtEdit]) throws 
    
    /**
     * `Y.applyUpdate(doc, update, REMOTE_TRANSPORT_ORIGIN)`.
     */
    func applyRemoteUpdate(update: Data) throws 
    
    /**
     * Whether `redo` would do anything.
     */
    func canRedo()  -> Bool
    
    /**
     * Whether `undo` would do anything.
     */
    func canUndo()  -> Bool
    
    /**
     * `undoManager.clear()`.
     */
    func clearUndoHistory() 
    
    /**
     * `doc.clientID`, also the awareness client id.
     */
    func clientId()  -> UInt64
    
    /**
     * `Y.encodeStateAsUpdate(doc)`.
     */
    func encodeStateAsUpdate()  -> Data
    
    /**
     * Everything the document holds, for validation.
     */
    func readSnapshot()  -> CrdtSnapshot
    
    /**
     * Collaborative redo.
     */
    func redo()  -> Data
    
    /**
     * Collaborative undo of this person's last captured change. Returns the
     * update to send (empty when there was nothing to undo).
     */
    func undo()  -> Data
    
}
/**
 * One canvas's shared document plus its collaborative undo manager.
 */
open class CanvasCrdt: CanvasCrdtProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_grovepad_yrs_fn_clone_canvascrdt(self.handle, $0) }
    }
    /**
     * A fresh document. Swift passes a random 32-bit `client_id`, the range
     * `new Y.Doc()` draws from, so awareness ids stay small JavaScript numbers.
     */
public convenience init(clientId: UInt64) {
    let handle =
        try! rustCall() {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_constructor_canvascrdt_new(
        FfiConverterUInt64.lower(clientId),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_grovepad_yrs_fn_free_canvascrdt(handle, $0) }
    }

    

    
    /**
     * Apply this person's edits in one transaction with the local-store
     * origin. Returns the update to send, empty when nothing changed.
     */
open func applyLocalEdits(edits: [CrdtEdit])throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCrdtError_lift) {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_apply_local_edits(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeCrdtEdit.lower(edits),uniffiCallStatus
    )
})
}
    
    /**
     * Apply edits that must not be undoable or re-sent (the empty-canvas seed
     * a read-only role writes when the server has nothing yet).
     */
open func applyRemoteEdits(edits: [CrdtEdit])throws   {try rustCallWithError(FfiConverterTypeCrdtError_lift) {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_apply_remote_edits(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeCrdtEdit.lower(edits),uniffiCallStatus
    )
}
}
    
    /**
     * `Y.applyUpdate(doc, update, REMOTE_TRANSPORT_ORIGIN)`.
     */
open func applyRemoteUpdate(update: Data)throws   {try rustCallWithError(FfiConverterTypeCrdtError_lift) {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_apply_remote_update(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(update),uniffiCallStatus
    )
}
}
    
    /**
     * Whether `redo` would do anything.
     */
open func canRedo() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_can_redo(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Whether `undo` would do anything.
     */
open func canUndo() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_can_undo(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * `undoManager.clear()`.
     */
open func clearUndoHistory()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_clear_undo_history(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
    /**
     * `doc.clientID`, also the awareness client id.
     */
open func clientId() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_client_id(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * `Y.encodeStateAsUpdate(doc)`.
     */
open func encodeStateAsUpdate() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_encode_state_as_update(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Everything the document holds, for validation.
     */
open func readSnapshot() -> CrdtSnapshot  {
    return try!  FfiConverterTypeCrdtSnapshot_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_read_snapshot(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Collaborative redo.
     */
open func redo() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_redo(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Collaborative undo of this person's last captured change. Returns the
     * update to send (empty when there was nothing to undo).
     */
open func undo() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_method_canvascrdt_undo(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCanvasCrdt: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CanvasCrdt

    public static func lift(_ handle: UInt64) throws -> CanvasCrdt {
        return CanvasCrdt(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CanvasCrdt) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CanvasCrdt {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CanvasCrdt, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCanvasCrdt_lift(_ handle: UInt64) throws -> CanvasCrdt {
    return try FfiConverterTypeCanvasCrdt.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCanvasCrdt_lower(_ value: CanvasCrdt) -> UInt64 {
    return FfiConverterTypeCanvasCrdt.lower(value)
}




/**
 * One JSON-valued field of a record.
 */
public struct CrdtField: Equatable, Hashable {
    /**
     * The property name.
     */
    public var key: String
    /**
     * The value, as JSON text.
     */
    public var json: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The property name.
         */key: String, 
        /**
         * The value, as JSON text.
         */json: String) {
        self.key = key
        self.json = json
    }

    

    
}

#if compiler(>=6)
extension CrdtField: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrdtField: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CrdtField {
        return
            try CrdtField(
                key: FfiConverterString.read(from: &buf), 
                json: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CrdtField, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.json, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtField_lift(_ buf: RustBuffer) throws -> CrdtField {
    return try FfiConverterTypeCrdtField.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtField_lower(_ value: CrdtField) -> RustBuffer {
    return FfiConverterTypeCrdtField.lower(value)
}


/**
 * One record read out of the document.
 */
public struct CrdtRecord: Equatable, Hashable {
    /**
     * The key under the root map (the record id).
     */
    public var id: String
    /**
     * Every field, as JSON.
     */
    public var fields: [CrdtField]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The key under the root map (the record id).
         */id: String, 
        /**
         * Every field, as JSON.
         */fields: [CrdtField]) {
        self.id = id
        self.fields = fields
    }

    

    
}

#if compiler(>=6)
extension CrdtRecord: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrdtRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CrdtRecord {
        return
            try CrdtRecord(
                id: FfiConverterString.read(from: &buf), 
                fields: FfiConverterSequenceTypeCrdtField.read(from: &buf)
        )
    }

    public static func write(_ value: CrdtRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterSequenceTypeCrdtField.write(value.fields, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtRecord_lift(_ buf: RustBuffer) throws -> CrdtRecord {
    return try FfiConverterTypeCrdtRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtRecord_lower(_ value: CrdtRecord) -> RustBuffer {
    return FfiConverterTypeCrdtRecord.lower(value)
}


/**
 * Everything in the document, unvalidated. Swift runs it through the board
 * parser before it reaches the store, as `readCanvasSnapshot` does.
 */
public struct CrdtSnapshot: Equatable, Hashable {
    /**
     * `canvas` root fields.
     */
    public var canvas: [CrdtField]
    /**
     * Record counts per root, including entries that are not maps (the web
     * bounds `root.size`, not the number of usable records).
     */
    public var widgetCount: UInt32
    /**
     * See `widget_count`.
     */
    public var relationCount: UInt32
    /**
     * See `widget_count`.
     */
    public var connectionCount: UInt32
    /**
     * See `widget_count`.
     */
    public var glueCount: UInt32
    /**
     * See `widget_count`.
     */
    public var textCount: UInt32
    /**
     * Widget records (entries that are `Y.Map`s).
     */
    public var widgets: [CrdtRecord]
    /**
     * Relation records.
     */
    public var relations: [CrdtRecord]
    /**
     * Connection records.
     */
    public var connections: [CrdtRecord]
    /**
     * Glue records.
     */
    public var glues: [CrdtRecord]
    /**
     * Note bodies (entries that are `Y.Text`s).
     */
    public var texts: [CrdtText]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * `canvas` root fields.
         */canvas: [CrdtField], 
        /**
         * Record counts per root, including entries that are not maps (the web
         * bounds `root.size`, not the number of usable records).
         */widgetCount: UInt32, 
        /**
         * See `widget_count`.
         */relationCount: UInt32, 
        /**
         * See `widget_count`.
         */connectionCount: UInt32, 
        /**
         * See `widget_count`.
         */glueCount: UInt32, 
        /**
         * See `widget_count`.
         */textCount: UInt32, 
        /**
         * Widget records (entries that are `Y.Map`s).
         */widgets: [CrdtRecord], 
        /**
         * Relation records.
         */relations: [CrdtRecord], 
        /**
         * Connection records.
         */connections: [CrdtRecord], 
        /**
         * Glue records.
         */glues: [CrdtRecord], 
        /**
         * Note bodies (entries that are `Y.Text`s).
         */texts: [CrdtText]) {
        self.canvas = canvas
        self.widgetCount = widgetCount
        self.relationCount = relationCount
        self.connectionCount = connectionCount
        self.glueCount = glueCount
        self.textCount = textCount
        self.widgets = widgets
        self.relations = relations
        self.connections = connections
        self.glues = glues
        self.texts = texts
    }

    

    
}

#if compiler(>=6)
extension CrdtSnapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrdtSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CrdtSnapshot {
        return
            try CrdtSnapshot(
                canvas: FfiConverterSequenceTypeCrdtField.read(from: &buf), 
                widgetCount: FfiConverterUInt32.read(from: &buf), 
                relationCount: FfiConverterUInt32.read(from: &buf), 
                connectionCount: FfiConverterUInt32.read(from: &buf), 
                glueCount: FfiConverterUInt32.read(from: &buf), 
                textCount: FfiConverterUInt32.read(from: &buf), 
                widgets: FfiConverterSequenceTypeCrdtRecord.read(from: &buf), 
                relations: FfiConverterSequenceTypeCrdtRecord.read(from: &buf), 
                connections: FfiConverterSequenceTypeCrdtRecord.read(from: &buf), 
                glues: FfiConverterSequenceTypeCrdtRecord.read(from: &buf), 
                texts: FfiConverterSequenceTypeCrdtText.read(from: &buf)
        )
    }

    public static func write(_ value: CrdtSnapshot, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeCrdtField.write(value.canvas, into: &buf)
        FfiConverterUInt32.write(value.widgetCount, into: &buf)
        FfiConverterUInt32.write(value.relationCount, into: &buf)
        FfiConverterUInt32.write(value.connectionCount, into: &buf)
        FfiConverterUInt32.write(value.glueCount, into: &buf)
        FfiConverterUInt32.write(value.textCount, into: &buf)
        FfiConverterSequenceTypeCrdtRecord.write(value.widgets, into: &buf)
        FfiConverterSequenceTypeCrdtRecord.write(value.relations, into: &buf)
        FfiConverterSequenceTypeCrdtRecord.write(value.connections, into: &buf)
        FfiConverterSequenceTypeCrdtRecord.write(value.glues, into: &buf)
        FfiConverterSequenceTypeCrdtText.write(value.texts, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtSnapshot_lift(_ buf: RustBuffer) throws -> CrdtSnapshot {
    return try FfiConverterTypeCrdtSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtSnapshot_lower(_ value: CrdtSnapshot) -> RustBuffer {
    return FfiConverterTypeCrdtSnapshot.lower(value)
}


/**
 * One collaborative note body.
 */
public struct CrdtText: Equatable, Hashable {
    /**
     * The widget id it belongs to.
     */
    public var id: String
    /**
     * The text.
     */
    public var text: String
    /**
     * Length in UTF-16 code units, the unit JavaScript's `Y.Text.length` uses.
     */
    public var utf16Length: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The widget id it belongs to.
         */id: String, 
        /**
         * The text.
         */text: String, 
        /**
         * Length in UTF-16 code units, the unit JavaScript's `Y.Text.length` uses.
         */utf16Length: UInt32) {
        self.id = id
        self.text = text
        self.utf16Length = utf16Length
    }

    

    
}

#if compiler(>=6)
extension CrdtText: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrdtText: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CrdtText {
        return
            try CrdtText(
                id: FfiConverterString.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                utf16Length: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: CrdtText, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterUInt32.write(value.utf16Length, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtText_lift(_ buf: RustBuffer) throws -> CrdtText {
    return try FfiConverterTypeCrdtText.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtText_lower(_ value: CrdtText) -> RustBuffer {
    return FfiConverterTypeCrdtText.lower(value)
}


/**
 * One step of a local write, mirroring `writeCanvasSnapshot`.
 */

public enum CrdtEdit: Equatable, Hashable {
    
    /**
     * `replaceMapFields(doc.getMap('canvas'), fields)`.
     */
    case replaceCanvas(
        /**
         * The complete field set.
         */fields: [CrdtField]
    )
    /**
     * Make `root[id]` a map holding exactly `fields` (`reconcileRecords`
     * body): absent keys are deleted, a field is only written when its value
     * actually changed, so unrelated concurrent edits merge.
     */
    case replaceRecord(
        /**
         * Which collection.
         */root: CrdtRoot, 
        /**
         * The record id.
         */id: String, 
        /**
         * The complete field set.
         */fields: [CrdtField]
    )
    /**
     * `root.delete(id)`.
     */
    case deleteRecord(
        /**
         * Which collection.
         */root: CrdtRoot, 
        /**
         * The record id.
         */id: String
    )
    /**
     * Make `texts[id]` a `Y.Text` holding `text`, applied as one splice
     * between the common prefix and suffix (`replaceText`).
     */
    case replaceText(
        /**
         * The widget id.
         */id: String, 
        /**
         * The whole new text.
         */text: String
    )
    /**
     * `texts.delete(id)`.
     */
    case deleteText(
        /**
         * The widget id.
         */id: String
    )
    /**
     * Delete every key of `root` not in `ids` (a first write with no previous
     * snapshot walks `root.keys()`).
     */
    case retainRecords(
        /**
         * Which collection.
         */root: CrdtRoot, 
        /**
         * The ids that stay.
         */ids: [String]
    )
    /**
     * Delete every `texts` key not in `ids`.
     */
    case retainTexts(
        /**
         * The widget ids whose text stays.
         */ids: [String]
    )





}

#if compiler(>=6)
extension CrdtEdit: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrdtEdit: FfiConverterRustBuffer {
    typealias SwiftType = CrdtEdit

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CrdtEdit {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .replaceCanvas(fields: try FfiConverterSequenceTypeCrdtField.read(from: &buf)
        )
        
        case 2: return .replaceRecord(root: try FfiConverterTypeCrdtRoot.read(from: &buf), id: try FfiConverterString.read(from: &buf), fields: try FfiConverterSequenceTypeCrdtField.read(from: &buf)
        )
        
        case 3: return .deleteRecord(root: try FfiConverterTypeCrdtRoot.read(from: &buf), id: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .replaceText(id: try FfiConverterString.read(from: &buf), text: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .deleteText(id: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .retainRecords(root: try FfiConverterTypeCrdtRoot.read(from: &buf), ids: try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 7: return .retainTexts(ids: try FfiConverterSequenceString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CrdtEdit, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .replaceCanvas(fields):
            writeInt(&buf, Int32(1))
            FfiConverterSequenceTypeCrdtField.write(fields, into: &buf)
            
        
        case let .replaceRecord(root,id,fields):
            writeInt(&buf, Int32(2))
            FfiConverterTypeCrdtRoot.write(root, into: &buf)
            FfiConverterString.write(id, into: &buf)
            FfiConverterSequenceTypeCrdtField.write(fields, into: &buf)
            
        
        case let .deleteRecord(root,id):
            writeInt(&buf, Int32(3))
            FfiConverterTypeCrdtRoot.write(root, into: &buf)
            FfiConverterString.write(id, into: &buf)
            
        
        case let .replaceText(id,text):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(id, into: &buf)
            FfiConverterString.write(text, into: &buf)
            
        
        case let .deleteText(id):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .retainRecords(root,ids):
            writeInt(&buf, Int32(6))
            FfiConverterTypeCrdtRoot.write(root, into: &buf)
            FfiConverterSequenceString.write(ids, into: &buf)
            
        
        case let .retainTexts(ids):
            writeInt(&buf, Int32(7))
            FfiConverterSequenceString.write(ids, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtEdit_lift(_ buf: RustBuffer) throws -> CrdtEdit {
    return try FfiConverterTypeCrdtEdit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtEdit_lower(_ value: CrdtEdit) -> RustBuffer {
    return FfiConverterTypeCrdtEdit.lower(value)
}



/**
 * Why a call into the engine failed.
 */
public 
enum CrdtError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * An incoming update could not be decoded or applied.
     */
    case Update(message: String
    )
    /**
     * A field value was not valid JSON.
     */
    case Json(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CrdtError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrdtError: FfiConverterRustBuffer {
    typealias SwiftType = CrdtError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CrdtError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Update(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Json(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CrdtError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Update(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Json(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtError_lift(_ buf: RustBuffer) throws -> CrdtError {
    return try FfiConverterTypeCrdtError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtError_lower(_ value: CrdtError) -> RustBuffer {
    return FfiConverterTypeCrdtError.lower(value)
}


/**
 * The four record collections. Canvas metadata and note text have their own
 * edits.
 */

public enum CrdtRoot: Equatable, Hashable {
    
    /**
     * `widgets` — widget records without their collaborative `data.text`.
     */
    case widgets
    /**
     * `relations`
     */
    case relations
    /**
     * `connections`
     */
    case connections
    /**
     * `glues`
     */
    case glues





}

#if compiler(>=6)
extension CrdtRoot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrdtRoot: FfiConverterRustBuffer {
    typealias SwiftType = CrdtRoot

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CrdtRoot {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .widgets
        
        case 2: return .relations
        
        case 3: return .connections
        
        case 4: return .glues
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CrdtRoot, into buf: inout [UInt8]) {
        switch value {
        
        
        case .widgets:
            writeInt(&buf, Int32(1))
        
        
        case .relations:
            writeInt(&buf, Int32(2))
        
        
        case .connections:
            writeInt(&buf, Int32(3))
        
        
        case .glues:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtRoot_lift(_ buf: RustBuffer) throws -> CrdtRoot {
    return try FfiConverterTypeCrdtRoot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrdtRoot_lower(_ value: CrdtRoot) -> RustBuffer {
    return FfiConverterTypeCrdtRoot.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCrdtField: FfiConverterRustBuffer {
    typealias SwiftType = [CrdtField]

    public static func write(_ value: [CrdtField], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCrdtField.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CrdtField] {
        let len: Int32 = try readInt(&buf)
        var seq = [CrdtField]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCrdtField.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCrdtRecord: FfiConverterRustBuffer {
    typealias SwiftType = [CrdtRecord]

    public static func write(_ value: [CrdtRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCrdtRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CrdtRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [CrdtRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCrdtRecord.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCrdtText: FfiConverterRustBuffer {
    typealias SwiftType = [CrdtText]

    public static func write(_ value: [CrdtText], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCrdtText.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CrdtText] {
        let len: Int32 = try readInt(&buf)
        var seq = [CrdtText]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCrdtText.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCrdtEdit: FfiConverterRustBuffer {
    typealias SwiftType = [CrdtEdit]

    public static func write(_ value: [CrdtEdit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCrdtEdit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CrdtEdit] {
        let len: Int32 = try readInt(&buf)
        var seq = [CrdtEdit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCrdtEdit.read(from: &buf))
        }
        return seq
    }
}
/**
 * `Y.mergeUpdates`: the offline queue folds long bursts into one update.
 */
public func mergeUpdates(updates: [Data])throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCrdtError_lift) {
        uniffiCallStatus in
    uniffi_grovepad_yrs_fn_func_merge_updates(
        FfiConverterSequenceData.lower(updates),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_grovepad_yrs_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_grovepad_yrs_checksum_func_merge_updates() != 16635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_apply_local_edits() != 543) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_apply_remote_edits() != 55185) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_apply_remote_update() != 10963) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_can_redo() != 42068) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_can_undo() != 34269) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_clear_undo_history() != 19589) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_client_id() != 33922) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_encode_state_as_update() != 5797) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_read_snapshot() != 24719) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_redo() != 8158) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_method_canvascrdt_undo() != 28573) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_grovepad_yrs_checksum_constructor_canvascrdt_new() != 24189) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureGrovepadYrsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all